### ISSUE TITLE
Dash DocSet support

### ISSUE THREAD

**Issue by joepie91** [Thibaut/devdocs#117]
I brought up the possibility of having the documentation for Bookshelf.js on DevDocs as well for easy reference (tgriesser/bookshelf#455), and the issue was brought up that the DevDocs data is apparently not in a structured format - which I'd say is a fairly good point.

It would probably be a good idea to support reading Dash DocSets (if not using them for storage entirely, insofar that is feasible). This would not only allow for the use of appropriately-licensed third-party Dash sets, but would also make it easier for a project developer to submit their *own* documentation in a structured format, rather than having to rely on a scraper (which would require maintenance when the source documentation format is changed for any reason).

The Dash format [doesn't seem to be too complicated](https://github.com/exlee/d3-dash-gen/blob/master/parse.ls), apparently it's just SQLite with XML and regular HTML/CSS/JS.

**Comment by Thibaut** [comment]
A structured format may come later this year but DevDocs won't support Dash's format itself.

**Comment by joepie91** [comment]
@Thibaut Any update on the Bookshelf / Knex documentation?

**Comment by Thibaut** [comment]
@joepie91 I'm still waiting for https://github.com/tgriesser/knex/issues/449 and for the projects to grow in popularity (to justify jumping the list at https://trello.com/b/6BmTulfx/devdocs-documentation).
