### ISSUE TITLE
Permission denied on downloading docs

### ISSUE THREAD

**Issue by kirara** [Thibaut/devdocs#144]
Running 'thor docs:download php' on Windows I get:
> (1/1) PHP FAILED (Errno::EACCES: Permission denied @ sys_fail2 - (S:/Users/Kirara/AppData/Local/Temp/open-uri20141221-13768-138kyeu, D:/root/devdocs/public/docs/php.tar.gz))

Both mentioned directories are writable and I actually tried running it from commandline as Administrator. Same result.

**Comment by Thibaut** [comment]
Closing as I don't think this can be fixed in DevDocs (file permission issue).
