### ISSUE TITLE
Working code examples?

### ISSUE THREAD

**Issue by abailey-et** [Thibaut/devdocs#147]
How much work would it be to have the option to open a side panel with a list of links to working code examples? 

I think there's so many code snippets around the web especially on CodePen, Plunker, JSFiddle, PythonFiddle etc. that extracting a working snippet from their site that is related to the documentation might be useful. Probably won't apply to every language of course.

**Comment by utensil** [comment]
:+1:

**Comment by Thibaut** [comment]
Thanks for the suggestion.

I've thought about this but I think it's too much work (we'd need to keep the lists useful and up-to-date, vs. almost all the content DevDocs aggregates now is automated) and adding too much clutter to the UI (side panel) for a small benefit.

DevDocs's primary mission is about reference documentation, not really tutorials &co. Sorry.
