### ISSUE TITLE
Ruby 2.2.0 not detected as default ruby

### ISSUE THREAD

**Issue by Edelwin** [Thibaut/devdocs#148]
```
edelwin@melinoe 15:23 (master) ~/repos/devdocs ❯❯ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
edelwin@melinoe 15:23 (master) ~/repos/devdocs ❯❯ bundle install
Your Ruby version is 2.0.0, but your Gemfile specified 2.2.0
```
Do you have any idea about the origin of the problem?

**Comment by MForever78** [comment]
@Edelwin I had the same problem.

My situation is, at the time when I install bundler, my ruby is below 2.2.0. And then I updated ruby, the bundler still thought my ruby is below 2.2.0.

Solution: uninstall bundler and gem install it again.

Hope it helps.

**Comment by ArpiaPsuv** [comment]
@ MForever78  @ MForever78 

browse to the directory where you have the application
delete this file /devdocs-master/Gemfile.lock 
now run on your terminal ruby-v  the output will be something like this depending
on the version:

ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

must now edit the Gemfile and add your version of ruby
  it look something like this

source 'https://rubygems.org'
ruby "2.2.0"
ruby "2.1.5"

**Comment by MForever78** [comment]
@ArpiaPsuv 

Oh, are you providing solution to the problem? I had the same problem but I fixed it by reinstall bundler, as I said. Maybe you should @Edelwin .

I wonder if it is safe to edit the Gemfile to modify the specific ruby version? No idea how devdocs is working, just ask.

I think both your solution and mine are quite brutal. Maybe there's a way to edit some file just related to bundler, cuz it's just bundler who cause the problem.

**Comment by ArpiaPsuv** [comment]
anyway the solution is the same must be added a conditional, specifying that the required vercion ruby is greater than 2.0.0 or 1.9.3

also if you change these lines this 

source 'https://rubygems.org'
ruby "2.2.0"
ruby "2.1.5"

gem 'thor'
gem 'pry', '~> 0.9.12'
gem 'activesupport', '~> 4.0', require: false
gem 'yajl-ruby', require: false

group :app do
  gem 'rack'
  gem 'sinatra'
  gem 'sinatra-contrib'
  gem 'thin'
  gem 'sprockets'
  gem 'sprockets-helpers'
  gem 'erubis'
  gem 'browser'
  gem 'sass'
  gem 'coffee-script'
end

group :production do
  gem 'uglifier'
end

group :development do
  gem 'better_errors'
end

group :docs do
  gem 'typhoeus'
  gem 'nokogiri', '~> 1.6.0'
  gem 'html-pipeline'
  gem 'progress_bar', require: false
  gem 'unix_utils', require: false
end

group :test do
  gem 'minitest'
  gem 'rr', require: false
end

if ENV['SELENIUM'] == '1'
  gem 'capybara'
  gem 'selenium-webdriver'
end

for that    be will work 
source 'https://rubygems.org'


gem 'thor'
gem 'pry', '~> 0.9.12'
gem 'activesupport', '~> 4.0', require: false
gem 'yajl-ruby', require: false

group :app do
  gem 'rack'
  gem 'sinatra'
  gem 'sinatra-contrib'
  gem 'thin'
  gem 'sprockets'
  gem 'sprockets-helpers'
  gem 'erubis'
  gem 'browser'
  gem 'sass'
  gem 'coffee-script'
end

group :production do
  gem 'uglifier'
end

group :development do
  gem 'better_errors'
end

group :docs do
  gem 'typhoeus'
  gem 'nokogiri', '~> 1.6.0'
  gem 'html-pipeline'
  gem 'progress_bar', require: false
  gem 'unix_utils', require: false
end

group :test do
  gem 'minitest'
  gem 'rr', require: false
end

if ENV['SELENIUM'] == '1'
  gem 'capybara'
  gem 'selenium-webdriver'
end

**Comment by Thibaut** [comment]
Re-installing `bundler` and restarting your shell should fix this.

The Ruby version specified in the `Gemfile` is the only one officially supported. You can remove that line and use a different version, but then some things might stop working (for now DevDocs is still compatible with Ruby 2.1, though).

Thanks for your help @MForever78!
