### ISSUE TITLE
Can't constrain search to C++ docset

### ISSUE THREAD

**Issue by yacoob** [Thibaut/devdocs#151]
I can type `C<TAB>` and search for C documentation only.

If I type `C++<TAB>`, the expected constraining to C++ docs doesn't happen. Looks like the `++` is throwing the parser off.

**Comment by ymeine** [comment]
In the meantime I think you can type `cpp<TAB>`, it worked for me!

**Comment by Thibaut** [comment]
Thanks!

**Comment by yacoob** [comment]
Most delightful. Thank you :)
