### ISSUE TITLE
Improve documentation tree _structuring_ (order, ...) and _navigation_ (icons, ...)

### ISSUE THREAD

**Issue by wheredevel** [Thibaut/devdocs#152]
I want to navigate more quickly (and pleasantly) in the doc tree.

Icons.
First level has icons and text - ok! Helps me find, for example, Mongoose.
I'd like to see icons on the next levels too!
What is that - guide, api, tutorial, ...?
What is that - function, property, ...?
// Please, don't make me think.

Order
And the order is important too. I.e. "Getting Started" should precede the rest, I assume.
Mongoose, for example, have, probably, thought about a good section order for their audience. DevDocs remixed it into alphabetical order. 
// Bummer.

**Comment by Thibaut** [comment]
I moved the "Guide" / "Getting Started" categories to the top. Function/Property/etc. tagging will come later, probably without icons though.
