### ISSUE TITLE
Offline database size limitation on Firefox web app

### ISSUE THREAD

**Issue by cilq** [Thibaut/devdocs#154]
When enough documentations are stored offline, so that the sqlite file reaches about 50 MB, the web app is not able to access it anymore. The interface is fully functional, but opening the Offline tab results in the message
> Oops, the database failed to load.

This also prevents the user from resetting the app.
After deleting the storage files in `[Profile_directory]/storage/default`, the app is fully functional again.
The web app was created using Firefox Developer Edition 37.0a2, however the web version on the same browser has no such size limitation.

**Comment by Thibaut** [comment]
Thanks for the bug report. I'll look into this as soon as I can.

**Comment by Thibaut** [comment]
Unfortunately there's no way to programmatically detect what the size limitation is, and once the quota is reached the database is locked and can't be opened anymore (at least in Firefox).

As a work-around I made it so the database is automatically deleted when the quota is reached, with a notification explaining why.
