### ISSUE TITLE
Bringing back Yii 1.1 docs

### ISSUE THREAD

**Issue by maciejtarnowski** [Thibaut/devdocs#157]
Yii2 was a complete rework of the framework and the company I work for is still using Yii 1.1 in quite a few projects. Me and my colleagues would really appreciate availability of the older documentation as devdocs is much easier and faster to use than project's homepage. Does it make sense to add separate documentation labeled for example "Yii1"? I think I could try to do that and create a pull request, but I would like to get some feedback beforehand.

Thanks!

**Comment by Thibaut** [comment]
Multi-version support is planned for the future but not yet supported. In the meantime I'll try to bring back Yii 1.1 as a separate documentation next week-end.

**Comment by maciejtarnowski** [comment]
Thank you @Thibaut !
