### ISSUE TITLE
Microsoft Javascript docs

### ISSUE THREAD

**Issue by morenoh149** [Thibaut/devdocs#158]
Are surprisingly good! https://msdn.microsoft.com/en-us/library/ff679977%28v=VS.94%29.aspx
I'm not a microsoft fanboy by any means. But I was wondering if anyone other js devs have reviewed these. Seem to be at par or better than the mdn docs.

Anyway to have more than one set of js docs?

**Comment by Thibaut** [comment]
Unfortunately these docs are proprietary:

> All Microsoft Content is the copyrighted work of Microsoft or its suppliers, and is governed by the terms of the license agreement that accompanies or is included with the Microsoft Content. If the Microsoft Content does not include a license agreement, then you may make a reasonable number of copies of the Microsoft Content for your internal use in designing, developing, and testing your software, products and services that is made available to you on the Documentation Portals without a license agreement.

https://msdn.microsoft.com/en-us/cc300389
