### ISSUE TITLE
doc list icons

### ISSUE THREAD

**Issue by skibz** [Thibaut/devdocs#160]
hardly an "issue", more nit-picky than anything, but...
with the new dark skin option, some icons don't appear as well as they could (coffeescript and backbone for instance)
what could be done to restore the clarity of some of the hard to view icons?

**Comment by RossBarnie** [comment]
Same for Markdown.

The [File Icons](https://github.com/DanBrooker/file-icons) atom package handles this really well, if anyone wants to look into it.
