### ISSUE TITLE
Add Wordpress Documentation

### ISSUE THREAD

**Issue by todoconk** [Thibaut/devdocs#163]
Hey!

Can you add WP Doc ?

Thanks!

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/c/mDIVCppx/85-wordpress

**Comment by selrond** [comment]
@Thibaut any progress on this? Thnk you for your awesome work!

**Comment by j-f1** [comment]
@selrond Please use the “vote” button on the Trello card to show you support.

**Comment by selrond** [comment]
@j-f1 I did a long time ago, that's why I'm asking

**Comment by Thibaut** [comment]
@selrond I won't add the Wordpress doc myself. If someone wants to work on it, I'm happy to get it in, but this is the kind of documentation that would take many hours to implement, and I have a long list of things to do before I'd have the time to work on it.

**Comment by selrond** [comment]
Uderstandable, thanks!
Dňa ne 26. 11. 2017 o 18:32 Thibaut Courouble <notifications@github.com>
napísala(a):

**Comment by sesn** [comment]
@Thibaut , Is this still open? I'm willing to work on wordpress doc. Apart from contributing guide, Can u tell me the steps to follow?

**Comment by j-f1** [comment]
@sesn There’s some [guidance](https://github.com/freeCodeCamp/devdocs/wiki/Adding-documentations-to-DevDocs) in the wiki.
