### ISSUE TITLE
Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by gpgekko** [Thibaut/devdocs#166]
I have been consistently getting this error on my Chromebook for the last week. It happens whenever I press the theme toggle button (to switch to the dark theme). I've tried everything: reloading, resetting, clearing the whole cache just in case...
I don't seem to get it on my pc, and I have no idea why.

**Comment by Thibaut** [comment]
I can see this exception in my error tracking app. Surprisingly it only happens on Chrome OS.

Could you run these commands in the web console (one by one) and send me the results:

```js
$('link[rel="stylesheet"][data-alt]')
$('link[rel="stylesheet"]')
$('link[data-alt]')
document.styleSheets[0].ownerNode
```

Thanks

**Comment by gpgekko** [comment]
Looks fine:
![screenshot 2015-02-15 at 12 30 13](https://cloud.githubusercontent.com/assets/5121420/6203092/70781044-b50e-11e4-9408-3389c343fe28.png)

**Comment by gpgekko** [comment]
In fact, after today's update to DevDocs, it seems to work fine.

**Comment by Thibaut** [comment]
@gpgekko Thanks! The error hasn't happened in 4 days so I'm gonna close this and hope for the best ^^
