### ISSUE TITLE
Links to source code in ember.js are broken.

### ISSUE THREAD

**Issue by chenxsan** [Thibaut/devdocs#171]
For example, [reopenClass method](http://devdocs.io/ember/classes/ember.coreobject#method_reopenClass), that **Defined in** links to: 

https://github.com/emberjs/ember.js/tree//packages/ember-runtime/lib/system/core_object.js#L702

You will get a 404 page because the correct link is:

https://github.com/emberjs/ember.js/tree/v1.10.0/packages/ember-runtime/lib/system/core_object.js#L702. 

The version part `v1.10.0` was left out in the doc now.

**Comment by Thibaut** [comment]
Fixed. Thanks for the bug report.
