### ISSUE TITLE
The information in Offline Page was wrong.

### ISSUE THREAD

**Issue by CzBiX** [Thibaut/devdocs#173]
I installed the webapps in Firefox from https://marketplace.firefox.com/app/devdocs/.
The offline mode was works fine.
But in the offline pages, it was show the wrong information.
![20150304-122248-5c7e](https://cloud.githubusercontent.com/assets/760097/6478230/3c57843a-c269-11e4-8db5-c90b983f032c.png)

**Comment by Thibaut** [comment]
>  The offline mode was works fine.

Do you mean you can close the app / shutdown your computer, and still re-open it offline?

**Comment by CzBiX** [comment]
@Thibaut Yes! It's works well without problems.
