### ISSUE TITLE
alt+s to search stackoverflow?

### ISSUE THREAD

**Issue by run-time** [Thibaut/devdocs#174]
I find myself using the alt+g shortcut to search google but due to the nature of this content the stuff I'm looking for is usually on stackoverflow.

How hard would it be to add another shortcut key to search stackoverflow?

Even better if it could search stackoverflow using the tag for the root level documentation type I am currently in.

Example:

If I search stackoverflow using this text, "[angularjs] date time directive" it will find things tagged with angularjs and all the other text in the query.

This is the URL it goes to  --  
http://stackoverflow.com/search?q=%5Bangularjs%5D+date+time+directive

**Comment by Thibaut** [comment]
:+1: I'll add this within the next week or two.
