### ISSUE TITLE
Move disable to the top

### ISSUE THREAD

**Issue by saaqibz** [Thibaut/devdocs#176]
I could not find the disable docs options for a while and I wonder if others are having the same issue. Maybe move it to the top instead of the bottom of the left nav?

Thanks for making a wonderful app.

**Comment by Thibaut** [comment]
Thanks for the suggestion. The "disabled" list is open by default so I don't think we need to move it to the top; it'd look kind of awkward.

![devdocs - private browsing 2015-03-14 09-10-11](https://cloud.githubusercontent.com/assets/17579/6651762/f1d06c06-ca29-11e4-83e8-be09d346f321.png)

But you are right that the discoverability of this list isn't great. I'll try to improve this in a future update.
