### ISSUE TITLE
<code> font hard to read

### ISSUE THREAD

**Issue by komplexb** [Thibaut/devdocs#177]
The the font style for `syntax` is too similar to the regular reading font, so its a little hard to see when a word is actually code syntax. Note the styling of the `this` keyword in the screenshots.
![devdocs-default](https://cloud.githubusercontent.com/assets/3874813/6587677/7387cdd4-c755-11e4-9497-bf7ca133dba7.png)

Seems to be more pronounced in Chrome than FireFox, it appears you have decent contrast for block-code areas, so I guess this is just a consistency issue. In the example below the `font-family` attribute for the `code` element is unchecked.
![devdocs-edit](https://cloud.githubusercontent.com/assets/3874813/6587676/73819b26-c755-11e4-9514-251de1e01504.png)

**Comment by nazrhyn** [comment]
It probably wouldn't work for the dark theme, as such, but I've always been a fan of the red and grey that Slack uses:
![slackinlinecode](https://cloud.githubusercontent.com/assets/1672405/6639506/a7693d64-c966-11e4-84cc-35b88d81b6ce.png)

**Comment by Thibaut** [comment]
I changed the code font to the one used by GitHub. It should provide better contrast compared to the normal font.

I'd rather not style every `code` element with a different background/border as I think it hurts readability when overused.

**Comment by nazrhyn** [comment]
I think the Slack one probably makes more sense in the chat context. Having a Christmas tree of code boxes that stand out too much is definitely suboptimal.

**Comment by komplexb** [comment]
Is the change already in place? Not seeing it reflected in my instance.

**Comment by Thibaut** [comment]
@komplexb The change is live on [devdocs.io](http://devdocs.io) yes.
