### ISSUE TITLE
Reloading after opening article loads "rooted" with no search box filter

### ISSUE THREAD

**Issue by nazrhyn** [Thibaut/devdocs#178]
#### Introduction ####
I've been trying to nail down the steps for this for a few days now and I finally got it!

#### Steps ####
1. Enable **Node.js** and at least one other language.
1. In the search box...
    1. Type `node<TAB>` to enable the filter.
    1. Type `unlink<ENTER>` to select the **fs.unlink** article.

        > *This will open the unlink article, and rewrite the URL to `/node/fs#fs_fs_unlink_path_callback`.*
1. Reload the page.

    > *For me, this happens when my previous tabs are re-opened the next day from their previous-day state.*

#### Results ####
What happens is that the site loads in the `/node` folder and from that point on is "rooted" to the **Node.js** documentation. There's no clear way to get back to other languages outside of clicking the **DevDocs** link or manually going to the site root.

To me, if the site is rewriting the URL to add the new documentation path, reloading should return it to the state it was in when it got rewritten rather than the "rooted" state that it loads in now. That is, the search box should contain the filter and the full tree should be displayed with the appropriate documentation article selected.

#### Aside ####
DevDocs is a fantastic idea that has been very well executed. It is a permanently-open tab for me, at work. This issue is absolutely a minor inconvenience, but I wanted to report it as I didn't see it in the list of open issues. Thanks for creating this awesome tool!

**Comment by Thibaut** [comment]
Thanks for the detailed issue.

This is the intended behavior (there is a banner at the bottom of the page that tells you when the app is in "single doc" mode). It's required because of how DevDocs work (to keep things fast, only the docs the user has selected are loaded in memory), as well as limitations in the AppCache API (which is only reliable on the root path).

To go from "single doc" mode to "full app" mode you can also press `escape` twice.

**Comment by nazrhyn** [comment]
I see, thanks for the response! Maybe to improve the discoverability of that shortcut, it could be parenthetically included in that bottom banner?

**Comment by Thibaut** [comment]
Good idea. I'll add this next week-end.
