### ISSUE TITLE
Filesystem Docs Missing

### ISSUE THREAD

**Issue by DanielHerr** [Thibaut/devdocs#179]
The Filesystem API doesn't have any docs. You can use Mozilla's: https://developer.mozilla.org/en-US/docs/Web/API/File_System_API

**Comment by Thibaut** [comment]
This API won't be included in DevDocs until MDN removes the banner that says:

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user.

Sorry.
