### ISSUE TITLE
`_.isElement(document.body)` is returning `false`.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [Thibaut/devdocs#180]
I am testing this in plunker. And i saw `_.isElement(document.body)` is returning `false`. But as per the documentation, it should return `true`.

**Comment by Thibaut** [comment]
Wrong repo. DevDocs is just a documentation tool, not a library.

**Comment by rajeshwarpatlolla** [comment]
When i click on `I found a bug, where do I report it?
In the issue tracker. Thanks!` which was in `http://devdocs.io/offline` it re directed to this repo only. So i raised this issue. Could you please let me know which is the corresponding directory to post this issue?

**Comment by Thibaut** [comment]
The bug isn't in the DevDocs app itself (this repo), it's in whichever library you're reading the docs of (I'm guessing either [Underscore.js](https://github.com/jashkenas/underscore) or [lodash](https://github.com/lodash/lodash)).

**Comment by rajeshwarpatlolla** [comment]
Yes, it is lodash related bug.
