### ISSUE TITLE
Provide Meteor framework documentation

### ISSUE THREAD

**Issue by gvagenas** [Thibaut/devdocs#181]
Please provide meteor framework documentation http://docs.meteor.com/#/full/

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/c/BWo1ted2/36-meteor

**Comment by gvagenas** [comment]
Sorry for opening the issue, I should have checked the wiki first.
Thanks

**Comment by Thibaut** [comment]
No problem
