### ISSUE TITLE
Ruby 2.2.1 and Could not find ffi-1.9.7 in any of the sources

### ISSUE THREAD

**Issue by nszceta** [Thibaut/devdocs#182]
bundle install fails with latest ruby update available for homebrew on OS X

After editing the Gemfile to support Ruby 2.2.1, I am still getting

```
Could not find ffi-1.9.7 in any of the sources
```

Workaround:

```
bundle update ffi
bundle install
```

**Comment by Thibaut** [comment]
This is because ffi 1.9.7 was yanked. I've updated the Gemfile to require 1.9.8.

**Comment by ohadpartuck** [comment]
+1 . thanks
