### ISSUE TITLE
Display density

### ISSUE THREAD

**Issue by adius** [Thibaut/devdocs#184]
It would be cool if there was a setting to change the size of the UI elements like on gmail, which has the settings comfortable, cozy and compact.

Of course one can simply zoom out of the website a little, but this breaks currently the layout.

**Comment by Thibaut** [comment]
Browsers already handle zooming in & out pretty well. I'd rather keep DevDocs simple and not re-invent the wheel.

> but this breaks currently the layout.

This should work. Could you post a screenshot?

**Comment by adius** [comment]
I'm not sure why the layout war broken before. Can't reproduce it anymore.
It does work pretty good with zooming for me as well now.
