### ISSUE TITLE
Tried building from source; core dumps

### ISSUE THREAD

**Issue by lpar** [Thibaut/devdocs#186]
Currently running Fedora 21 and Xfce. Installed the necessary Qt5 packages, successfully built a binary. However:

    % bin/zeal 
    libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
    Cannot mix incompatible Qt library (version 0x50400) with this library (version 0x50401)
    zsh: abort (core dumped)  bin/zeal

Any ideas how I could help track down the cause?

A working Linux binary for download would be really helpful.

**Comment by Thibaut** [comment]
https://github.com/zealdocs/zeal

**Comment by lpar** [comment]
> Fedora 19
> There is no rpm package yet, but Zeal can be easily built from scratch. 

That's what I did. Apparently it can't easily be built from scratch.

**Comment by Thibaut** [comment]
You are in the wrong repo.

**Comment by lpar** [comment]
Oh! Sorry.
