### ISSUE TITLE
Offline version problem

### ISSUE THREAD

**Issue by jekyl32** [Thibaut/devdocs#187]
Hi.

This is not critical but when I installed offline version of php docs the links in section See Also still refer to php.net.

Dont'n know what happen with rest of docs.

Great app !!!

**Comment by Thibaut** [comment]
Hey
Thanks for the bug report. This is known issue with the PHP doc, which has poorly-organized links and URLs. Unfortunately I cannot fix it at this time, sorry. See #36 and #71 for more info.

**Comment by Hipska** [comment]
See what I meant? (#89) Other issues will keep coming until you leave one open..
