### ISSUE TITLE
Quickly disable one docset  (just like enable one docset)

### ISSUE THREAD

**Issue by yleo77** [Thibaut/devdocs#189]
For now, enable a docset by clicking the enable trigger  in the disabled  list  is a very useful function for me.

I wanna a similar function  that is disable a docset quickly by clicking something related to this docset.

Do you have any advise or plan for this thing?

Thanks.

**Comment by Thibaut** [comment]
Thanks for the suggestion. I don't want to add the same kind of link to "disable" than to "enable" because I don't think most people disable docs very often — it'd just clutter the UI. Sorry.

**Comment by Kaijun** [comment]
for people who also misclicked enable button and wanted to re-disable it:

clear the cookie and the list of enabled docsets will be restored to the original preset.

**Comment by Thibaut** [comment]
@Kaijun or you can just click "Select documentation" and uncheck any docs you don't want

**Comment by cpury** [comment]
@Thibaut I can't find this "Select documentation", could you provide a more detailed description or screenshot of it?

UX-wise, I think it is very confusing that I can't disable the same way I enable docs. And since by default you enable so many web-related docs, all the non-web-devs that don't care about DOM etc. will be frustrated quickly if they can't find the disable button.

**Comment by Thibaut** [comment]
@cpury the UI has changed since this issue was created. Doc enabling/disabling is now done on the Preferences page:

![devdocs api documentation 2017-07-18 08-16-55](https://user-images.githubusercontent.com/17579/28316601-82c6a030-6b91-11e7-98fe-8db014f7e065.png)

http://devdocs.io/settings

**Comment by cpury** [comment]
@Thibaut ohhh thanks! I had already been in the preferences and looked for a way to manage my docs, and totally did not see the checkboxes that sneakily get added on the left. I think your UX could really be a little more straightforward here.

In all other ways, great product! Thanks for building it.

**Comment by Thibaut** [comment]
@cpury thanks for the feedback. I'll try to improve this in the future.

**Comment by lewallen** [comment]
Wow, it also took me several visits to Preferences to see those checkboxes, and over all it took ~10 minutes of web search to figure out how to disable (first time user). When you do get a chance, it would be awesome to improve it.

Anyway, amazing work and thanks so much for the project.

**Comment by Thibaut** [comment]
Another reason why there aren't "Disable" links like there are for "Enable" is that disabling documentations requires a full-page reload, whereas enabling documentations one by one doesn't (unloading already-loaded data is more complicated than loading additional data).

That said, I made a bunch of improvements over the week-end:

- Added a "Customize" link next to the "Disabled" title in the sidebar (only visible on hover, like the "Enable" links).

  ![devdocs api documentation 2017-08-08 08-23-42](https://user-images.githubusercontent.com/17579/29071790-12e4b3fa-7c13-11e7-9ee1-8e540d00d7cb.png)

- Added labels to the list of documentation on the preferences page, so the checkboxes are more obvious.

  ![devdocs preferences 2017-08-08 08-27-17](https://user-images.githubusercontent.com/17579/29071863-6a855cfe-7c13-11e7-999c-c3c4ba1aa7e4.png)

- Moved the "Apply" button on the preferences page to the top-left corner (replacing the "Back" button), to make it more clear that this button must be clicked for changes to take effect.

  ![devdocs preferences 2017-08-08 08-30-20](https://user-images.githubusercontent.com/17579/29071962-d61c11f6-7c13-11e7-85a7-b89bc80f2bbc.png)

Thanks for the feedback everyone!

**Comment by bslade** [comment]
Re: Another reason why there aren't "Disable" links like there are for "Enable" is that disabling documentations requires a full-page reload

For me, a full page reload when disabling a document entry in the right sidebar is not big deal.  I don't disable document entries that often.   I think it's far more important to make the user interface consistent.  Ie., have a "disable document entry" work the same way as "enable document entry".  Especially for newbies.

But I appreciate all those who support the DevDocsAPI website.  It's a great tool
