### ISSUE TITLE
Add links to the official website on each documentation's root page

### ISSUE THREAD

**Issue by Thibaut** [Thibaut/devdocs#19]
Related issue: #18

**Comment by TrangPham** [comment]
@Thibaut Do you think this should be added similar to how `attribution` is added to each root page?

**Comment by Thibaut** [comment]
@TrangPham Yes, except the attribution is added to all pages. This I would probably only add to the root page, and put it at the top instead of the bottom.

**Comment by TrangPham** [comment]
@Thibaut Thanks. I will try to tackle this.
