### ISSUE TITLE
add angular-formly

### ISSUE THREAD

**Issue by kentcdodds** [Thibaut/devdocs#190]
[angular-formly](http://docs.angular-formly.com) (by yours truly). Would love to see this on devdocs. Would a pull request for adding this library be accepted?

**Comment by Thibaut** [comment]
Hey Kent
Yes I would gladly accept a pull request. Note however that DevDocs isn't well suited for UI frameworks (if you want to show examples) because it removes all JS and CSS from the original docs.

**Comment by kentcdodds** [comment]
If I understand you correctly, that shouldn't be a problem. I just had someone ask if they could get docs offline and my first thought was devdocs. Thanks for your great work!

**Comment by Thibaut** [comment]
Cool!
There is no scraper for `readme.io`-powered docs yet in the repo so this might not be super straightforward to implement. Feel free to post questions here if you need a hand.

**Comment by kentcdodds** [comment]
I probably will... Never done ruby before.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by Thibaut** [comment]
Don't think we need to keep this open.

**Comment by kentcdodds** [comment]
Understood. Thanks. FYI @mikeerickson
