### ISSUE TITLE
MongoDB docs license update

### ISSUE THREAD

**Issue by lorensr** [Thibaut/devdocs#191]
MongoDB says DevDocs should be able to add its docs:

![image](https://cloud.githubusercontent.com/assets/251288/6999032/2d95ecb4-dbac-11e4-80bd-589c30de8426.png)

http://docs.mongodb.org/manual/about/

In which case the pictured Trello notice is out of date.

**Comment by Thibaut** [comment]
Thanks for bringing this up to their attention. 
https://twitter.com/DevDocs/status/584854282471661568
We'll see what they say.

**Comment by lorensr** [comment]
Thanks for the details! I'm down to two docs tabs pinned and always open, hoping it will come down to one. Their docs UI feels worse the more I use devdocs :)
