### ISSUE TITLE
Create 'Installable Web App' Button

### ISSUE THREAD

**Issue by berbaquero** [Thibaut/devdocs#192]
On Firefox, you can add an option to Install a Web-app with the [Web App Manifest](https://developer.mozilla.org/en-US/Apps/Build/Manifest#Requirements_for_generic_Open_Web_Apps).

It could basically work like this:
![screen shot 2015-04-08 at 11 17 26](https://cloud.githubusercontent.com/assets/1769951/7042276/f1342272-dde0-11e4-9171-dfc07b9ba269.png)

Once you click the 'Install' link, the browser will ask for confirmation, and if confirmed by the user, it will Install the Web-app as a standalone app on the OS. Basically the same as a Fluid app, but without actually needing any external tool.

I'd love to have this option on DevDocs. If it's something you think makes sense for DevDocs, I could try to add it myself. :)

**Comment by berbaquero** [comment]
Hmm, just saw the official Firefox Marketplace link, so I guess this 'Install' button could be redundant.

**Comment by Thibaut** [comment]
It's still a good idea to replace the link with a button to install the app (maybe not as prominent as in your screenshot, since it's Firefox-only at the moment). I'll look into that soon.

FYI DevDocs's manifest is here: http://devdocs.io/manifest.webapp

**Comment by berbaquero** [comment]
Well, the 'Install' button on the screenshot would of course only be shown on Firefox browsers, anyway.

Cool that you like the idea, in any case; installing directly from the browser would be very good, indeed.

**Comment by Thibaut** [comment]
Closing this as Mozilla is removing the web app runtime from Firefox (https://www.fxsitecompat.com/en-CA/docs/2016/web-app-runtime-will-be-removed-from-firefox-for-desktop-and-android/).
