### ISSUE TITLE
Reserved abbreviations

### ISSUE THREAD

**Issue by timseverien** [Thibaut/devdocs#193]
When searching for a JavaScript method, like Array.join, I typically type: 

    js Array.join

The abbreviation `js` is extended to one of the many JS libraries, frameworks and tools, as they are an exact match to `js`, yet JavaScript does not. Similarly, typing `md`, a very common abbreviation for Markdown, rarely lists Markdown, depending on which modules are enabled. For me, it shows the PHP’s md5 function. A third example would be Sass’ file extension `scss`.

Perhaps a set of common abbreviations could be implemented as aliases that is searched through prior to the global fuzzy search. Being able to customise those could also be a great improvement.

For now, I’ll just teach myself to use `jsc` or something because I’m not giving up on this brilliant tool.

**Comment by Thibaut** [comment]
:+1: 

Will look into that soon.

**Comment by timseverien** [comment]
*smooch*

:+1:
