### ISSUE TITLE
Solarized theme for dark mode

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Thibaut/devdocs#194]
I'm really happy to see a dark mode; but honestly, it can be kind of hard to read; and a lot of the colours don't have quite enough contrast.

Have you considered using the ‘[Solarized](http://ethanschoonover.com/solarized)’ colour-scheme? It's very popular, and extremely readable in both light *and* dark mode. (In fact, that's precisely what it was designed to do: choose colours with scientifically-backed contrast levels between each colour and both the light and dark backgrounds.)

Hell, if I had my way, I'd love to see both the light *and* dark modes changed to adhere to Solarized. :P

**Comment by Thibaut** [comment]
Thanks for the feedback. I'll look into. 

Which colors don't have enough contrast for you?

**Comment by ELLIOTTCABLE** [comment]
Actually, I think it's just the new-user note on the landing page (with the green background) that's so egregiously bad in dark mode. Looks like I jumped to conclusions. (=

Other things worth noting: the section-headers could do with a little more contrast, but it's not horrible; and the table-border lines are almost invisible in dark-mode.

That said, I'd still love to see a switch to Solarized; but that's probably a bit subjective of me. :P

**Comment by ELLIOTTCABLE** [comment]
:+1:
