### ISSUE TITLE
Offline mode in Safari

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Thibaut/devdocs#195]
So, Safari 7.1+ [supports IndexedDB](http://caniuse.com/#feat=indexeddb). Unfortunately, I still get this error when trying to use Offline Mode:

> #### Oops, the database failed to load.
> DevDocs requires IndexedDB to cache documentations for offline access.
> Unfortunately IndexedDB is either not supported in your browser, disabled, or buggy.

If there's any aid I can provide in tracking this bug down, if you don't have access to a Safari, let me know. (Related: perhaps inclusion of the [WebSql / IndexedDB shim](http://nparashuram.com/IndexedDBShim/) would be a worthwhile addition? That'd bring [slightly older](http://caniuse.com/#search=WebSql) iOS and OS X versions into the fold, so to speak.

**Comment by Thibaut** [comment]
Unfortunately Safari's IndexedDB has multiple bugs that make it pretty much useless:

https://bugs.webkit.org/show_bug.cgi?id=136937
https://bugs.webkit.org/show_bug.cgi?id=136888

Hopefully Apple will fix them in the next Safari / iOS.

I'm not interested in adding a polyfill, sorry (too many potential bugs that I don't want to waste time on).
