### ISSUE TITLE
Search field when ‘selecting documentation’

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Thibaut/devdocs#196]
Typing in the search field (or, heh, typing at all :P) while in ‘Select documentation’ mode will exit that mode, and lose any changes made so far.

Probably best to disable the search field (and search-when-you-type functionality) when selecting sources, unless you want to modify it to search within the list of documentation sources' names.

**Comment by Thibaut** [comment]
A while ago I added the ability to search disabled docs in the main search (+ enable from the search results). b14fc9438a52ab1a7c317ba97645dbf1fe3f2c7d disables the search input while the picker is open, as suggested.
