### ISSUE TITLE
please add casperjs / phantomjs to devdocs

### ISSUE THREAD

**Issue by mschultheiss83** [Thibaut/devdocs#197]
Would love to see [this](http://docs.casperjs.org/en/latest/) on devdocs. 
Could also use [phantomjs](http://phantomjs.org/api/) if not in the pipeline

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/c/cmuaDXMs/62-casperjs
https://trello.com/c/gOLIq2Wl/178-phantomjs

**Comment by mschultheiss83** [comment]
sorry and thanks for the links
