### ISSUE TITLE
Store selected docs pref in something less volatile than a cookie?

### ISSUE THREAD

**Issue by fvsch** [Thibaut/devdocs#199]
Devdocs kept forgetting about my selected documentations and reverting to the default ones, even though it would still have the offline data around in IndexedDB. Turns out this preference is stored in a cookie, and I have set up my browser to agressively forget cookies (every time I close the browser).

Would it be possible to store the preferences in IndexedDB instead, perhaps only if user has enabled offline?

Using localStorage instead of a cookie would be a solution, but I suspect we should consider localStorage to be as volatile as cookies, since localStorage doesn't ask for user permission to store data.

**Comment by Thibaut** [comment]
This isn't possible, sorry. The server needs to know which docs you've selected in order to render the app cache manifest: http://devdocs.io/manifest.appcache
You could whitelist cookies on `devdocs.io` instead.
