### ISSUE TITLE
Offline web app

### ISSUE THREAD

**Issue by Thibaut** [Thibaut/devdocs#2]
DevDocs's offline setup isn't very good, requiring people to manually install, run, and update the code. Ideally we should cache everything in the browser using a storage API.

IndexedDB is supported by most browsers but I'm not sure it can reliably store tens of thousands of files amounting to hundreds of megabytes.

Chrome also supports the FileSystem API.

**Comment by Thibaut** [comment]
Offline mode has landed: http://devdocs.io/offline :)
(you may have to wait for app cache to update, and then reload the page)

IndexedDB FTW!

**Comment by bbodenmiller** [comment]
@Thibaut thanks for offline support!

**Comment by brutalcrozt** [comment]
thanks thi :)
