### ISSUE TITLE
Question about url scraper and paginated pages

### ISSUE THREAD

**Issue by sarhugo** [Thibaut/devdocs#202]
Hi, I'm trying to make the drupal documentation. One problem that I found is that at api.drupal.org there are several paged tables. For example at the starting point that I choose: https://api.drupal.org/api/drupal/groups
The pager links are not followed (since the uri is the same, only the query parameters change)
Is there a way to force fetching these links and merge the pages into one (with some manual preprocessing)? like https://api.drupal.org/api/drupal/groups and https://api.drupal.org/api/drupal/groups?object_name=&summary=&page=1 into groups
Let me know, other way I can create a local copy of the api.drupal.org website and modify the tables to show all the results (but it will need a real good howto to reproduce it)

Regards

**Comment by Thibaut** [comment]
Hi

Scraping the same path twice with different query params isn't supported, sorry. The location of the file and a bunch of other things are entirely based on the path, and it would be quite difficult to change that.

What you could do instead is manually add the URLs on page 2 to your scraper's `initial_paths`, like [here](https://github.com/Thibaut/devdocs/blob/0a09c8904e88692b13f877f8b797bf6f9a9105c2/lib/docs/scrapers/requirejs.rb#L8-L16). It's a bit harder to maintain (you have to manually hard-code the paths), but will achieve the same effect as visiting the page with the scraper.

Hope this helps. Closing this issue as it's not really an issue.
