### ISSUE TITLE
"jQuery > Ajax > jQuery.ajax()" does not document the "method" option

### ISSUE THREAD

**Issue by ooesili** [Thibaut/devdocs#204]
The aforementioned page does not document the `method` option that can be passed to `jQuery.ajax()`. This option is mentioned in the [official documentation](http://api.jquery.com/jQuery.ajax/).

**Comment by Thibaut** [comment]
I haven't updated the jQuery in a while because they're time-consuming to set up locally. Will probably wait for the next major release.
