### ISSUE TITLE
Unix man pages

### ISSUE THREAD

**Issue by zix99** [Thibaut/devdocs#206]
I'm not sure how you'd go about this, (Site scrape, or otherwise), but I'd love to be able to read (at least some subset) of the unix man pages.

Thanks for the great site!

**Comment by Thibaut** [comment]
The issue is with finding a good source that:

- is available in HTML format
- can be modified/redistributed commercially
- is categorized and/or doesn't have 100k+ entries

You can suggest ideas here: https://trello.com/c/Nx3q7KsQ/103-linux-man-pages
