### ISSUE TITLE
Don't intercept the Ctrl+F key combo

### ISSUE THREAD

**Issue by etanol** [Thibaut/devdocs#215]
Because sometimes subsections are not indexed in a particular documentation, it is necessary to use the _search in page_ browser feature.  This functionality is usually attached to the `Ctrl+F` key combination.  However, the web application captures all keyboard events.

Right now, the way to achieve that is, at least on Firefox, to double click in the page content (to force a focus shift) and then press `Ctrl+F`.  It could be nice if, at least, there would be a way to search text within a documentation page, instead of searching through the index; all without having to move the hand away from the keyboard.

**Comment by Thibaut** [comment]
Hey
DevDocs doesn't capture `Ctrl+F` (`Cmd+F` on OS X) for that very reason. Are you sure you don't have an extension or something that would capture the key event? Can you replicate in Chrome and IE?

**Comment by etanol** [comment]
You are correct.  It was an issue of my GUI toolkit configuration.

Sorry for the noise, closing.

**Comment by Thibaut** [comment]
No problem!
