### ISSUE TITLE
Can't scroll using up/down arrows

### ISSUE THREAD

**Issue by rudiedirkx** [Thibaut/devdocs#218]
Even after blurring the search box, I can't scroll using the up/down arrow keys. Usually focus starts on the body and I have to hit some shortcut (like `/`) to focus the search/nav. Like this I can't even unfocus to do the native up/down thing.

I'm sure the up/down functionality is by design, but I consider the breaking of the scrolling a bug.

**Comment by Thibaut** [comment]
You can use `alt+up/down` and `space/shift+space` to scroll (press `?` to see all shortcuts). DevDocs would become hard to use IMO if you had to constantly switch back & forth between focusing & blurring the search field to activate different keyboard shortcuts.

Search is the app's primary function; I don't want people to have to think twice (is the search field focused or not) before typing or hitting the arrow keys. To make things predictable, `up` & `down` always navigate the sidebar.

I might add a user setting to swap the behavior of `up/down` and `alt+up/down`, but I don't consider this a bug, sorry.

**Comment by rudiedirkx** [comment]
Space for scrolling is so weird. Especially since the search box is focused.

ALT + UP/DOWN is good to know. Thanks.

**Comment by silverwind** [comment]
> I might add a user setting to swap the behavior of up/down and alt+up/down, but I don't consider this a bug, sorry.

I'm also an arrow scroller sometimes and it surprised me that up/down didn't scroll the document but the sidebar. Imho, up/down should scroll the document by default, I rarely if ever need to scroll the sidebar.
