### ISSUE TITLE
User experience issue with using space and alt key combinations.

### ISSUE THREAD

**Issue by niksrc** [Thibaut/devdocs#222]
Using ````space```` and ````space + shift```` combination is too cumbersome.Even if i use ````alt + up/down````, distance between the keys is large , affecting the user experience.

If we use either ````ctrl+up/down```` or ````shift+up/down```` , there would be a significant increase in productivity and faster navigation.

**Comment by ofalvai** [comment]
I'm wondering why the sidebar scrolls by default. Most of the time I want to scroll the main area, not the sidebar.

**Comment by Thibaut** [comment]
@ofalvai It's the opposite for me. Most of the time I want to quickly navigate the sidebar / search results. I then use `space / shift + space` to scroll.

@niksrc I'll make `shift + up/down` scroll like `alt + up/down` tomorrow.
