### ISSUE TITLE
Rust Documentation Outdated: Update to v1.1.0

### ISSUE THREAD

**Issue by orkhayiq** [Thibaut/devdocs#225]
The [Rust documentation featured on the site](https://devdocs.io/rust/) is currently v.1.0.0. Rust releases a stable version every 6 weeks. The newly released v1.1.0 became stable [yesterday](http://blog.rust-lang.org/2015/06/25/Rust-1.1.html).

**Comment by Thibaut** [comment]
I'm currently on vacation. Will do a batch of updates in a week.
