### ISSUE TITLE
doc filtering not working

### ISSUE THREAD

**Issue by newtmitch** [Thibaut/devdocs#226]
I'm wondering if it's just me, but I saw this in Chrome the other day, but not in FF, now in both. When I want to filter on a specific doc set, say lodash, I'll type it's name and then hit tab or command-enter to bring it into a new window. The rest of the docs melt away and stay out of my way until I hit escape twice. I noticed this stopped working in Chrome first, now FF. Now it actually takes me to the head of that doc set, but searching still does a global search across all docs I'm subscribed to, making the "filtering" pretty useless. When I saw this the first time I tried clearing cache, trying an Incognito window in Chrome, all to no avail...

What is interesting is that if I filter on a doc set name that I don't have enabled, it'll filter exactly how I'd expect it to. But anything in my enabled doc list doesn't filter the same...

Slight update - the tab functionality appears to work although visually it still shows the rest of the docs after you hit tab but before you start actually typing in order to search. The command-enter functionality, however, looks the same as the tab, but searching isn't limited to the doc set that you "enter-tabbed" into... weird.

**Comment by kikyous** [comment]
> Searching a single documentation
You can scope the search to a single documentation by typing its name (or an abbreviation), and pressing Tab (Space on mobile devices). For example, to search the JavaScript documentation, enter javascript or js, then Tab.
To clear the current scope, empty the search field and hit Backspace.

**Comment by newtmitch** [comment]
Understood. I'm saying that's not working properly.

**Comment by Thibaut** [comment]
Hey!

Sorry for the late reply.

This was a side-effect of fixing #209. When pinning the tab and restarting the browser, DevDocs used to launch in "single doc" mode unless the last URL was the root URL. Me and others found it annoying to have to press `Esc` twice to go back to "all docs" mode, so I made it so the app always boots in that mode for docs that have been enabled.

Tomorrow I will make it so the search scope is automatically set when the app is launched from a doc URL, which should resolve this issue (command+enter will then focus a doc until you press `Esc`).
