### ISSUE TITLE
Search within specific language

### ISSUE THREAD

**Issue by tsia** [Thibaut/devdocs#231]
Hi,

i work as Software developer and System Administrator. So i have many (around 30) Languages enabled in DevDocs.

Does it make sense to implement some way of limiting the search to only one lanuage?

**Comment by BenoitZugmeyer** [comment]
Try typing the first letters of the language (ex: pyt) then hit tab.

**Comment by tsia** [comment]
😱 Why didn't i know this?! THIS IS AWESOME!
