### ISSUE TITLE
Offline mode for Safari

### ISSUE THREAD

**Issue by tsia** [Thibaut/devdocs#232]
Have you considered using something like [this IndexedDB Polyfill](http://nparashuram.com/IndexedDBShim/) using WebSQL to support Offline mode in Safari (and Fluid)?

**Comment by Thibaut** [comment]
I have, but would rather wait for Apple to get their s*** together than trying to work around this myself. That polyfill is good but incomplete. I don't want to waste time debugging issues related to it, sorry. IMO there are more important things to work on.

**Comment by tsia** [comment]
testing https://gist.github.com/demonbane/1065791 for creating Chrome-Based Fluid-Like Apps.

**Comment by ahmadseleem** [comment]
No need for this Gist:
you can just a ready to use:

https://marketplace.firefox.com/app/devdocs/

**Comment by bassu** [comment]
I have to agree with @Thibaut. Safari's market share isn't that interesting for Apple to push quick bug fixes while DevDocs, which I assume is a hobby project, has much more tighter priorities than Apple's slack !
