### ISSUE TITLE
light Style suggestion

### ISSUE THREAD

**Issue by morenoh149** [Thibaut/devdocs#236]
When browsing the Cordova documentation. I think it would be better if section name background colors were flipped.
![screenshot 2015-07-25 22 37 52](https://cloud.githubusercontent.com/assets/587438/8892702/fe1c0788-331d-11e5-808c-91721a678253.png)

So `pause` has a lightblue background.

**Comment by Thibaut** [comment]
Thanks for the suggestion. I'll fix this soon. If there are other docs that you think could be improved feel free to let me know.

**Comment by morenoh149** [comment]
since you mentioned it, the dark theme would look better inverted as well. Here's a modified screencap
![screenshot 2015-08-05 09 17 07](https://cloud.githubusercontent.com/assets/587438/9091056/d5702fca-3b52-11e5-929d-bfb90659c89a.png)
vs
![screenshot 2015-08-05 09 18 32](https://cloud.githubusercontent.com/assets/587438/9091074/f9097608-3b52-11e5-8b4c-6985dbbcc6b6.png)

**Comment by Thibaut** [comment]
Fixed up that one page. I think the others are OK.
