### ISSUE TITLE
Mongoose missing documentation

### ISSUE THREAD

**Issue by JaKXz** [Thibaut/devdocs#237]
Hi - huge fan of DevDocs here - but it seems the Mongoose docs are not being completely scraped. I would just make a PR to update the version, but I'm not sure if that covers the actual issue here.

[The `Query#then` method](http://mongoosejs.com/docs/api.html#query_Query-then) is the method in question for this issue, which has been around since v4.0.x according to a maintainer, so there might also be other methods missing... [possibly across other languages/frameworks as well?]

**Comment by Thibaut** [comment]
The documentation for that method was added in 4.0.6. DevDocs is still on 4.0.5. I'll update the doc soon.

**Comment by JaKXz** [comment]
Ah - my bad, and thanks!

**Comment by Thibaut** [comment]
Thanks for the heads up!
