### ISSUE TITLE
Haskell-Functions within classes are not found

### ISSUE THREAD

**Issue by Drezil** [Thibaut/devdocs#239]
examples of common functions not found include `>>=`, `mappend`, `compare` etc.

There should be a way to generate a better documentation with hoogle (to index everything) and stack/cabal.

**Comment by Thibaut** [comment]
Fixed by e096acc5c7b0bdf89da2b788098a70e44f2929b5 (reload the app to get the new version).
Let me know if you have suggestions for improving that doc. I've never used Haskell and the original docs are a bit of a mess.
