### ISSUE TITLE
Jade documentation

### ISSUE THREAD

**Issue by dogancelik** [Thibaut/devdocs#243]
Hi I couldn't find Jade in the docs, could you please add it?
Jade is a very popular markup language like Haml

https://github.com/jadejs/jade
http://jade-lang.com/

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation
