### ISSUE TITLE
doc files in the repo?

### ISSUE THREAD

**Issue by dcsan** [Thibaut/devdocs#247]
are the actual doc files that the scraper pulls down available anywhere? I can't see them in the assets dir...

**Comment by Thibaut** [comment]
You can download all the files using `thor docs:download --all`. They will appear in the `public/docs` folder — all 30,000 / 435MB of them.

**Comment by Thibaut** [comment]
Note: as indicated in the README, please attribute these files to DevDocs if you reuse them elsewhere.
