### ISSUE TITLE
HTML attributes missing connotations which MDN renders as icons

### ISSUE THREAD

**Issue by ryanvfung** [Thibaut/devdocs#248]
When comparing the [devdocs](http://devdocs.io/html/element/td) and [Mozilla Developer Network (MDN)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td) pages for the HTML `td` element, various attributes have additional connotations which are not present in devdocs.
Three example attributes, `align`, `axis` and `bgcolor` are listed below, with MDN icons replaced by connotations in brackets:

| Attribute | Attribute and Connotation in MDN | Rendered content in devdocs |
|---|---|---|
| `align` | `align` (deprecated) in HTML 4.01, (obsolete) in HTML5 | `align` in HTML 4.01, in HTML5
| `axis` | `axis` (obsolete) in HTML5 | `axis` in HTML5
| `bgcolor` | `bgcolor`(non-standard) | `bgcolor` |

While there are additional notes beneath the description for the attributes regarding the usage of the relevant attribute, it would be useful to have this information displayed next to the attribute name itself.

These connotations are currently rendered on MDN in the following form, with an icon font generating the visible icon images:
```html
<span title="">
    <i class="icon-placeholder">
</span>
```

**Comment by Thibaut** [comment]
Thanks for the bug report. I'll get this fixed the next time I update the MDN docsets.
