### ISSUE TITLE
Support multiple versions of a piece of software

### ISSUE THREAD

**Issue by akahn** [Thibaut/devdocs#25]
I found out about this project from the Postgres Weekly newsletter. The devdocs for postgres (http://devdocs.io/postgresql/) will be very useful to me. One thing that's lacking from the official postgres documentation, though, is the ability to choose a specific version of Postgres. In my case, I'd like to read the documentation for Postgres 9.2 since I'm not running 9.3 yet.

**Comment by altaurog** [comment]
+1 on multi-version support.  Python isn't such an unusual case, IMO.  Django and Angular have backwards-incompatible changes between versions.  I imagine many other of the documented platforms do as well.  Whenever upgrading to a new version is non-trivial, there are bound to be many dev groups using older versions.  Similarly, some devs are bound by various policies to stable environments with older versions like debian or ubuntu LTS.

This is one of the things I appreciate greatly about readthedocs.

**Comment by Thibaut** [comment]
I might give this a shot in the coming months.

**Comment by sarathprasath** [comment]
+1 for multi-version support(especially on Rails & Ruby)

**Comment by fskirschbaum** [comment]
Another *+1* on multiple version support even if not concurrent, picking the version you want to have "installed" would be super handy!

**Comment by ryanmark** [comment]
I keep revisiting this project hoping to find that you've added multiple version support. There are many of us who would love to use this project but simply can't because we would require this feature. +1

**Comment by Thibaut** [comment]
@ryanmark Thanks for the feedback. As I said, I wish I had time to do everything, but this is a major undertaking which I have to balance with other things, including my personal life. I maintain and develop DevDocs exclusively on my spare time. What would be worse for everybody is for me to burn out.

**Comment by omouse** [comment]
Sorry for bugging you about this!

Is there a nice way for *others* (i.e. not you!!) to work on this and to submit pull requests for particular libraries? Is there a template that can be used for others to build on, such as the way you're handling python 3 vs 2 and yii 1 vs 2?

I notice that @nfm mentioned he had made an attempt to make it work; not sure if he submitted a pull request for that.

[There's a BountySource open for this, if anyone *really* wanted this feature they should contribute code or dollars to support its development.](https://www.bountysource.com/issues/5442208-support-multiple-versions-of-a-piece-of-software) Maybe including a link and a warning about this issue in the README or on the devdocs site might stop so many people from commenting on it and requesting it and reduce the feeling of stress/burn out.

**Comment by nfm** [comment]
@omouse I never ended up opening a PR for this, but I've just had a super quick look now and it seems like it would be pretty straightforward, especially now that there are examples for how to do this in the repo (eg. Python 2 and 3).

I think the process would be the same as adding a whole new language - you'd submit a PR like #281 for the alternate major version of the software you wanted to add. You could probably reuse much of the existing Filter and Scraper, unless the documentation format or location changed between major versions.

**Comment by Thibaut** [comment]
@omouse thanks for offering to help. As @nfm said, major versions of prominent languages/frameworks can be submitted as separate scrapers. More finer grained versioning will require changes to the scraping framework and UI. At the moment I'm still too busy to tackle this, but it is at the top of my list for when I have more free time on my hands (along with the Bootstrap doc).

PS: it's 100% OK for people to comment/+1 here. It helps me prioritize which features to work on next.

**Comment by rejetto** [comment]
+1
thanks :)

**Comment by Unibozu** [comment]
+1

**Comment by lancelafontaine** [comment]
+1. Although DevDocs is amazingly functional, this is the feature that is making me hold off from using DevDocs all the time. I simply can't trust that the documentation is correct and refers to the version I am working with.

**Comment by Thibaut** [comment]
_[#SOON](https://twitter.com/DevDocs/status/689074357444853760)_

**Comment by Thibaut** [comment]
Enjoy :)

**Comment by omouse** [comment]
@Thibaut deserves many :beers: beers and :cake: cake. Seriously, amazing! I'm really happy, now there's even more examples for others to work with to see how to implement multi-version for their favourite APIs :-D

**Comment by nfm** [comment]
@Thibaut  :heart: This is awesome!

**Comment by Kaijiro** [comment]
Well done buddy !

**Comment by fskirschbaum** [comment]
This is welcome and excellent news! Well done!
