### ISSUE TITLE
Clojure documentation doesn't load

### ISSUE THREAD

**Issue by rgb-one** [Thibaut/devdocs#250]
As the title says: http://devdocs.io/clojure/

**Comment by Thibaut** [comment]
Could you post a screenshot? (+ also one of the network tab in the dev tools) It works for me.

**Comment by rgb-one** [comment]
It seems I may mistaken. I was expecting to see documentation on the front page and didn't take note of the content in the sidebar.

**Screenshot**
Clojure page:
![clojure-devdocs-frontpage](https://cloud.githubusercontent.com/assets/5672238/9399431/cb4d6408-4779-11e5-81ad-1f73df403c10.png)

Developer tools Network Info:
![clojure-devdocs-dev-tools-network](https://cloud.githubusercontent.com/assets/5672238/9399462/3dc9ef06-477a-11e5-80d8-395968ede236.png)

**Comment by Thibaut** [comment]
This is intended. Some docs have a blank index page due to how the original doc is formatted. The best way to navigate content is always the sidebar and search.
