### ISSUE TITLE
Output to epub / pdf / other formats

### ISSUE THREAD

**Issue by janesconference** [Thibaut/devdocs#252]
It would be nice to have a way to export the (enabled) documentation into epub or pdf etc., to allow easy offline consultation on ebook readers.

**Comment by Thibaut** [comment]
Thanks for the suggestion. This isn't something I see myself having time to develop in the foreseeable future, sorry. You're welcome to give this a try and open a PR, or make it a separate repository, which I'd be happy to link to.

**Comment by jmerle** [comment]
I'll give this a try this weekend.

**Comment by jmerle** [comment]
While it is possible, I decided not to go on with it. While it is possible to generate both PDF and epub files using Ruby, you'd need to take care of page ordering, PDF/epub specific styling and testing it to make sure it works on all docs (with edge cases like external images and iframes). To me the time I'd have to put into it is not worth it considering the very, very specific target audience.
