### ISSUE TITLE
Better support for keyboard controls

### ISSUE THREAD

**Issue by Pastafarianist** [Thibaut/devdocs#254]
Right now the search field grabs focus whenever it wants to. Furthermore, it catches `ctrl+f`. Therefore, if I'm opening some docs and start looking for a specific string, I have to grab the mouse to click on the text to transfer the focus. Then I can use `page up / page down`, arrows and `ctrl+f`.

I would probably be better to allow `page up / page down` to control the scrolling at all times, at least. Also, maybe assign some other shortcut to jump to the search bar, not `ctrl+f`.

**Comment by Thibaut** [comment]
Why OS / browser are you using?
`ctrl+f` doesn't get captured in my browser, and `page up / page down` is always allowed.

**Comment by Pastafarianist** [comment]
I'm on Linux, Chrome 44.0.2403.157.

**Comment by Thibaut** [comment]
What did you expect to happen when you pressed `ctrl+f`? It should have opened Chrome's own search field, not DevDocs's. If you want to focus the search field in DevDocs, just start typing or press backspace. What does `ctrl+f` do on other websites?

**Comment by Pastafarianist** [comment]
I expected the Chrome search box to appear. It didn't. Nothing happened at all and the focus remained in devdocs's search field.

**Comment by Thibaut** [comment]
Can you try disabling all Chrome extensions, and changing the `type` attribute of the search input from `"search"` to `"text"` using the dev tools.

**Comment by Pastafarianist** [comment]
You are right, disabling cVim restores the `ctrl+f` functionality. I've created an [issue](https://github.com/1995eaton/chromium-vim/issues/361) in their bugtracker.
