### ISSUE TITLE
C++ multimap has wrong example

### ISSUE THREAD

**Issue by RasmusWL** [Thibaut/devdocs#255]
[The DevDocs C++ page for multimap](http://devdocs.io/cpp/container/multimap/multimap) has a wrong exmaple.

The [source page](http://en.cppreference.com/w/cpp/container/multimap/multimap) has _no_ example. The example included in the DevDocs is from the [map source page](http://en.cppreference.com/w/cpp/container/map/map).

---

A possibility is to _also_ go through the documentation on www.cplusplus.com, as this page has a  [multimap example](http://www.cplusplus.com/reference/map/multimap/multimap/).

**Comment by Thibaut** [comment]
> A possibility is to also go through the documentation on www.cplusplus.com, as this page has a multimap example.

Unfortunately these docs are proprietary ("© cplusplus.com, 2000-2015 - All rights reserved"), so I can't use them on DevDocs :/
