### ISSUE TITLE
Firefox search from address bar doesn't work

### ISSUE THREAD

**Issue by OrangeDog** [Thibaut/devdocs#256]
I think it's because devdocs uses `#` for query parameters instead of `?`.
I've not had any trouble adding FF search shortcuts for other services.
Using Firefox 40.0.3

**Comment by Thibaut** [comment]
It works for me. What shortcut did you add? Did you do it manually?

**Comment by OrangeDog** [comment]
Oh, I checked again and now it works. I must be going mad...
