### ISSUE TITLE
Firefox WebApp doesn't save the "Toggle light" preference

### ISSUE THREAD

**Issue by camolin3** [Thibaut/devdocs#259]
When pressing the "Toogle light" button, it works. Closing the webapp and opening again always show the ligth theme. The expected behaviour is to keep the last color selected (black, in my case).

This happens in Ubuntu 15.04 x64. I'm using Firefox 42.0a2.
BTW, it works just as expected in the browser, the problem is with the webapp.

I reset the webapp from the "offline" Q&A tab, but it is still failing to remember the black theme.

**Comment by camolin3** [comment]
From time to time, it starts with the black theme. But I can't reproduce it.

**Comment by Thibaut** [comment]
Same. I tried to reproduce. Sometimes it works, sometimes it doesn't. Very weird…

I haven't had much time to work on DevDocs recently but will try to take another look at this in the coming weeks.

**Comment by Calinou** [comment]
Also happens in Firefox for Android (on Android 5.0).

**Comment by mdhooge** [comment]
Do you have a filter on cookies?
I had the same problem until I authorized the http domain, even though I connect through httpS.

**Comment by Thibaut** [comment]
Closing as Mozilla is removing the web app runtime from Firefox: https://wiki.mozilla.org/Marketplace/FutureofMarketplaceFAQ
