### ISSUE TITLE
Python2 docs are missing some content

### ISSUE THREAD

**Issue by kandrilenas** [Thibaut/devdocs#262]
Hello, 

The Python2 (and Python) docs are missing some of the Standard Library documentation.
"Python Language Services" and a number of other sections just provide an "Oops, that page doesn't exist." error. These sections are listed in the table of contents.

This is similar to closed issue #137

Not sure if there is anything I can do to help fix this (let me know if there is). Thank you!

**Comment by Thibaut** [comment]
Thanks for the bug report!

**Comment by kandrilenas** [comment]
Of course! I'm super new to Github so I'm not sure what I'm doing.

Thank you.
