### ISSUE TITLE
Some C/C++ links on header file listing page do not work

### ISSUE THREAD

**Issue by wolf99** [Thibaut/devdocs#269]
As per gif tweet: https://twitter.com/TobyMole/status/644110791558434817

On the devdocs.io website, clicking on the links for header file documentation in C or C++ results in a page not found error

Header files for which this happens for C:
assert.h, errno.h, locale.h, setjmp.h, signal.h, stdalign.h, stdarg.h, stdatomic.h, stddef.h, stdio.h, stdlib.h, stdnoreturn.h, threads.h and time.h.

For C++ it was noted with algorithm.h and iterator.h links, but other links were not tested

This is in Chrome 45.0.2454.93 m (current version) on windows 7 64-bit.

**Comment by cdvillard** [comment]
I'm having similar issues all on other parts of the site as well including HTTP, JavaScript, and CSS. Something isn't linking properly.

**Comment by Thibaut** [comment]
@cdvillard Your issue is different. Sounds related to https://github.com/Thibaut/devdocs/issues/264.
