### ISSUE TITLE
Request: perl documentation

### ISSUE THREAD

**Issue by OrangeDog** [Thibaut/devdocs#271]
Filing an issue as I'm guessing there are people who could implement it a lot faster than I.
Can devdocs include content from perldoc.perl.org?
I'd guess by either scraping the site, or parsing the pods directly.

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/c/GlLxFIaB/20-perl

**Comment by OrangeDog** [comment]
Whoops.
