### ISSUE TITLE
[Feature] Android/WindowsPhone/IOS Native App Integration

### ISSUE THREAD

**Issue by Toltar** [Thibaut/devdocs#274]
I was quite excited finding this repository and it even includes a JSON API as concluded here: https://github.com/Thibaut/devdocs/issues/133 

Now that this project has a JSON-API; I suggest we use it to not only integrate into IDE's but possibly into a Mobile App where you can use a phone and/or tablet (which this on tablets would be awesome to use this with) would be very useful to have. I see that you have a mobile version which you can download offline docs and it is wonderfully made and designed as stated in the goals of the repository: "...maintain a clean and readable user interface; be fully functional offline; support full keyboard navigation;". Though I want to take these goals a step further by introducing the idea for a mobile app. I think introducing a native mobile app in will take what all the contributors have achieved in meeting the goals and take it a step further by "...maintain[ing] a clean and readable user interface..." by adhering to the design standards of the apps ecosystem, "...be fully functional offline..." by ushering the app into a native ecosystem to their respective platform, "support full keyboard navigation" by coming up with ways to make a efficient UX by not just a keyboard but a touch interface.

Of coarse I would love for one defined user interface though there are standards to those interfaces which the users of mobile devices are accustomed to. Developers of cross platform apps sometimes tend to try to create a different UX and UI experience based on the platform they are developing for. The reason for this is because even though there is a lot more effort(and money) into redesigning an app for each platform. Even though the statement is vague that the project's goals are to "...maintain a clean and readable user interface..." and "...support full keyboard support..." I would think of asking myself what defines a clean user interface?. Also, why is it not stated to provide "...support for fully touch interfaces..."? It means different things to different people of a clean interface because one could say Google's "Material Design Standards" are clean when in an iPhone in the users eyes would maybe say "iPhone's Design Standards" for apps provide a cleaner user interface. One could argue that we don't want to create a complexity through making an interface for each platform and we must keep consistency for the sake for the project. Though in another light, we are only making small tweaks. As far as I know both Android and IOS have the commonly used "sliding sidebar" and their are quite a good amount of similarities in terms of design and user interface that can be implemented in both apps. But it would probably be a good idea to implement them in the ecosystem that the users are used to in which gives a highly available experience. Please discuss this and even argue on my points, I would like to see another perspective other than mine. 

Speaking of a highly available experience, another goal of the project is to "...be fully functional offline...". And their is no better way to do that than ushering a native experience for the project. The project indeed has downloadable offline docs and caching. Though bringing a native experience is far more accessible than caching. Caching requires the user to access the website and yes so does downloading the app needs the internet to download from the apps native app store. Though I want to leave that open for discussion since both benefits seem to equal each other.

So I believe their is potential for devdocs.io to move into the mobile app sphere. Even though I think its important rather to support more languages, frameworks, and libraries into the project; it still is an extra thing we can keep in mind as we continue to move forward with it. I have worked with Android Development myself and feel this would be something I would want on my Samsung Note 10.1 2014 edition tablet to use for quick reference with one less browser window open on my desktop. I would also like to hear what others think they can use this for. Please feel free to correct me on anything I said regarding any technical and grammatical related matters(I'm not perfect and we all make mistakes). I would love to work on something like this since I am a Junior in college and need more projects under my belt as well. Thanks for reading! I look forward to discussing with you all upon these matters.

(If I violated the CONTRIBUTION guidelines please let me know. I did read the Feature Request section before posting this but again I may have misunderstood the context of it.)

**Comment by Thibaut** [comment]
Thanks for the write-up.

DevDocs doesn't have an API yet. It only makes certain files (used by the web app for the search) publicly available. You're free to use those to make your own app.

I have no interest in making a native app, sorry. I don't have the time (DevDocs is just a side project of mine), nor feel that this is in the spirit of the project (even though I can see the use case). The web app has a mobile-optimized version; you can add a shortcut to it on your homescreen and get most of the functionality that a native app would provide (PRs that improve the UI are welcome).

I have no objections to anyone making a native version of DevDocs, though, so long as you credit DevDocs for the data and use a different name (see the [copyright section of the README](https://github.com/Thibaut/devdocs#copyright--license)). On the contrary, I'd be happy to promote it on devdocs.io if it's well made.
