### ISSUE TITLE
Alfred WorkFlow

### ISSUE THREAD

**Issue by jeffscottward** [Thibaut/devdocs#275]
Requesting a plugin to search for absolutely anywhere via an Alfred Workflow.
Should be very straightforward to map to the search.

**Comment by jeffscottward** [comment]
https://github.com/jeffscottward/DevDocsIO-AlfredWorkflow

**Comment by Thibaut** [comment]
Thanks. I added a link to it on the wiki:
https://github.com/Thibaut/devdocs/wiki

FYI there's also this:
https://github.com/yannickglt/alfred-devdocs
