### ISSUE TITLE
Google Chrome doc tooltip directly on websites @feature

### ISSUE THREAD

**Issue by krzemian** [Thibaut/devdocs#278]
Proposed workflow

1. Enter [a website](http://ricardo.cc/2013/06/07/react-tutorial-rewritten-in-plain-javascript.html)
2. The extension automatically identifies code snippets and the language they're written in
3. Hover mouse over a function name/module/class etc. to get a short description  
 Like (the scope of the info is to be discussed) "_Returns the first element within the document (using depth-first pre-order traversal of the document's nodes|by first element in document markup and iterating through sequential nodes by order of amount of child nodes) that matches the specified group of selectors._" for `document.QuerySelector`
4. Click to get to [full doc on devdocs.io](http://devdocs.io/dom/document/queryselector)

Benefits

* It complies with the cornerstone of DevDoc's vision: _DevDocs aims to make reading and searching reference documentation fast, easy and enjoyable._
* Could make it faster to understand code, especially when at the early stages of learning a given subject.
    * Would replace the current workflow: ctrl+l -> d -> tab -> [type in query string] -> enter

At the same time I'm not sure if it falls in the "non-full-text search enginge" category.

What do you think?

**Comment by Thibaut** [comment]
Thanks for the detailed suggestion!

Such an extension would be nice but isn't something I'd add to this repo or want to work on myself, sorry. I have no experience with browser extensions, one big app to maintain already, and many features to implement.

If you want to make it yourself I'd be happy to add a link to it in DevDocs, though.
