### ISSUE TITLE
Chef docs

### ISSUE THREAD

**Issue by doertedev** [Thibaut/devdocs#279]
Oy. The docs state that opening an issue beforehand would be wise so...

I'm right now trying to pull the [chef resource documentation](https://docs.chef.io) together.
Only a small part of chef is in commercial use, and the docs are under Creative Commons Attribution 3.0 Unported License. I also have chef marketing ppl in my twitter feed and asked if they've got a problem. I'll port their response in the SOURCE file if so.

On it.

**Comment by doertedev** [comment]
Notice though: Only added the resources, because adding all the other sorts of documentation in the scope of devdocs rarely makes sense. This leads to me being confused if whether listing the entire resource page on the main root for "chef" make sense...
[trello right now gives +71 for chef](https://trello.com/c/IMwU9aOQ/144-chef).

Feedback pls.

**Comment by Thibaut** [comment]
Thanks. Opening an issue is useful to let everyone know that you're working on it. Since you opened a PR already, we can close this.
