### ISSUE TITLE
filter search

### ISSUE THREAD

**Issue by marcelino-m** [Thibaut/devdocs#288]
is possible narrowed the search  docs like [zeal](https://zealdocs.org/)?
Example : c,python:print
This limit  search  to C and Python docs only

**Comment by Thibaut** [comment]
You can do it for one doc: http://devdocs.io/#q=css%20color
More info here: http://devdocs.io/help

I don't really see the need to support multiple docs since it'd be cumbersome to type them all out.

**Comment by SolaWing** [comment]
@Thibaut though multiple docs indeed be cumbersome to type them all out, it is still very useful to focus on the subset of user's current program environment.

for example:
web developer may need to search in `html, dom, javascript, css` etc...
python developer may need to search in `python, pandas, numpy` and other third party libs..

now devdocs only support all or single docs, thus user have to choose either to search in all and endure unwanted noise, or to switch the current document frequently.

The inconvenience of input can be solved by setting in advance. like dash you can define custom prefix as a set of docs. or when integrating with other editor, editor can generate the full url and don't need user to type it out

**Comment by jmerle** [comment]
>though multiple docs indeed be cumbersome to type them all out, it is still very useful to focus on the subset of user's current program environment.

I think #582 is a better solution for that, although they are both a lot of work.
