### ISSUE TITLE
some empty tag are necessary

### ISSUE THREAD

**Issue by kikyous** [Thibaut/devdocs#289]
for example
http://laravel.com/docs/5.1/contracts#introduction

```html
<p><a name="introduction"></a></p>
```
emtyp a tag with a name attr is used for anchors, but default `CleanTextFilter` remove it.

**Comment by Thibaut** [comment]
What links is this breaking?
The solution is to move the anchor tags to `id` attributes on the heading. I'll do that next time I update Laravel.

**Comment by kikyous** [comment]
http://devdocs.io/laravel/docs/5.1/authentication

Links in TOC is  broken.

> The solution is to move the anchor tags to id attributes on the heading.

yes, but we need tag like `<p><a name="introduction"></a></p>`  before every `h2`  to get id attribute which is removed by `CleanTextFilter`

**Comment by Thibaut** [comment]
`CleanTextFilter` runs last. We can do the `<p><a name="introduction"></a></p><h2>…</h2>` → `<h2 id="introduction">…</h2>` transformation before it (in https://github.com/Thibaut/devdocs/blob/master/lib/docs/filters/laravel/clean_html.rb).
