### ISSUE TITLE
Suggestion: Add a way to swap Up/Down arrow keys with ALT+Up/Down

### ISSUE THREAD

**Issue by povrazor** [Thibaut/devdocs#296]
I'm loving devdocs.io, but most documentation browsing outside devdocs works with the arrow keys.

I completely understand why the arrow keys are bound the way they are, but I find I naturally want to scroll the page using just the UP/DOWN arrow keys, not ALT+UP/DOWN. I realize SPACE and the Page UP/DOWN keys work as expected, but not everybody reads whole pages at a time (I'm an incher, inching my pages slowly as I go ;) ).

If possible, I would love to have a way I could swap the effect of UP/DOWN with ALT+UP/DOWN.

Thanks for the great site. :D

**Comment by jaikamat** [comment]
@Thibaut @povrazor would you mind if I try to tackle this? 😄

**Comment by Thibaut** [comment]
@jaikamat not at all 👍

**Comment by jaikamat** [comment]
@Thibaut Thanks a ton! Will work on it once the workweek is over and submit a PR

**Comment by cesarizu** [comment]
Hello, has there been any progress on this issue? Thanks a lot!

**Comment by Thibaut** [comment]
http://devdocs.io/settings :)

**Comment by jmerle** [comment]
This issue was never about custom keyboard shortcuts, it's about the "Use arrow keys to scroll the main content area" option.
