### ISSUE TITLE
Issues in loading documents/pages

### ISSUE THREAD

**Issue by satyendrachaudhary** [Thibaut/devdocs#297]
I was not able to open any single document. Whenever I click on something, I got this error on javascript console(Chrome Version:46.0.2490.80)

***XMLHttpRequest cannot load http://docs.devdocs.io/python/index.html?1444661855. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://devdocs.io' is therefore not allowed access. The response had HTTP status code 400.***

And this on the page
***Oops, the page failed to load.***

Yes, I am on proxy network, but i thought if I am able to open the web application, content should also be loaded with it.

**Comment by Thibaut** [comment]
See https://github.com/Thibaut/devdocs/issues/264#issuecomment-139914142
Unfortunately there's nothing that can be done on DevDocs's end to work around this issue. The docs live on a separate origin. If your proxy is blocking those requests then the app cannot function.
