### ISSUE TITLE
Classify API documentations and new documentations

### ISSUE THREAD

**Issue by Nosthertus** [Thibaut/devdocs#299]
The search in the list of documentations would be much easier and friendlier if the documentations were branched in languages, example `node.js` and `jQuery` would be inside of `Javascript` language, if not, maybe this would be an option the user could enable.

Also, this program has become one of the most used applications for my work, and i really would like it more if it has documentation for `diet.js` and `sequelizejs` which both are used in `node.js`

**Comment by Thibaut** [comment]
Thanks for the suggestion. This feature is already being tracked [here](https://github.com/Thibaut/devdocs/issues/4) (feel free to +1 there). 

For new docs, see https://trello.com/b/6BmTulfx/devdocs-documentation and https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs
