### ISSUE TITLE
Wrong text direction.

### ISSUE THREAD

**Issue by reverland** [Thibaut/devdocs#300]
http://devdocs.io/dom/element/classlist

![screenshot from 2015-11-25 21 39 16](https://cloud.githubusercontent.com/assets/1418726/11398615/081614f4-93bd-11e5-95ac-c525262fa222.png)

Its ok in MDN but  `dir="rtl"` too.

https://developer.mozilla.org/en-US/docs/Web/API/element/classList

![screenshot from 2015-11-25 21 42 48](https://cloud.githubusercontent.com/assets/1418726/11398721/a0961396-93bd-11e5-83f3-202fdedfbafb.png)

**Comment by Thibaut** [comment]
Thanks for reporting the bug!
