### ISSUE TITLE
Enabled Documentation Shown Multiple Time

### ISSUE THREAD

**Issue by bekicot** [Thibaut/devdocs#301]
I clicked enable button twice as i dont see it moved to the top instantly. When i opened offline and tried to install the documentation, it shown coffescript twice.

Maybe the picture will explain a lot more. 
![devdocs offline](https://cloud.githubusercontent.com/assets/1826884/11422153/4fd9a350-946c-11e5-97f2-ef577944ddaf.png)

**Comment by Thibaut** [comment]
Thanks for the bug report! I've just fixed it. If you still see duplicate docs on the offline page, just reload the page and they'll go away.
