### ISSUE TITLE
Use existing zipped docs for elixir instead of scraping

### ISSUE THREAD

**Issue by ericmj** [Thibaut/devdocs#306]
Docs for elixir: https://github.com/elixir-lang/elixir/releases/download/v1.1.1/Docs.zip
Docs for hex packages: https://s3.amazonaws.com/s3.hex.pm/docs/phoenix-1.0.3.tar.gz

**Comment by Thibaut** [comment]
Hey
Are you asking because the scrapers are adding too much load on the Elixir and hexdocs.pm websites?

**Comment by ericmj** [comment]
No. But it should be easier to just fetch a tarball with all the docs you need instead of running a scraper.

**Comment by JesseTG** [comment]
And then they'll have to run the scraper on the downloaded archives!

**Comment by ericmj** [comment]
What information is it you pull out? I'm sure we can provide a better format than scraping websites. Your scraper will break every time ex_doc changes the formatting and you wont be able to scrape multiple versions of packages because they use different ex_doc versions.

**Comment by Thibaut** [comment]
@ericmj Thanks! DevDocs's scrapers are pretty reliable and easy to write at this point (been at it for >2 years), especially for docs that have good markup and structured URLs. The output format is a combination of stripped down HTML files (with all the links changed) and metadata (extracted from the markup). It'd actually be more work to write a custom parser. Supporting multiple versions of ex_doc isn't a problem; only small changes to the scrapers should be required to keep things working.

I'll look into using the zipped docs in the next update, but usually unless the doc is very big it's easier to scrape the website (nothing to download; just run the command).

Closing this as it's not really an issue.

**Comment by ericmj** [comment]
Sure, this issue was mostly to let you know the tarballs exist so you can use them if you want.

**Comment by Thibaut** [comment]
@ericmj thanks :+1:
