### ISSUE TITLE
Provide typescript declarations

### ISSUE THREAD

**Issue by daniell0gda** [Thibaut/devdocs#307]
Hello !
I would love to have up to date typescript declarations.
There are some at DefinitlyTyped but old :(

**Comment by Thibaut** [comment]
You can vote for Typescript [here](https://trello.com/c/2z4hwSwN/220-typescript) or take a stab at [adding it](https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs) yourself.
