### ISSUE TITLE
Contributing without testing

### ISSUE THREAD

**Issue by calebkleveter** [Thibaut/devdocs#311]
I want to contribute to DevDocs, but I can't test anything because I can't install Thor or run Rails because I don't have sudo privileges. How could I get around this?

**Comment by Thibaut** [comment]
Hey

AFAIK some Ruby version managers like RVM don't require sudo privileges. An alternative would be to run DevDocs on a remote server like Heroku.

Unfortunately I can't give you much information beyond this as I don't have that problem. If you still can't find a way, I'd suggest asking on StackOverflow.

**Comment by calebkleveter** [comment]
Thanks for the ideas. Sadly, I need sudo privileges to install gems with RVM and I also need to install bundler to use Heroku (requiring sudo privileges).

**Comment by calebkleveter** [comment]
I found a way to install gems without sudo *privileges*! 

```console
gem install --user-install <gem>
```

**Comment by calebkleveter** [comment]
I was referred to [Cloud 9](https://c9.io/) to solve the issue that I was having.
