### ISSUE TITLE
Support Objective C / Cocoa

### ISSUE THREAD

**Issue by lgarron** [Thibaut/devdocs#312]
I'm doing some Mac programming, and needed to look up a few things about views in Cocoa. It would be awesome if [`devdocs.io`](http://devdocs.io/) could include those.

The documentation licenses I can find don't look promising for this, but I haven't seen an issue about this yet, so I thought I'd file one.

**Comment by calebkleveter** [comment]
If you have suggestions, ask on the [Trello](https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here) board. But here is what it says about what you want:

>MySQL, ElasticSearch, MongoDB, anything by Apple (Objective-C, Cocoa…), Microsoft (.NET, MS SQL…) or Adobe (ActionScript, Flex…) are all released under restrictive licenses (no redistribution) incompatible with DevDocs — please do not suggest them.

I asked about Swift:

>@tibc , awhile ago I mentioned swift being open source. I found an Apple Blog post on it. https://developer.apple.com/swift/blog/?id=29

And here was the reply:

>@calebkleveter the Swift source code is open source. The docs unfortunately are not (AFAIK).

**Comment by lgarron** [comment]
> If you have suggestions, ask on the Trello board.

Ah, I missed that.
