### ISSUE TITLE
Deploy with nginx and pressenger

### ISSUE THREAD

**Issue by ruby232** [Thibaut/devdocs#314]
I create server
server {
      listen 3232;
      server_name localhost;
      root /opt/devdocs/public/;
      passenger_enabled on;
      passenger_intercept_errors off;
      passenger_friendly_error_pages on;
     rails_env production;
}

But launch this error and page is empty
Application Cache Error event: Resource fetch failed (404) http://localhost:3232/assets/application-8331726cacebab5dcaaf0b58df5234bd9f5d6ce9bbad87da15cd86497fa93ee9.js
172.22.0.26/:30 GET http://172.22.0.26:3232/assets/application-8331726cacebab5dcaaf0b58df5234bd9f5d6ce9bbad87da15cd86497fa93ee9.js

**Comment by Thibaut** [comment]
Hi

You should run the app in `development` environment, not `production`.  If it still doesn't work, I'd suggest asking on StackOverflow. I unfortunately don't have time to offer support for running DevDocs locally.

**Comment by ruby232** [comment]
Thanks, change
```sh
rails_env production; 
```
for 
```sh
rails_env development; 
```
and run very good
