### ISSUE TITLE
Swift 2 support.

### ISSUE THREAD

**Issue by MrSpock** [Thibaut/devdocs#315]
Hi,
What a great product you made !
Any chances to get Apple Swift 2 support anytime soon ? Unfortunately I'm not that good with it (yet) to make pull request :)

**Comment by calebkleveter** [comment]
If you have suggestions, ask on the [Trello](https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here) board. But here is what it says about what you want:

>MySQL, ElasticSearch, MongoDB, anything by Apple (Objective-C, Cocoa…), Microsoft (.NET, MS SQL…) or Adobe (ActionScript, Flex…) are all released under restrictive licenses (no redistribution) incompatible with DevDocs — please do not suggest them.

I asked about Swift:

>@tibc , awhile ago I mentioned swift being open source. I found an Apple Blog post on it. https://developer.apple.com/swift/blog/?id=29

And here was the reply:

>@calebkleveter the Swift source code is open source. The docs unfortunately are not (AFAIK).

As for contributing, there is some great documentation on how to do that [here](https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs)! Just make sure you work on ones that are in the Trello todo!

**Comment by Thibaut** [comment]
Thanks @calebkleveter! 

AFAICT all of this is proprietary: 
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/
> Copyright © 2015 Apple Inc. All rights reserved. 

And cannot be redistributed:

> Terms of Use: http://www.apple.com/legal/internet-services/terms/site.html

This may be open source: http://swiftdoc.org/ + the "Swift Programming Language", but it's only available in EPUB format at the moment: (doesn't work with DevDocs)
https://swift.org/documentation/#the-swift-programming-language

Please correct if I'm wrong or if any of this is outdated. Happy to add Swift once the complete docs are open source and available in HTML format.

**Comment by avocade** [comment]
+1 if this has changed.
