### ISSUE TITLE
Filter documentation using a prefix

### ISSUE THREAD

**Issue by ProLoser** [Thibaut/devdocs#316]
In Dash.app for OSX, I give most of my documentation simple prefixes so that I can quickly filter out documentation I don't care about and peruse only a specific set of docs I do. At any point during your query you simply type the prefix followed by a `:` and it switches to that doc.

Some prefixes I've setup personally have been:

```
Javascript - js
HTML - html
AngularJS - ng
CSS - css
Ruby on Rails - ror
Ruby - r
Express.js - e
Node.js - n
Lodash & Underscore - _
etc...
```

When I want to for example search for a function in angular documentation I would type in the following:
`ng:isnumber` and it will only show me search result pages for the documentations that match that prefix (yes multiple documentations can share a similar prefix). I left out the space because on Dash the moment you type the `:` it immediately converts it to a tag and the remaining text entry is treated visually different.

**Comment by binaryannie** [comment]
You can already do that if you hit tab instead of :, though it won't search in more than one doc after you hit tab.

**Comment by Thibaut** [comment]
As @binaryannie said (thanks), you can do the same in DevDocs by typing a documentation name (or an abbreviation) + <kbd>Tab</kbd>.
For example: <kbd>ror</kbd> + <kbd>Tab</kbd>.
