### ISSUE TITLE
problem while installing on Ubuntu 

### ISSUE THREAD

**Issue by superstarrajini** [Thibaut/devdocs#318]
djuser@serverraja:~/devdocs$ rackup
/home/djuser/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'coffee-script'. (Bundler::GemRequireError)
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /home/djuser/devdocs/lib/app.rb:2:in `<top (required)>'
        from /home/djuser/devdocs/config.ru:5:in `require'
        from /home/djuser/devdocs/config.ru:5:in `block in <main>'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /home/djuser/devdocs/config.ru:in `new'
        from /home/djuser/devdocs/config.ru:in `<main>'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
        from /home/djuser/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
        from /home/djuser/.rvm/gems/ruby-2.2.2/bin/rackup:23:in `load'
        from /home/djuser/.rvm/gems/ruby-2.2.2/bin/rackup:23:in `<main>'
        from /home/djuser/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
        from /home/djuser/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
djuser@serverraja:~/devdocs$

**Comment by Thibaut** [comment]
Did you install node.js? The `coffee-script` gem requires it (via [`execjs`](https://github.com/sstephenson/execjs/blob/master/README.md)).

**Comment by Thibaut** [comment]
@superstarrajini ping
