### ISSUE TITLE
Ability to filter out EcmaScript2015, EcmaScript2016 etc

### ISSUE THREAD

**Issue by stevage** [Thibaut/devdocs#319]
It would be helpful to be able to completely filter out all JavaScript functions specific to ES2015+. Our project doesn't allow them, and I keep almost using some function because I see it in the list.

**Comment by Thibaut** [comment]
Thanks for the suggestion. I think this is too much effort for a small payoff. It'll get harder to maintain every year and MDN's metadata isn't always accurate/complete. This is good enough IMO:

![devdocs - javascript array entries 2016-01-30 10-15-35](https://cloud.githubusercontent.com/assets/17579/12696509/b70de436-c73a-11e5-97c8-1e1e26a7c985.png)
