### ISSUE TITLE
Index.json items missing or moved

### ISSUE THREAD

**Issue by OKNoah** [Thibaut/devdocs#320]
Hi. I have downloaded the cleaned version of the Python 2 docs and found the `index.json` file useful. However, some of the items in the file have incorrect names or paths. I'm just wondering why that is and what it might mean for anyone using this file and wether there is a way to get a similar file that represents the code better.

For example,

    {
      "name": "findertools.copy()",
      "path": "library/macostools#findertools.copy",
      "type": "Mac OS"
    },
    {
      "name": "findertools.launch()",
      "path": "library/macostools#findertools.launch",
      "type": "Mac OS"
    },
    {
      "name": "findertools.move()",
      "path": "library/macostools#findertools.move",
      "type": "Mac OS"
    },
    {
      "name": "findertools.Print()",
      "path": "library/macostools#findertools.Print",
      "type": "Mac OS"
    },
    {
      "name": "findertools.restart()",
      "path": "library/macostools#findertools.restart",
      "type": "Mac OS"
    },
    {
      "name": "findertools.shutdown()",
      "path": "library/macostools#findertools.shutdown",
      "type": "Mac OS"
    },
    {
      "name": "findertools.sleep()",
      "path": "library/macostools#findertools.sleep",
      "type": "Mac OS"
    },

all these items have been either renamed to `macostools` (`.copy()`) or removed from that file. The `curses` stuff also seems to be moved or removed.

**Comment by Thibaut** [comment]
Hi - This is a bug in the scraper. Most pages have a single `<div class="section">` but [this page](https://docs.python.org/2.7/library/macostools.html) has two, and [this filter](https://github.com/Thibaut/devdocs/blob/87080c24ea13935dda640e5161b10b090268e55d/lib/docs/filters/python/clean_html.rb#L5) removes everything but the first one. I'll fix it soon.
