### ISSUE TITLE
VS Code plugin

### ISSUE THREAD

**Issue by khrome83** [Thibaut/devdocs#321]
How do we go about getting s VS Code plugin put together?

**Comment by Thibaut** [comment]
No idea, sorry. If you need changes in DevDocs core to accommodate a plugin, let me know and I'd be happy to help, but I have no interest in developing the plugin myself (I don't use VS / Windows).

**Comment by mikaoelitiana** [comment]
@khrome83 there is this now https://github.com/benhjt/vscode-devdocs
