### ISSUE TITLE
Offline feature stopped working on Google Chrome

### ISSUE THREAD

**Issue by suriya** [Thibaut/devdocs#322]
First of all, thank you for a great product. I use devdocs.io a lot, especially the offline feature.

Recently, I find that it has stopped working. I got the following message:

> Oops, offline mode is unavailable.
>
> DevDocs requires IndexedDB to cache documentations for offline access.
> Unfortunately Safari's implementation of IndexedDB is badly broken.
> This message will automatically go away when Apple fix their code.

However, I do not use Safari. I use Google Chrome on Ubuntu. Here's my user agent:
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by Thibaut** [comment]
Hi

This is surprising since the app detects this particular Webkit bug by performing a [test IndexedDB transaction](https://github.com/Thibaut/devdocs/blob/87080c24ea13935dda640e5161b10b090268e55d/assets/javascripts/app/db.coffee#L28), not sniffing the user-agent. So if you see the error, your browser must have the Webkit bug (or a related one).

Unfortunately since this is a browser bug there isn't much I can do. I can't replicate using Chrome 47 on OS X and Windows. Could you try Chrome 48 (beta) and 49 (canary)?

**Comment by suriya** [comment]
I am unable to reproduce this behavior on my browser now. It was probably some transient issue.

Thank you once again.

**Comment by bzark** [comment]
Should this work on iPad 2 running v9.1.2 using Google Chrome?  It says IndexedDB is not available.

**Comment by Thibaut** [comment]
@bzark Unfortunately IndexedDB doesn't work on iOS. It's turned off in WebViews (what Chrome uses) and broken in Safari.

**Comment by bzark** [comment]
I was surprised it didn't work on Chrome.  Guessing Apple denied the app and made them turn that feature off.

**Comment by llagerlof** [comment]
Stopped working for me. Offline worked for some hours, and now vanishes. Almost the same OP's error:

> Oops, offline mode is unavailable.
> 
> DevDocs requires IndexedDB to cache documentations for offline access.
> Although your browser appears to support it, DevDocs couldn't open the database.
> This could be because you're browsing in private mode and have disallowed offline storage on the domain.

Well, I am not in private mode, nor disallowed offline storage. I even disabled my ad blocker, but isn't working at all.

**Comment by Thibaut** [comment]
@llagerlof could you try running `app.db.reset()` in the console & reload the app.

**Comment by llagerlof** [comment]
@Thibaut Thanks. I will try later. I am using Firefox now. This problem only happens in Chrome.

**Comment by brutalcrozt** [comment]
> Sorry for opening new issue.
I really a fans of the offline feature, last time (today) i check with chrome and FF it works fine.
But falls on opera  36.0.2130.65
Could you give me step to throubleshoot this?
I also notice i can't access specific page, like http://devdocs.io/cordova/guide/platforms/android/lifecycle
What do you think if we use end to end test to make sure no page is broken?

That was before i can online, i also already have a screenshoot.
I would suggest you put `app.db.reset()` on Ooops offline move is unavaliable.

**Comment by devillized** [comment]
hi, I have  chrome running on OS X & faced this issue even though i don't use safari.

But, confirming what @brutalcrozt  said above. 
A reset() in console & reloading the page gets the offline version working.

**Comment by Thibaut** [comment]
This should be fixed by https://github.com/Thibaut/devdocs/commit/800622099f34ac4a8ff5dff57c1fb6ef623bb227

**Comment by josejbreijo** [comment]
I had the same problem in Chromiun 55 on Linux Mint 18.1 but I solved it using `app.db.reset()`, so thumbs up
