### ISSUE TITLE
java(not javascript) documentation 

### ISSUE THREAD

**Issue by zero9ji** [Thibaut/devdocs#324]
I could not found the java EE documentation, i think the team should add it.
thanks

**Comment by Kaijiro** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations

Please don't open issues to request new documentations.
Use the [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation) where everyone can vote and contributors can get a feel for what is most wished for.

**Comment by zero9ji** [comment]
OK could the  project admins delete this issue?
