### ISSUE TITLE
Suggestion: Smooth scrolling when using keyboard shortcuts

### ISSUE THREAD

**Issue by sbrl** [Thibaut/devdocs#328]
Smooth scrolling when using the keyboard shortcuts would prevent me from getting lost when I scroll with the `<space>` keyboard shortcut, for example.

**Comment by sbrl** [comment]
Awesome, thanks!

I'm looking forward to trying this out in the next release.

**Comment by Thibaut** [comment]
@sbrl It's out. Just reload the page :)

**Comment by sbrl** [comment]
Yep, that works.
Thanks!

**Comment by jablan** [comment]
any way to disable the smooth scrolling? :/

**Comment by Thibaut** [comment]
@jablan I have plans to add a settings panel in the next couple months. Until then there's no good way to add user settings.
