### ISSUE TITLE
MathML source passed through

### ISSUE THREAD

**Issue by echristopherson** [Thibaut/devdocs#331]
On pages with MathML, devdocs seems to pass through the MathML source instead of rendering it. For instance, <http://devdocs.io/javascript/global_objects/math/pi> shows `\mathtt{\mi{Math.PI}} = \pi \approx 3.14159`.

**Comment by echristopherson** [comment]
I see I ran up against Chrome's known lack of support for MathML. When I go to <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/PI>, the page tells me "Your browser does not support MathML. A CSS fallback has been used instead.", and it does use a fallback which displays correctly. I wonder if DevDocs could employ a similar fallback.

**Comment by japborst** [comment]
I think [MathJax](https://www.mathjax.org/) could be very well employed for this. Also see [MathML input](http://docs.mathjax.org/en/latest/start.html#mathml-input) in the docs.

**Comment by Thibaut** [comment]
IMO MathJax is too big/slow for DevDocs. @japborst added a CSS fallback in https://github.com/Thibaut/devdocs/pull/496 which I think is enough to close this issue.
