### ISSUE TITLE
JavaScript prototype methods not distinguished from methods on constructor

### ISSUE THREAD

**Issue by echristopherson** [Thibaut/devdocs#332]
Entries for things like Array.prototype.shift (<http://devdocs.io/javascript/global_objects/array/shift>) are shown using the notation `Array.shift` in the sidebar, page title, and page header, which makes it impossible to tell without reading some of the page that the property belongs to the prototype and not the Array constructor. MDN does show this distinction; see <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift>.

I don't know if there's a good reason for this in DevDocs, but I would like to see prototype properties distinguished.

**Comment by Delapouite** [comment]
Absolutely. Removing the `prototype` part is misleading, especially for new comers to the languages.
