### ISSUE TITLE
Devdocs never works offline

### ISSUE THREAD

**Issue by wzup** [Thibaut/devdocs#333]
Your app never works offline. Every time I have no internet and try to open your app (I have added it to Chrome apps menu), it never opens. Only Chrome default page always says "You have no internet connection". I have installed all docs I need, however it doesn't work offline. Why? What else should be activated to enable offline mode?

![devdocs - offline - google chrome 2016-01-19 16 26 42](https://cloud.githubusercontent.com/assets/3880497/12413420/ac63431a-bec9-11e5-87a6-71beb8452190.png)

**Comment by Thibaut** [comment]
What answer do you see after the "Can I close the tab/browser? " question in the Q&A section?

**Comment by Thibaut** [comment]
Can't fix this without more info.

**Comment by muturi254** [comment]
install the docs first
