### ISSUE TITLE
Item gets added twice.

### ISSUE THREAD

**Issue by pecey** [Thibaut/devdocs#334]
![rsz_screenshot_from_2016-01-20_08-17-04](https://cloud.githubusercontent.com/assets/11463842/12438647/bfd58590-bf4e-11e5-944b-935aef3d5d01.png)

As clearly visible, Angular got added twice. I probably clicked twice, but ideally, something which is already enabled shouldn't be added to the list again.

**Comment by Thibaut** [comment]
Thanks for reporting the bug!
