### ISSUE TITLE
Add Ruby 2.3 docs

### ISSUE THREAD

**Issue by swrobel** [Thibaut/devdocs#335]

**Comment by Kaijiro** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations

Please don't open issues to request new documentations.
Use the [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation) where everyone can vote and contributors can get a feel for what is most wished for.

Furthermore, you can see that docs versionning is [already in discussion](https://github.com/Thibaut/devdocs/issues/25) and @Thibaut seems to have worked on it.
