### ISSUE TITLE
DB error when trying to install offline documentation of both Python versions

### ISSUE THREAD

**Issue by gpgekko** [Thibaut/devdocs#342]
With the new multi version support, I selected both version (2.7 and 3.5) and tried to install the offline documentation. However, I get the following error:

> Uncaught NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found. (application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2330)

I *think* I had Python installed before the multi version change, but I'm not 100% certain.

This is on the latest Chrome beta on a Windows 10 machine.

Full stacktrace:
> app.DB.e.idbTransaction	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2330
(anonymous function)	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2217
app.DB.e.runCallbacks	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2204
app.DB.e.onOpenSuccess	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2197
(anonymous function)	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2166
IndexedDB (async)		
app.DB.e.db	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2179
app.DB.e.store	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:2213
(anonymous function)	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:3038
c	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:1591
s	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:1588
e.async.t.onreadystatechange	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:1577
XMLHttpRequest.send (async)		
ajax	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:1554
app.models.Doc.n.install	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:3040
app.views.OfflinePage.o.onClick	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:3553
(anonymous function)	@	application-29746e5be9d306b1ff02cb481d1e95b557e23e0894f3bd48ba00ce4630d37ff2.js:3506

**Comment by Kaijiro** [comment]
Hey,

What are the both version that you are talking about ? Python ?

**Comment by gpgekko** [comment]
These two:

![knipselpp](https://cloud.githubusercontent.com/assets/5121420/12609313/4958ab34-c4e1-11e5-9b3b-13dd422dab98.PNG)

**Comment by Thibaut** [comment]
Thanks for the bug report. I'll investigate this week-end.

**Comment by Thibaut** [comment]
Can you still replicate this or did it only happen once?

**Comment by gpgekko** [comment]
I could reproduce it that whole week, but today it seems to be fixed!
