### ISSUE TITLE
Some code snippets in C++ are corrupted

### ISSUE THREAD

**Issue by MarPan** [Thibaut/devdocs#351]
E.g.: 

Compare the last example in std::transform:
http://devdocs.io/cpp/algorithm/transform
http://en.cppreference.com/w/cpp/algorithm/transform

The whole beginning of lambda function is missing: "[](unsigned char c) { return std"

**Comment by sim642** [comment]
It's not corrupted, just outdated: http://en.cppreference.com/mwiki/index.php?title=cpp%2Falgorithm%2Ftransform&diff=83193&oldid=83191.

**Comment by Thibaut** [comment]
Can't fix this until cppreference.com releases a new offline archive: http://en.cppreference.com/w/Cppreference:Archives
The last one was November 29. The fix was made January 23.
