### ISSUE TITLE
‘Tabbing’ into a particular docset should also update the sidebar

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Thibaut/devdocs#360]
So, after having typed ‘Node’, the first result is ‘Node.js’; if I click the hamburger next to it in the sidebar, then the sidebar becomes focused on the Node.js documentation, with a nice TOC. If I hit `tab` instead, then I can further search *specifically through* that documentation.

Unfortunately, I have to choose one or the other; *and* I have to hunt down that light-grey hamburger with my eyes/mouse.

I would posit that tab-selection of a documentation-set should also focus on that set in the sidebar, displaying the same TOC of documentation-contents as clicking on the hamburger does.

**Comment by Thibaut** [comment]
Thanks for the suggestion!
