### ISSUE TITLE
Error when downloading docs

### ISSUE THREAD

**Issue by declanmarks** [Thibaut/devdocs#361]
When I install the app I can download the docs for offline that come by default. But when I add more Languages and try to download docs then it fails. 

So I can't download docs of languages that I have enabled and can on the ones that are enabled by default.

**Comment by Thibaut** [comment]
Are you installing the app / downloading the docs? Locally or on devdocs.io? Please post screenshots and/or command logs.

**Comment by Thibaut** [comment]
Can't fix without more info.

**Comment by declanmarks** [comment]
Sorry, I haven't replied but I have been very busy with college work. I have been using your app on the app store. I have tried it through chrome and it works, it just doesn't work through your app, very strange. I can download docs from the default items, just new ones don't work. I would prefer to use the app rather than browser just to keep it separate. Below is 


![before](https://cloud.githubusercontent.com/assets/9248192/14495541/d68cdf88-0187-11e6-9f77-4fe040339e70.png)
![error](https://cloud.githubusercontent.com/assets/9248192/14495539/d6847730-0187-11e6-9258-91d9a7d98c30.png)
