### ISSUE TITLE
NumPy, SciPy, Scikit-Learn

### ISSUE THREAD

**Issue by jadedevin13** [Thibaut/devdocs#364]
Please consider these documentations. Thank you.

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations 
https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by Styrke** [comment]
I also use these regularly, so maybe I'll add them in the future (after #353).
