### ISSUE TITLE
Can not use in iPhone

### ISSUE THREAD

**Issue by kentaro0919** [Thibaut/devdocs#365]
Great project!!!

I think http://pouchdb.com/ can give a answer.

**Comment by Thibaut** [comment]
Do you mean the offline mode doesn't work?

**Comment by kentaro0919** [comment]
Yes, pouches can run in many browsers
http://pouchdb.com/faq.html

**Comment by Thibaut** [comment]
Sorry, I don't want to rewrite the app's offline code + import a big 3rd-party dependency, just because Apple ships a broken IndexedDB. Offline mode will work on Safari & iOS as soon as Apple ships https://bugs.webkit.org/show_bug.cgi?id=149117.
