### ISSUE TITLE
Way to limit search scope with keyboard

### ISSUE THREAD

**Issue by tino** [Thibaut/devdocs#368]
Right now you can go to http://devdocs.io/python/ and everything you search for is limited to the Python documentation. There is no way (at least to my knowlegde) to accomplish this without midifying the URL.

On a side note, searching with the language/framework as first term doesn't give any results (go to http://devdocs.io/ and search for `python timezone` -> no results. Go to http://devdocs.io/python/ and search for `timezone` and voila.

**Comment by Thibaut** [comment]
There is :) http://devdocs.io/help#doc_search

**Comment by tino** [comment]
🙀 sorry! And thanks for the great app :smile:
