### ISSUE TITLE
Cloudflare's "email protection" mangles examples that contain @

### ISSUE THREAD

**Issue by pornel** [Thibaut/devdocs#373]
[Document](https://nodejs.org/dist/latest-v5.x/docs/api/url.html) that shows an example URL with `@` in it:

    'http://user:pass@host.com:8080/p/a/t/h?query=string#hash'

Appears in devdocs.io as 

     'http://user:[email protected]*:8080/p/a/t/h?query=string#hash'

and links to https://nodejs.org/cdn-cgi/l/email-protection

> Email Protection
You are unable to access this email address nodejs.org
The website from which you got to this page is protected by CloudFlare.

**Comment by Thibaut** [comment]
Thanks for the bug report. I'll try to fix this in the next update.
