### ISSUE TITLE
Incredible

### ISSUE THREAD

**Issue by ericclemmons** [Thibaut/devdocs#375]
This is an incredible project with an incredible UX, performance, and quality.

You're doing outstanding work and I wanted to open this issue to give you :clap:.

**Comment by ericclemmons** [comment]
I just got back to the car and found some more!

:tada: :balloon: :cake: :beers: :bear: :bikini: (don't ask)

**Comment by Thibaut** [comment]
Thank you :heart: 

It's been a lot of work over the years (still is). I'm glad the work I did around UX & performance doesn't go unnoticed :smile:
