### ISSUE TITLE
Add a "Search all" to dropdown to search over all doc sets when match isn't found in activated sets

### ISSUE THREAD

**Issue by qq99** [Thibaut/devdocs#38]
It's not apparently obvious that I have to activate a documentation set
I saw underscore in my list of potential sources, but didn't activate it.  When I was searching, I got no result -- made me think devdocs was broken

I think it might be nice to have a spot where you "Search over non-activated documentation sources" when there are no results

**Comment by Thibaut** [comment]
For performance reasons (don't want to load all indexes all the time) I won't add that functionality. 

Last year I added a link to enable docs when no results are found:

![devdocs 2015-03-29 15-13-18](https://cloud.githubusercontent.com/assets/17579/6887226/43dfe9e2-d626-11e4-962b-d4ea88d43ed5.png)

This should mitigate the "discoverability" issue.
