### ISSUE TITLE
Stop removal of (some) empty tags?

### ISSUE THREAD

**Issue by howardjones** [Thibaut/devdocs#381]
I'm writing a scraper for the perl docs, and they use manpage-style formatting with a series of sections. Each section starts:
`<a name="OO-Perl"></a><h2>OO Perl</h2>`
and the `<a>` gets removed by the built-in filters in devdocs. The links between sections are useful though - what is the intended solution for this?

**Comment by Thibaut** [comment]
In your `clean_html` filter, move the `name` attribute of those links to an `id` attribute on the next element. That way the element (heading) will be highlighted correctly in the UI when scrolled to, and we can keep removing all empty tags, some of which can often break stuff.

E.g. https://github.com/Thibaut/devdocs/blob/905d6cee9e3e1c9737088f7fb4da53d1c28453ad/lib/docs/filters/nginx/clean_html.rb#L15-L18
