### ISSUE TITLE
bug: copy button on code snippets doesn't work on firefox 37

### ISSUE THREAD

**Issue by Phoenix-Brothres** [Thibaut/devdocs#383]

**Comment by Thibaut** [comment]
Any reason why you haven't upgraded Firefox? The current version is 45.

**Comment by Thibaut** [comment]
This was fixed in Firefox 41: https://www.fxsitecompat.com/en-CA/docs/2015/document-execcommand-for-cut-copy-and-paste-no-longer-throws/
