### ISSUE TITLE
Add support for font-awesome

### ISSUE THREAD

**Issue by orf** [Thibaut/devdocs#387]
Hey,
I love this project and your site, I think it's a fantastic timesaver! One thing I do have to leave devdocs to search often is font-awesome icons, could this be incorporated into the project? The search bar on their site works for aliases (searching for tick shows the `check` icon), if those aliases are public then those could be added as well.

I think a list of font-awesome icons technically qualifies as documentation, but I can understand if you disagree :+1:

**Comment by Thibaut** [comment]
Hey,

See https://trello.com/c/Wg57lb0u/275-font-awesome

The main problem with docs like Font Awesome, Bootstrap, etc. is that they require their own CSS/JS. DevDocs only works with static HTML. Otherwise the app would break (conflicting CSS/JS) or get slow / bloated / hard-to-use.

**Comment by stgogm** [comment]
Sorry for the bump but I'm really missing this. Is it possible to address this like Bootstrap? Mainly to be able to find the icon names and helper CSS classes.

Thanks!
