### ISSUE TITLE
Error when downloading docs

### ISSUE THREAD

**Issue by declanmarks** [Thibaut/devdocs#388]
This is a reply to a previous post but has been closed, https://github.com/Thibaut/devdocs/issues/361

Sorry, I haven't replied but I have been very busy with college work. I have been using your app on the app store. I have tried it through chrome and it works, it just doesn't work through your app, very strange. I can download docs from the default items, just new ones don't work. I would prefer to use the app rather than browser just to keep it separate. Below is a screenshot of my android phone.

![before](https://cloud.githubusercontent.com/assets/9248192/14495541/d68cdf88-0187-11e6-9f77-4fe040339e70.png)

![error](https://cloud.githubusercontent.com/assets/9248192/14495539/d6847730-0187-11e6-9258-91d9a7d98c30.png)

**Comment by Thibaut** [comment]
Thanks for the info. I can see the exceptions getting logged but I have no idea how to replicate or fix. Seems that IndexedDB gets locked to a certain version.

Which app store did you install the app from?

**Comment by declanmarks** [comment]
I am using the current version from the Google Play Store.

**Comment by Thibaut** [comment]
You're using an unofficial app made by someone who is wrongly using the "DevDocs" name for profit (the app is showing ads, and they're selling an ads-free version). Please stop using it.

Visit http://devdocs.io in Chrome and select "Add to home screen" in the menu. You'll get the same app, with no ads, and a fully functional offline mode.

**Comment by declanmarks** [comment]
Thank you. I just thought that this was your app and their was a problem with it.

**Comment by JesseTG** [comment]
Did you remember to report the faker?

**Comment by Kaijiro** [comment]
Maybe you could give us the app name with the editor name so we could mass report it.

**Comment by Thibaut** [comment]
This is the app: https://play.google.com/store/apps/details?id=com.funtitudeapps.devdocapp&hl=en 

@Kaijiro it's still technically a bug, just one I'm probably not going to try to fix. I might add an in-app warning for users of that app. Then I'll close the issue.

**Comment by Thibaut** [comment]
For the record, I contacted the developer of that app weeks ago to ask them to change the name. They haven't replied.

**Comment by Thibaut** [comment]
I added a message on the home page when the app runs in an Android WebView. Could someone check that it's displayed in the "unofficial" app please?

**Comment by robert-bosweb** [comment]
@Thibaut yes, the message does appear. (Android 6.0.1, Nexus 6P)

![screenshot_20160526-104653](https://cloud.githubusercontent.com/assets/6226952/15560503/7ebe6564-232f-11e6-85e5-0b45e0dca001.png)

**Comment by Thibaut** [comment]
@obert-bosweb thanks. I'll close this issue then.
