### ISSUE TITLE
Improved desktop wrapper

### ISSUE THREAD

**Issue by robinbastien** [Thibaut/devdocs#39]
I was thinking of scripting up a desktop wrapper for devdocs. Currently I have it wrapped with Fluid as indicated in your docs, but it would be nice to improve the wrapper with taskbar/menu options, a custom app icon, and have proper sync abilities so it can load offline if need be. I was thinking TideSDK, Node-Webkit, or even trying out the new Brackets-Shell.

Thoughts?

**Comment by mcoquet** [comment]
@robinbastien @Thibaut  hi! whats the status on this? anyone pick this idea up?

**Comment by Thibaut** [comment]
@mcoquet This feature is pretty low on my todo list, especially now that DevDocs works offline in the browser. Contributions are welcome though.

**Comment by mcoquet** [comment]
@Thibaut thx for the quick reply! Yeah, I figured as much. It sounds like something that would make more sense to live as a separate project ? What do you think?

**Comment by Thibaut** [comment]
@mcoquet yes this would likely live in a separate repo.

**Comment by theblacklion** [comment]
I'm using the Chrome extension and have it have added a menu shortcut. Together with the offline support I'm a very happy dev now :).

**Comment by Thibaut** [comment]
Closing this. DevDocs is now fully functional offline so there is less of a need for a desktop app. If someone wants to take a stab at creating a taskbar/menu wrapper I'd gladly advertise it on DevDocs. But I don't have the skills to do that myself.
