### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by calebmer** [Thibaut/devdocs#396]
When I am focused on the search box I can not tab out of the search box. Also when trying to tab through navigation links there is no visual representation of which link is in focus.

**Comment by Thibaut** [comment]
Hey - I'll try to make some improvements soon. Note that you can use `alt+f` (http://devdocs.io/help#shortcuts) to focus the first link in the main content area, and then use `tab` to cycle through all of them.

**Comment by Thibaut** [comment]
Should work now.
