### ISSUE TITLE
Download offline PHP 

### ISSUE THREAD

**Issue by BerDev** [Thibaut/devdocs#399]
When I select php to download it offline, I get ERROR.

regards,
Hamza.
![image](https://cloud.githubusercontent.com/assets/18898874/14948189/7c882652-1035-11e6-8350-8b1cb5fdf8f7.png)

**Comment by Thibaut** [comment]
Which browser / OS are you using? How much free disk space do you have on your computer?

**Comment by BerDev** [comment]
I have tried with Chrome and Mozilla, it was the same issu, I have no problem with disk space.

regards,

**Comment by Thibaut** [comment]
Does it work if you uninstall the other docs?
Do you see any error in the console?
Are you able to load [this URL](http://docs.devdocs.io/php/db.json?1459697848)?

**Comment by Thibaut** [comment]
Can't fix without more info (https://github.com/Thibaut/devdocs/issues/399#issuecomment-219297625).
