### ISSUE TITLE
What happend to Firefox app version?

### ISSUE THREAD

**Issue by Nosthertus** [Thibaut/devdocs#400]
I was using the firefox version of this application, when i switched to ubuntu and download the firefox version in ubuntu, the link is no longer there, and the store says the browser does not support it anymore..

**Comment by Thibaut** [comment]
Mozilla is shutting down the Firefox Marketplace and removing the Web Runtime from Firefox: 
https://wiki.mozilla.org/Marketplace/FutureofMarketplaceFAQ
