### ISSUE TITLE
Groovy and Grails

### ISSUE THREAD

**Issue by 4goodapp** [Thibaut/devdocs#401]
Can you add the Apache Groovy programming language and its Grails web framework docs please.

Groovy http://groovy-lang.org/documentation.html
Grails docs: https://grails.org/documentation.html

 And let me know if it's not the right place to post this

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by Eccenux** [comment]
For those interested in voting :-)
https://trello.com/c/C9OemstM/143-groovy
