### ISSUE TITLE
Local file names from slugs are not being sanitized

### ISSUE THREAD

**Issue by nucular** [Thibaut/devdocs#402]
*Repeatable:* When remote slugs contain characters unsafe for the local file system (in my case NTFS on Windows 7)

*Steps to repeat:*
1. Clone my [fork](https://github.com/nucular/devdocs/tree/love) for the LÖVE scraper (at the time of writing HEAD of the branch `love`)
2. Run `thor docs:page love Canvas:renderTo` (which might fail because the `docs:page` command is broken, just remove the check at [lib/tasks/docs.thor#L34:L36](https://github.com/Thibaut/devdocs/blob/master/lib/tasks/docs.thor#L34:L36) for now).

*Expected result:* `public/docs/love/canvas:renderto.html` (or similar) is generated.

*Actual result:* `public/docs/love/canvas` is generated.

While writing a scraper for the [LÖVE](http://love2d.org) engine documentation I ran into an issue where remote pages with colons in their slugs (for example [Canvas:renderTo](https://love2d.org/wiki/Canvas:renderTo)) are being written to files named like the slug up to the first colon (for example `public/docs/love/canvas`). This results both in subsequent pages overwriting this file and in the client not being able to find this file under the expected path.

I would fix this problem myself in a pull-request, but I am neither sure where path sanitization logic would be appropriately placed (I assume in `Docs.Doc#path`) nor what to replace unsafe characters with to keep the integrity of other documentations.

**Comment by Thibaut** [comment]
Hey - sorry for the late reply.
Try adding `options[:decode_and_clean_paths] = true` to your scraper.

**Comment by nucular** [comment]
Thanks for the help!
When enabling that option pages are being stored in appropriate paths, but links to them from other pages don't seem to be affected by this (`canvas`instead of `canvas-renderto.html`). I have tried regenerating the entire documentation from a clean slate, but the problem persists.

**Comment by Thibaut** [comment]
Rebase with master and it should work :) (fix is in 2813cf9be32cf6f2dc69abca75069084d871aeb6)
