### ISSUE TITLE
Reloading for new version resets selected documentation

### ISSUE THREAD

**Issue by ssokolow** [Thibaut/devdocs#404]
I'm running Firefox Aurora on Android Lollipop and, both times DevDocs has asked me to reload to apply an update, it resets the list of selected docs to CSS, DOM, DOM Events, HTML, HTTP, and JavaScript.

This doesn't affect the downloaded content as, once I reselect the docs I want, it's listed as downloaded and up to date on the Offline page.

Given that my privacy extensions tie cookies and all other stored content together under the same preference (meaning the same rules govern downloaded docs and the list of selected docs), it shouldn't be my privacy extensions at fault.

**Comment by Thibaut** [comment]
Please disable your privacy extensions and see if the problem still happens. The selected docs are stored in a cookie and no one else has reported a similar problem, so I can't think of another explanation than your extensions are interfering with cookies.

PS: the downloaded docs are stored in a different place than the selection itself (IndexedDB vs. cookies).

**Comment by ssokolow** [comment]
At the moment, I can't test anything since my only Android device had to be returned after the LCD cable failed (fixed lines in display output) and I use Zeal for reading docs on my desktop.

(However, I did make a backup, so I'll be able to test once I get some new hardware to restore it to.)

It shouldn't be the extension, though, since:
1. The behaviour I observed had it persisting the selection beyond the "10 seconds after the last devdocs tab is closed" point.
2. It's set to flush all stored state on the same trigger to limit the effectiveness of supercookies. It'd do a pretty poor job of that if it omitted IndexedDB.

**Comment by Thibaut** [comment]
With the information I have, the only explanation is that something is blocking (or deleting) cookies on the device, which is outside of DevDocs's control. The code that stores the doc selection has been in production for 2+ years without issues.

If you're able to replicate with all extensions disabled, let me know and I'll reopen this.
