### ISSUE TITLE
Angular: guide/component not crawled

### ISSUE THREAD

**Issue by simon04** [Thibaut/devdocs#405]
With Angular 1.5 a new guide has been added: https://code.angularjs.org/1.5.5/docs/guide/component, but it does not get crawled and is missing on http://devdocs.io/angular~1.5-guide/.

I discovered this on http://devdocs.io/angular~1.5/api/ng/provider/$compileprovider, by following the link "component guide" (which points to to http://devdocs.io/angular~1.5/api/ng/provider/guide/component).

**Comment by Thibaut** [comment]
Thanks for the bug report.
