### ISSUE TITLE
Angular 2?

### ISSUE THREAD

**Issue by giacomocerquone** [Thibaut/devdocs#409]
What about adding the documentation of angular 2 now that it's in its "release candidate" version?

**Comment by Thibaut** [comment]
Only when the stable version is released. Angular is among the most difficult docs to scrape. I'd rather not risk having to do that work twice, if they significantly change their docs between now and the stable release.

**Comment by eladcandroid** [comment]
It's still can be very helpful and it won't be changed so much..
