### ISSUE TITLE
Additional documentation for lower level protocols like DNS or TCP/IP, and UDP

### ISSUE THREAD

**Issue by sigmonsays** [Thibaut/devdocs#410]
Great job!

I am interested in getting lower level protocols into the site. I personally would like TCP/IP, DNS, and UDP. I'm sure there are others like SCTP, BGP, OSPF, ARP, ETHERNET, etc.

Is there a generic tool for importing RFCs?

**Comment by Kaijiro** [comment]
Hey @sigmonsays 

I don't know if RFC's really fits DevDocs philosophy.

Actually, I think there is no scrapper for RFCs and I think @Thibaut will not see any problem if you make your own fork of DevDocs to create a srapper for RFCs.

The "problem" I can see, is that there is REALLY a lot of RFCs and you'll have to find a way to sort them (As you can see, every part of the application is splitted into development langage / application).

Furthermore RFCs are not so easy / pleasant to read. 

But I like the idea and I wish you good luck if you want to try :)

**Comment by Thibaut** [comment]
RFCs don't really share a common structure other than being text-based. Also I don't know of a site that has all of them in a scrape-able format.

Could you post links to the RFCs you'd like to see on DevDocs? Happy to look into it if it's not too much work and the RFCs' license allows redistribution.
