### ISSUE TITLE
Offline content not delivered when connected to wifi & no internet

### ISSUE THREAD

**Issue by SalathielGenese** [Thibaut/devdocs#413]
I wondered, about 5 months I'm using devdocs & such a things never happened. Our Internet was bad (I mean off) but I was connected to our local WIFI.. and devdocs was not working. I even reset my browsers settings, cleared the cache, etc.... Nothing!

When Internet came back, I first re-installed (let me state it so) all my favorite docs, and I switched off the WIFI to see how it'll behave. When everything was OK, I then tried to understand...

But I still wonder what Internet have to do with a content that's supposed to come from local DB.

**Comment by Thibaut** [comment]
Does it work now? Loading the app while offline was broken for a couple weeks. I fixed it last week.

**Comment by SalathielGenese** [comment]
Everything seem OK.
Thanks!
