### ISSUE TITLE
Add documentation for MongoDb

### ISSUE THREAD

**Issue by SalathielGenese** [Thibaut/devdocs#414]
More & more developers will be looking to JavaScript. Thanks because `Js`, `Ts`, `ng`, `& co` are already available, but to add `MongoDb` will be fine.
Just look at the number of people in their community & moreover, the number of student who registered for their classes at mongo university `May 2016`. I'm one of them & thought it would be great to have their docs at finger's tip through `devdocs`.

Thanks.

**Comment by Kaijiro** [comment]
Hi @SalathielGenese 

@Thibaut already took a look to the MongoDB documentation, but its license doesn't allow to integrate it inside DevDocs.

You can also look at [this Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation)where there is every langage done, planned to do and incompatible.
