### ISSUE TITLE
Wrong tab indentation size in git docs

### ISSUE THREAD

**Issue by monk-time** [Thibaut/devdocs#422]
The default css value `tab-size:2` for `pre`/`code` tags mangles indentation in git docs, which seem to use 8 as tab size. I haven't checked other docs, but I assume they may have the same issue.

**Example:** 
(expected) https://git-scm.com/docs/git-checkout#_detached_head - the second code block has a tab on the third line (before HEAD) and two tabs behind the following arrow:
![git](https://cloud.githubusercontent.com/assets/7759622/16006392/8e2f23e0-3175-11e6-8247-2a8fd865fac0.png)

(actual) http://devdocs.io/git/git-checkout#_detached_head - the wrong indentation makes the example quite confusing:
![devdocs](https://cloud.githubusercontent.com/assets/7759622/16006395/9376c768-3175-11e6-8415-ca50b71342c4.png)

Win7x64, Firefox 47, Chrome 51 (same in both browsers)

**Comment by Thibaut** [comment]
Thanks for the bug report. I'll fix this up soon.

It's unlikely other docs are affected as most of them use spaces, not tabs, but if you see anything that looks off, let me know.
