### ISSUE TITLE
Missing Padrino on the front-page

### ISSUE THREAD

**Issue by wikimatze** [Thibaut/devdocs#425]
Going to http://devdocs.io/ and searching for Padrino gives me no match. Is there missing something for it?

**Comment by Thibaut** [comment]
It works for me:

![devdocs api documentation 2016-06-22 08-16-51](https://cloud.githubusercontent.com/assets/17579/16266234/c47f6094-3851-11e6-8deb-a84646244bf9.png)

Maybe your cache is outdated and not updating? What's the most recent news item you see [here](http://devdocs.io/news)?

**Comment by wikimatze** [comment]
Now I see it, I even tried the IE when I created this issue and couldn't find it.
