### ISSUE TITLE
R docs disappeared

### ISSUE THREAD

**Issue by hack-r** [Thibaut/devdocs#428]
It seems that somehow the R docs have disappeared!

**Comment by Thibaut** [comment]
Do you mean the R programming language? That doc has never been available on devdocs.io.

**Comment by hack-r** [comment]
Oh, okay, yes that must be the problem. ;) 

I guess that was my way of trying to suggest to add R because we like your service but not including R is highly offensive to my people.

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
