### ISSUE TITLE
Add Sequelize ORM

### ISSUE THREAD

**Issue by felixfbecker** [Thibaut/devdocs#430]
The sequelize docs are horrible to get around, I would love to search & read them with devdocs.
http://docs.sequelizejs.com/en/latest/

**Comment by felixfbecker** [comment]
Sorry for not reading contrib guide

**Comment by waldyrious** [comment]
> Sorry for not reading contrib guide

To add more context, the contribution guidelines recommend not adding issues in this repo requesting new docs, but instead creating (or voting on) cards in the [public Trello board](https://trello.com/c/oFaPsh28).

In particular, there's already [a card for adding Sequelize](https://trello.com/c/oFaPsh28/139-sequelize). If anyone's interested, go there, vote it up and follow the card to stay updated on any developments.
