### ISSUE TITLE
Add Redux Documentation

### ISSUE THREAD

**Issue by vladejs** [Thibaut/devdocs#431]
Will be awesome to have this valuable documentation in devdocs.

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by morenoh149** [comment]
Is there a process for requesting updates? the redux docs are very out of data and has misleading information

**Comment by j-f1** [comment]
@morenoh149 [Request updates here](https://trello.com/c/2B0hmW7M)
