### ISSUE TITLE
Some icons are not showing properly

### ISSUE THREAD

**Issue by elegantcoder** [Thibaut/devdocs#435]
I saw that the icon sprites is not fit for some docs. 
See the following;

Q (what I contributed :-)  )
<img width="174" alt="screen_shot_2016-07-09_at_11_02_18_pm" src="https://cloud.githubusercontent.com/assets/1222972/16708344/3807c024-462b-11e6-8dce-2b67cf3ae887.png">

Vue.js
<img width="556" alt="screen_shot_2016-07-09_at_11_02_48_pm" src="https://cloud.githubusercontent.com/assets/1222972/16708346/3bd33c10-462b-11e6-896f-c04a5587e2d5.png">

And I opened the image on the Photoshop, I just know what was going on. 
<img width="1243" alt="screen_shot_2016-07-09_at_11_17_18_pm" src="https://cloud.githubusercontent.com/assets/1222972/16708353/7bb8d222-462b-11e6-8b38-a3a14c6bc55f.png">

In detail, the icon of Drupal has extra padding 1px on the left 
(2px -> 3px), so icons on the right of it, pushed right by 1px.

**Comment by Thibaut** [comment]
Thanks for the bug report!

**Comment by elegantcoder** [comment]
Oh, I didn't find where the sprite file is. If I knew, I clould send the pull request :-) 

👍

**Comment by Thibaut** [comment]
No worries. I have a separate file that I generate the PNGs from anyway, so a PR wouldn't have helped.
