### ISSUE TITLE
Drupal doc links in footer are broken

### ISSUE THREAD

**Issue by nielsonm** [Thibaut/devdocs#437]
When I click on the link in the footer of the Drupal documentation page I get a 404 error.

Example links:

https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu_alter

Links to a 404 page, whereas adding `/7.x`  gets the correct page. 

https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu_alter/7.x

**Comment by Thibaut** [comment]
Fixed by a120b88545bd10c629c8fd50c24e4d993154a3ae

**Comment by nielsonm** [comment]
Awesome!  Thanks!
