### ISSUE TITLE
Ability to create profiles

### ISSUE THREAD

**Issue by vicb** [Thibaut/devdocs#44]
It would be great to be able to create profiles, ie "frontend", "backend" each having different settings (available languages/tools).

This implies supporting login, using GH login could be great.

Lastly I want to thank you for this app, really **great** !

**Comment by Thibaut** [comment]
Adding user profiles would introduce too much complexity for a small benefit IMO. DevDocs already makes it quick & easy to search a single doc (with the `tab` shortcut,) and I'd rather avoid server-side state (login) at this time.
