### ISSUE TITLE
Force offline mode

### ISSUE THREAD

**Issue by llagerlof** [Thibaut/devdocs#441]
Sometimes my Internet is unusable (however, tecnically, I have Internet) but DevDocs identify it and try to load the "http://devdocs.io/offline", online, and fails because, you know, slow Internet.

Would be very good if you can "force" the full offline mode even if you have a valid Internet connection.

Thanks.

**Comment by Thibaut** [comment]
Open http://devdocs.io/ instead. Paths other than the root make a request to DevDocs's server before launching the app. The root path boots from cache, though, so even on a slow connection it will launch the app instantly.
