### ISSUE TITLE
Incorrect link to git quick quick reference pdf

### ISSUE THREAD

**Issue by daavve** [Thibaut/devdocs#445]
The first hyperlink at the very top of http://devdocs.io/git/  

Link on the existing devdocs page: [GitHub Cheat Sheet](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf)  

Link should point to: [GitHub Cheat Sheet](https://services.github.com/kit/downloads/github-git-cheat-sheet.pdf)

Thanks!

-Dave

**Comment by Thibaut** [comment]
Thanks for the bug report. The link is broken on the source site: https://git-scm.com/docs. See https://github.com/git/git-scm.com/pull/770#issuecomment-234726665

**Comment by daavve** [comment]
I submitted a [pull request](https://github.com/git/git-scm.com/pull/814) to try to update the server cache daily.  Hopefully it will fix things.

-Dave
