### ISSUE TITLE
devdocs should move to HTTPS?

### ISSUE THREAD

**Issue by ed-torvalds** [Thibaut/devdocs#446]
I am getting this error message in JavaScript console in Chromium 51.0 (on Linux)

    Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. https://goo.gl/rStTGz

That means in order for devdocs to work in near future in should move to HTTPS

**Comment by Thibaut** [comment]
The app already works over HTTPS: https://devdocs.io

It isn't the default because there are a number of docs that still have insecure images. I'll flip the switch eventually (likely when I implement Service Worker) but for now there's no rush.

**Comment by Thibaut** [comment]
Note: if/when Chrome disables AppCache over HTTP, apps that use it will not break. They just won't load offline anymore.
