### ISSUE TITLE
C++17 documentation

### ISSUE THREAD

**Issue by netheril96** [Thibaut/devdocs#448]
http://en.cppreference.com/w/, which seems to be the source of devdocs' C++ documentation, has been updated with docs on C++17. Please update devdocs with them as well.

**Comment by Thibaut** [comment]
I'm using the offline archive: http://en.cppreference.com/w/Cppreference:Archives which hasn't been updated in a while. I'll see if I can rewrite the scraper to hit the website directly in the coming weeks.
