### ISSUE TITLE
Failure to extract documentation archive files

### ISSUE THREAD

**Issue by scherepn** [Thibaut/devdocs#451]
Attempting to download the docs for `git`, `nginx`, or `redis` results in errors.

    [unix_utils] `gunzip /home/user/devdocs/public/docs/redis.tar.gz` STDERR:
    gzip: /home/user/devdocs/public/docs/redis.tar.gz: unexpected end of file
    [unix_utils] `tar -xf /tmp/... ` STDERR:
    tar: Unexpected EOF in archive
    tar: Unexpected EOF in archive
    tar: Error is not recoverable: exiting now

All three of these docs were just updated. Perhaps the generated tar.gz files were corrupted?

**Comment by Thibaut** [comment]
Weird. I re-uploaded the last batch. Seems to be working now. Thanks for the bug report.
