### ISSUE TITLE
Clicking to expand language entry when selecting documentation makes the entry open and close quickly.

### ISSUE THREAD

**Issue by ayaz** [Thibaut/devdocs#452]
There's a slight bug I noticed on Chrome on Linux when accessing this over devdocs.io. When selecting documentation, if the language entry is nested, clicking to expand the entry causes the entry to open for a split second and then collapse again. I have to click, hold, move the mouse around and then release for the entry to remain expanded.

**Comment by Thibaut** [comment]
Thanks for the bug report!
