### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_file_s_rename

### ISSUE THREAD

**Issue by AdnaneX** [Thibaut/devdocs#457]
> thor docs:download --default

![error](https://cloud.githubusercontent.com/assets/11260121/17582869/e1e663e6-5fa5-11e6-8734-a1e21254fd3d.png)

**Comment by Thibaut** [comment]
I just pushed a commit that may fix this. Could you pull the repo and try again.

**Comment by AdnaneX** [comment]
i have this error this time
![error2](https://cloud.githubusercontent.com/assets/11260121/17659425/47e5e17c-62ca-11e6-91ac-20d479f49ce0.png)

**Comment by Thibaut** [comment]
Try installing http://gnuwin32.sourceforge.net/packages/gzip.htm

If that doesn't work, use https://www.cygwin.com/ instead of the default shell.
