### ISSUE TITLE
Dom Events not loading fully

### ISSUE THREAD

**Issue by kcolford** [Thibaut/devdocs#460]
Even after reloading/refreshing and making sure I was online, I still got this:

![devdocs - dom events 2f dblclick](https://cloud.githubusercontent.com/assets/5855407/17777200/9982e43e-652d-11e6-812e-52c9dbccb0cc.png)

**Comment by Thibaut** [comment]
Could you open the dev tools, load that page, and post screenshots of the console and network tabs please.
