### ISSUE TITLE
D3.js update

### ISSUE THREAD

**Issue by 1oglop1** [Thibaut/devdocs#462]
https://github.com/d3/d3/wiki/API-Reference - this page has been moved and serves as crossroads between v4 and v3
May I suggest support of both versions v3 and v4?
right links are:
V4: https://github.com/d3/d3/blob/master/API.md
v3: https://github.com/d3/d3-3.x-api-reference/blob/master/API-Reference.md

maybe you can use page to map also changes if needed.

**Comment by Thibaut** [comment]
See https://trello.com/c/2B0hmW7M/52-request-updates-here#comment-57af45cdfc02bf35a7b7cee0
