### ISSUE TITLE
JavaScript Installation Error

### ISSUE THREAD

**Issue by Ogejoh** [Thibaut/devdocs#466]
I Get An Error Trying To Install JavaS
![javascript installation error](https://cloud.githubusercontent.com/assets/17549503/17932592/63a7b52e-6a19-11e6-8dad-61627abb851c.png)
cript Documentation.

**Comment by Thibaut** [comment]
Could you open the dev tools (before clicking Install) and post screenshots of the console and network tabs after you click Install please.
