### ISSUE TITLE
Add .net Core documentation

### ISSUE THREAD

**Issue by cmaneu** [Thibaut/devdocs#467]
We should add .net Core documentation to devdocs.
Online source: 
- [https://docs.microsoft.com/en-us/dotnet/articles/welcome](https://docs.microsoft.com/en-us/dotnet/articles/welcome)
- [https://docs.microsoft.com/en-us/dotnet/core/api/index](https://docs.microsoft.com/en-us/dotnet/core/api/index)

_Note:_ This issue is more or less a reminder to a future myself to try to create the appropriate UrlScraper subclass to do the job. Meanwhile, if someone has the energy to do this, we can coordinate our efforts.

**Comment by Thibaut** [comment]
See https://github.com/dotnet/core-docs/issues/397. At the moment the .NET API docs can't be added because they're not released under an open-source compatible license.

"To-be-added" docs are tracked on https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by sbrl** [comment]
The .NET API is now available under CC-BY-SA, as far as I understand it. Source: https://github.com/dotnet/dotnet-api-docs/blob/master/LICENSE

**Comment by NN---** [comment]
@Thibaut Does it have compatible license today ?

**Comment by j-f1** [comment]
Yep! Here’s the card: https://trello.com/c/IvJ01rkw/285-net-core
