### ISSUE TITLE
Add ASP.net Core documentation

### ISSUE THREAD

**Issue by cmaneu** [Thibaut/devdocs#468]
We should add ASP.net Core documentation to devdocs.
Online source: [https://docs.asp.net/en/latest/](https://docs.asp.net/en/latest/)

_Note:_ This issue is more or less a reminder to a future myself to try to create the appropriate UrlScraper subclass to do the job. Meanwhile, if someone has the energy to do this, we can coordinate our efforts.

**Comment by Thibaut** [comment]
"To-be-added" docs are tracked on https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by YohansHailu** [comment]
is it added now then?
