### ISSUE TITLE
Abbreviation suggestions: TensorFlow & NumPy

### ISSUE THREAD

**Issue by albertaparicio** [Thibaut/devdocs#470]
I have a suggestion for two abbreviations.

The first one is 'tf' for TensorFlow. I suggest this abbreviation, as it is the main one used in its API.

The second one is 'np' for NumPy. This package is usually abbreviated in this manner when imported into Python.

**Comment by Thibaut** [comment]
Thanks for the suggestion. I'll add those soon.
