### ISSUE TITLE
Electron Docs

### ISSUE THREAD

**Issue by jasondavis** [Thibaut/devdocs#479]
Could someone add Electron Docs?

**Electron**
http://electron.atom.io/

> Build cross platform desktop apps
> with JavaScript, HTML, and CSS

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation
