### ISSUE TITLE
Add a feature to export list of documentation

### ISSUE THREAD

**Issue by axelson** [Thibaut/devdocs#483]
Currently if you want to keep your documentation synced across multiple computers you have to manually add and remove documentation. It would be nice to be able to export a simple json file of the documentation.

While this would mostly be solved by #336 this is a different use-case.

**Comment by Thibaut** [comment]
All settings, including the selection of docs, are stored in cookies. Have you looked into extensions that synchronize cookies? (Firefox and Chrome also have built-in sync that can do this)
