### ISSUE TITLE
Pug support

### ISSUE THREAD

**Issue by FieryCod** [Thibaut/devdocs#485]
Big thanks for your work, the only thing which is missing are the pug docs. Is there any plan in the near future to add them to the devdocs?
https://pugjs.org/api/getting-started.html

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation
