### ISSUE TITLE
Mercurial (hg) docs

### ISSUE THREAD

**Issue by kirbo** [Thibaut/devdocs#487]
Don't know if this is the right place to ask, but I hope you redirect this to the right place: 

There are no Mercurial (hg) SCM documentations:
https://en.wikipedia.org/wiki/Mercurial

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation
