### ISSUE TITLE
provide "ts" abbreviation for typescript search

### ISSUE THREAD

**Issue by orionlee** [Thibaut/devdocs#490]
I'd love to see "ts" added as abbreviation for searching typescript doc.  Thoughts?

Thanks.

**Comment by orionlee** [comment]
@Thibaut Thanks!  

BTW, before the commit was made, I tried to hack it using DevTools to add the aliases by 
```
app.models.Entry.ALIASES["typescript"] = "ts";
```
But it had no effect.

**Comment by Thibaut** [comment]
You're welcome 👍 

> But it had no effect. 

That's because the aliases are applied on load (one of many techniques to make the search as fast as possible).
