### ISSUE TITLE
 point browser at localhost:9292 gets 102: the connection rejected

### ISSUE THREAD

**Issue by GLJay** [Thibaut/devdocs#492]
The installabtion is succeed on centos 6 . It can run suceessfully and it's ok when running the test command.  But it gets 102: the connection rejected when point browser at localhost:9292. And I check the port and selinux, there is nothing wrong. I can't find out the problem.

**Comment by Thibaut** [comment]
This sounds like a configuration issue on your end — not a bug in DevDocs. I recommend searching/asking on StackOverflow (DevDocs uses Sinatra/Rack + thin server).
