### ISSUE TITLE
Page scroll via keys

### ISSUE THREAD

**Issue by MartinMuzatko** [Thibaut/devdocs#495]
Hello there! 

Thank you for this awesome platform of documentations!

I'm really used to scroll pages via my arrow keys, so I expect this behavior on pretty any page. especially on documentation.

I understand that arrow keys are used for the sidebar, since you want to quickly get to your search results, whenever you type something.

**My suggestion:**
Instead of changing the default user experience for navigating through content to shift+arrowkey, I would only add eventhandlers for the results after something has been searched. Otherwise - when do you need to quickly navigate through pages other than the search results?

So maybe on Enter/Blur - we could switch back to navigate content rather than page items.

Please let me know what your thoughts are.

**Comment by Thibaut** [comment]
Hi - thanks for the feedback.

The arrow keys are also used to navigate the hierarchy of docs/categories/classes,functions,etc in the sidebar — not just for the search results. I think it's best to keep the behavior of the arrow keys consistent throughout the app. 

Would https://github.com/Thibaut/devdocs/issues/296 work for you? I've been meaning to work on it but it's hard to find the time these days, especially with all the new/updated docs…

**Comment by MartinMuzatko** [comment]
Yes! Thanks @Thibaut
