### ISSUE TITLE
Add docs for Pyramid (Python web framework)

### ISSUE THREAD

**Issue by davidblewett** [Thibaut/devdocs#503]
The published documentation is at http://docs.pylonsproject.org/en/latest/docs/pyramid.html . Project site is https://trypyramid.com/ and GitHub repo is https://github.com/Pylons/pyramid . 

Let me know if you need help; I can try to run the scraper on the generated docs for you.

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation

> I can try to run the scraper on the generated docs for you.

Contributions are welcome 👍
