### ISSUE TITLE
Feature Request: option to view original markup/style

### ISSUE THREAD

**Issue by chrisv2** [Thibaut/devdocs#507]
Really cool project, but trying to use it for a day now I find that I would really much prefer reading the docs in their original markup and style. For example, Bootstrap docs are just not that useful if the visual examples get stripped.

Would it be possible to have such an option?

**Comment by Thibaut** [comment]
Unfortunately no. Using the original markup and style means importing the CSS & JS of the source, which is going to conflict with the app and between docs. So then you have to load the doc content in an iframe, which would make the app significantly slower (having to load all these extra assets), harder to use (things like scrolling, focus, etc.), and harder to maintain. Also offline mode wouldn't work.
