### ISSUE TITLE
Offline is unavailable on Firefox

### ISSUE THREAD

**Issue by krampstudio** [Thibaut/devdocs#508]
Offline mode used to work with devdocs, but since a few time it says IndexedDB is unavailable. 
I'm not running in private browsing mode, allowed the storage. See the screenshot 

![selection_145](https://cloud.githubusercontent.com/assets/468620/19262935/f1afb6fa-8f99-11e6-934a-f17898252e01.png)

**Comment by krampstudio** [comment]
Seems somehow related to my firefox profile...

**Comment by sunng87** [comment]
I'm having the same issue. May I know how did you fix it? @krampstudio

**Comment by krampstudio** [comment]
@sunng87 I've created a clean profile

**Comment by edouard-lopez** [comment]
Is there another solution, other than atomizing my profile?
