### ISSUE TITLE
Open the corresponding web page on a different tab

### ISSUE THREAD

**Issue by danse** [Thibaut/devdocs#510]
First let me say that this project is awesome, and thanks for giving it to us!

I am thinking of a new feature which shouldn't be hard to build in a general way, the problem could mainly be to fit it in the overall experience.

Often i use Devdocs for checking quickly some assumptions or getting more info about a topic, and i am satisfied by the answers i find within the app. In a few other cases, though, i feel the need to deepen more, or to see the information in its context, or to use decorative info (style, dynamic panels) which was stripped out in the Devdocs version. Other times i want to send the link to the related doc to someone, and i know that the original page has more detailed anchors than the Devdoc version.

For all these reasons, i wish that there was a way to open the current Devdocs page, from its original source, in a new tab. I wish i had a button or a keyboard shortcut for that. In asking for this i am assuming that most docs have a web counterpart and i might be wrong about this, but the button or the shortcut might be missing or disabled when this is not the case.

Pedantic description of the use case:
- The user navigates to Devdocs
- They search for a keyword, for example `input`, and they find [the related page](http://devdocs.io/dom_events/input)
- They now click on a button, or use a keyboard shortcut, to open the original page from `developer.mozilla.org` in a new tab

What do you think about this feature?

Thanks again for this amazing tool!

**Comment by danse** [comment]
This might be related to #507

**Comment by danse** [comment]
Just a note. I assumed that this was easy, because i've got the feeling that in many cases the metadata about the location of the original page is already there. I might be wrong about this

**Comment by japborst** [comment]
@danse you do know that the URL to the original docs is at the bottom, right? Not very sure what the difference is compared to your use case

**Comment by Thibaut** [comment]
Yes there is already a link to the original page at the bottom of every page.

We could add a keyboard shortcut to open the original page in a new tab? (e.g. `alt + o`)

**Comment by danse** [comment]
Hey, good to know! I remember to have used that link at times but eventually i forgot about it. Some pages are very long. I would be up to make that resource more accessible either with a shortcut or by moving the link to a different area with fixed positioning

**Comment by danse** [comment]
Awesome :sunglasses:
