### ISSUE TITLE
Inject current search library to the chrome console env

### ISSUE THREAD

**Issue by zhea55** [Thibaut/devdocs#512]
I use devdocs search lodash methods

but i usually write test method in the console.

The offical lodash document inject lodash as _ variable, so i can use in chrome console.

Could you add this feature?

**Comment by Thibaut** [comment]
There are multiple versions of lodash, in addition to underscore.js. We can't inject all of them + I think this goes beyond the scope of DevDocs (which is about documentation). Injecting libraries in DevDocs may lead to conflicts, bugs, and slow down the app.
