### ISSUE TITLE
Some links in DOM documentation not pointed to offline doc

### ISSUE THREAD

**Issue by orionlee** [Thibaut/devdocs#514]
Example:
For DOM Events article:
  http://devdocs.io/dom_events/

The link to Event API points to
  https://developer.mozilla.org/en-US/docs/Web/API/Event
rather than the offline version:
  http://devdocs.io/dom/event

It'd be great if these links point to offline version.

**Comment by Thibaut** [comment]
Duplicate #234. Not an easy thing to fix because docs are generated in isolation.
