### ISSUE TITLE
Wrong page shown

### ISSUE THREAD

**Issue by code-tree** [Thibaut/devdocs#516]
![image](https://cloud.githubusercontent.com/assets/11289719/19633620/da1c9dde-99dd-11e6-8bfc-84614a79577a.png)

Page on Nginx slice module shown instead of JS array slice.

**Comment by code-tree** [comment]
I just came across another one of these.

![image](https://cloud.githubusercontent.com/assets/11289719/19714072/8b3f652c-9b75-11e6-87c6-83ef1036aeee.png)


Xpath concat is shown instead of JS array concat

**Comment by Thibaut** [comment]
Hmm this is very weird. No one else has reported a similar issue (those pages work for me).

Could you post screenshots of the console and network tabs in the dev tools, after you've open a broken page, please? (open the dev tool before opening the page so the browser is logging activity)

**Comment by code-tree** [comment]
I just tried to capture those results, but dev tools triggered a clear of the App Cache, and now it seems to be working fine. I'll let you know if I encounter it again.

**Comment by Thibaut** [comment]
👍
