### ISSUE TITLE
Disable keyboard shortcuts

### ISSUE THREAD

**Issue by mMontu** [Thibaut/devdocs#517]
Is there a way to optionally disable the default keyboard shortcuts? I'm facing a problem similar to #77, because I'm using [Pentadactyl](http://5digits.org/pentadactyl/index), which provides Vim-like shortcuts that are clashing with the page shortcuts.

Specifically I'm facing problems when I perform a search on the page contents:
- `/` : open the search line (similar to Vim)
- `<pattern>`: enter a pattern to search
- `<cr>`: end the input, jump to the first result

The problem is that when the <kbd>Enter</kbd> (last step above) is hit the cursor moves to search box (on the top left of the page). I've played with some Pentadactyl `:map` commands in order to change the behavior of `<cr>` when browsing http://devdocs.io/ but no luck so far.

The help at http://devdocs.io/help mentions that it is possible to select options through the URL:

```
devdocs.io/#q=js date. 
```

It would be nice if I could disable the keyboard shortcuts on the URL as well:

```
devdocs.io/#no_short_q=js date. 
```

**Comment by Thibaut** [comment]
I think this is very much an edge case / not something that most people need, so I'm a bit reluctant to make it a feature. You can disable keyboard shortcuts after the app has loaded by running `app.shortcuts.stop()`, which you could automate using something like Greasemonkey. Does that address your use-case?

**Comment by mMontu** [comment]
This is probably an issue for every Vimperator/Pentadactyl user, but I have no idea how many people use it, so maybe it is an edge case used for too few people.

To be honest I was hopping for a simpler solution, because I don't know Greasemonkey and it seems an overkill to install another extension in order to disable a shortcut in a single site (and hope this doesn't mess with Pentadactyl).

If this kind of issue should be handled by the user them it is probably better to solve it directly on Pentadactyl, as it has several options and mappings for keys. Those options/mappings allowed to solve similar issues in several other sites; I'm having some trouble here because the shortcut involves the <kbd>Enter</kbd> key, so remapping it to <nop> disables the default shortcut but also prevents the search in Pentadactyl (because search & commands are delimited by the <kbd>Enter</kbd>).

As I've run out of ideas to make this work using mappings, I've tried to use your suggestion of calling the javascript code you mentioned. Pentadactyl [provides a function to execute javascript](http://5digits.org/help/pentadactyl/eval.xhtml#:js), and based [on an example at superuser](http://superuser.com/questions/891648/) I tested this:

     :js content.wrappedJSObject.app.shortcuts.stop()

This stopped the shortcuts when browsing the page, but for some reason it is still triggered when finishing the search on Pentadactyl's search line. I'm wondering if the command above is entered on one frame, and the search triggers the shortcut in a different frame. Is there any other javascript call that disables the shortcuts more globally/forcefully?

**Comment by Thibaut** [comment]
> Is there any javascript call that disables the shortcuts more globally/forcefully?

`app.shortcuts.stop()` forcefully disables all keyboard shortcuts, but if the app hasn't finished loading yet, then those shortcuts will be re-enabled as part of the loading process. Is there an option in Pentadactyl to run some JavaScript only once the page has finished loading?

**Comment by mMontu** [comment]
Yes, I think there is a way to do that in Pentadactyl. But the test I reported was manual (waited the page load and them typed the command), so I think we have another problem here.

**Comment by Thibaut** [comment]
I've given this more thought and decided not to add a setting to disable all shortcuts, since only a handful of users would use it, and it might be confusing / the wrong solution to other users' problems.

**Comment by mMontu** [comment]
For some reason everything just works now. As I've been away from the site I don't know exactly when it started working. Thanks!

**Comment by lifeike** [comment]
alt+d is what I used for highlighting address bar. can you free alt+d shortcut ?  hopefully......................................
😆

**Comment by lifeike** [comment]
Hi Thibaut,

I have found the way to solve this problem. please notify all users in this page if you can.

1.install chrome extension: shortkeys
2.configure disable shortcuts in this extension
3.chrome extension mangement page --> shortkeys --> details --> permission on specific pages
4.paste devdocs url there, so that this extension will only applid on devdocs.io

best luck guys
