### ISSUE TITLE
Suggest to add account feature, so that it can sync the data.

### ISSUE THREAD

**Issue by mrdulin** [Thibaut/devdocs#518]
Does it save library enabled data in localStorage?

**Comment by FelixRilling** [comment]
I'm pretty sure the enabled docs are saved in an IndexedDB:
![devdocs](https://cloud.githubusercontent.com/assets/3207763/19766540/d9ee3de0-9c4e-11e6-85af-8d7a5d75de1d.png)

**Comment by mrdulin** [comment]
@FelixRilling `IndexDB`, amazing! But when I clear storage, It seems my data will be clear. I have to enabled each library again. So I want to sync my data in cloud.

**Comment by Thibaut** [comment]
All settings (selection of docs, color scheme, etc.) are stored in cookies. Firefox and Chrome have built-in sync that can synchronize cookies. There's also a number of browser extensions that can do this. Just use one of those and you'll be all set.

IndexedDB is only used for the offline data, which is kept up-to-date automatically. It's not something that can be synced (it already syncs with DevDocs's servers). See also https://github.com/Thibaut/devdocs/issues/336.

**Comment by lnunno** [comment]
If anyone is looking for a similar feature I've created a gist that automates this when entered into the terminal: https://gist.github.com/lnunno/f660727369fd4869efeee5bc9f1add5b

**Comment by Thibaut** [comment]
@lnunno in case you missed it, I recently added the ability to export/import settings: http://devdocs.io/settings

**Comment by lnunno** [comment]
@Thibaut Ah thanks, didn't realize the enabled docsets were included in this.
