### ISSUE TITLE
Option to add pages as Favorites

### ISSUE THREAD

**Issue by dkjain** [Thibaut/devdocs#521]
Hi,

It would be great if there is an option to mark or add pages as **favorites** (to offline docs) for quick access. Just like you would find in Microsoft chm files.

![image](https://cloud.githubusercontent.com/assets/10743577/19769467/1f67027e-9c79-11e6-8e7e-6f41b4184e35.png)

**Comment by Thibaut** [comment]
Thanks for the feedback. I think this goes beyond the scope of DevDocs + isn't something that most people would use. Browsers already handle bookmarks pretty well and there are lots of extensions for doing this kind of stuff.
