### ISSUE TITLE
Link to JS types from Node.js documentation

### ISSUE THREAD

**Issue by borekb** [Thibaut/devdocs#524]
Currently, on a page like http://devdocs.io/node/path#path_path_join_paths, if I click the "String" JavaScript type, it takes me to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type. It would be better if it could jump, internally, to http://devdocs.io/javascript/global_objects/string. Not sure if it's possible but would be helpful.

BTW DevDocs is amazing! <3

**Comment by Thibaut** [comment]
See https://github.com/Thibaut/devdocs/issues/234 
Unfortunately it's not an easy thing to do because docs are generated in isolation.

Thanks for the feedback!

**Comment by borekb** [comment]
Oh, I missed that issued (despite searching!).

Just a thought, could it be intercepted on the client-side / in JavaScript somehow?

**Comment by Thibaut** [comment]
The JS doesn't know which links / external URLs are available inside DevDocs. This is all done server-side when scrapping the docs. Links that should open inside the app are rewritten to be relative paths; external links are rewritten to be absolute URLs.
