### ISSUE TITLE
URL color template dark mode

### ISSUE THREAD

**Issue by lshaf** [Thibaut/devdocs#528]
Can you please change URL color when in dark mode?
because blue with dark background is so hard to read.
![image](https://cloud.githubusercontent.com/assets/4636265/20047425/cf2b9100-a4e6-11e6-9a7c-cf86f0caec43.png)

**Comment by Thibaut** [comment]
Could you post a link to that page? The issue isn't with links (in dark more they use the same text color but with an underline). It's the PHP documentation that has hard-coded colors on certain elements.

**Comment by lshaf** [comment]
Here http://devdocs.io/yii~2.0/yii-helpers-basearrayhelper :smile:

**Comment by lshaf** [comment]
so no changes for URL color?

**Comment by lshaf** [comment]
Ohh, I just uninstall it and install it again to fix the problem.
thanks 😄
