### ISSUE TITLE
Shortcuts for back/forward clash with text navigation shortcuts in search field

### ISSUE THREAD

**Issue by DMRobertson** [Thibaut/devdocs#529]
I think this issue is a Linux version of #51.

The current keyboard shortcuts for navigating forward and back are `Control-Left` and `Control-Right`. Unfortunately I've got into the habit of using these keybindings in Chrome (53) on Linux (Ubuntu 14.04) to navigate to the start or end of a word in a text box, such as the main search field. It's a bit frustrating when I mean to focus the cursor at the start of the field but instead go back to the previous page! I'm not sure if this a GNOME convention or something that's used in general across multiple desktop environments.

[Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_navigation), [Chrome](https://support.google.com/chrome/answer/157179?hl=en-GB), [IE 11](https://support.microsoft.com/en-gb/help/15357/windows-internet-explorer-11-keyboard-shortcuts) and [Edge](https://support.microsoft.com/en-us/help/13805/windows-keyboard-shortcuts-in-apps) already use `Alt-Left` and `Alt-Right` for forward/back; [Opera](http://help.opera.com/Linux/9.50/en/keyboard.html) apparently uses either `Alt-` or `Control-` in combination with `Left` and `Right`. I'm not a Mac user, but (in the interest of completeness) the forward/back word shortcuts are apparently [`Option-Left` and `Option-Right`](https://support.apple.com/en-gb/HT201236) and Safari's back/forward page shortcuts are [`Command-[` and `Command-]`](https://www.domainit.com/tools/mac-shortcuts.mhtml).

Maybe devdocs should use `Alt-Direction' for navigation? Or perhaps don't listen for page forward/back shortcuts when the search box is focused?

**Comment by Thibaut** [comment]
Sorry for the delay. I made it so the keyboard shortcut for back/forward is `Alt+Left/Right` on all platforms but Mac.
