### ISSUE TITLE
Feature req: get everything offline

### ISSUE THREAD

**Issue by NKjoep** [Thibaut/devdocs#531]
Happens to me to switch browser / computer multiple times day or week.

It would be handy to have a "select all" or "save all" docs for the offline navigation.
This will save me when I forget to download something.

What do you guys think?

**Comment by Thibaut** [comment]
See my reply to https://github.com/Thibaut/devdocs/issues/518#issuecomment-257185106 on synchronizing settings/docs between browsers.

Regarding offline data: #336 is somewhat related.

I would not recommend enabling all the documentations. There's something like half a million search entries in all the docs on DevDocs at this point (100k+ files / 500MB+). If you enable them all, the search will probably slow to a crawl.

Alternatively you could run DevDocs locally (and download all the docs locally, but not enable them in the app).
