### ISSUE TITLE
Provide option to change keyboard shortcuts

### ISSUE THREAD

**Issue by dkjain** [Thibaut/devdocs#533]
Hi,

Anyway to change / disable the Alt + arrow down/up shortcut to navigate right panel. Basically it's inconvenient to use both the hands when this can be operated single handedly.

If not possible in current repo, will you consider this for future releases.

thanks
dkj

**Comment by Thibaut** [comment]
Duplicate of https://github.com/Thibaut/devdocs/issues/296.

**Comment by saleo** [comment]
would greatly appreciate if this can be implemented, thx a lot
