### ISSUE TITLE
Ansible 2.2.0 documentation

### ISSUE THREAD

**Issue by jurgenhaas** [Thibaut/devdocs#534]
Ansible has been updated a couple of months ago and I wonder what's required to get the latest documentation into devdocs.io - is that a manual process or do you have to trigger something that's reading the documentation in?

**Comment by kevgathuku** [comment]
I also noticed the Haskell docs on devdocs are a bit behind the latest version. 
Please share a solution when you figure out how the process works.

**Comment by Thibaut** [comment]
The scraping is (mostly) automated but the updates are a manual process. You can ask [here](https://trello.com/c/2B0hmW7M/52-request-updates-here) when I forget. Both updates are done.
