### ISSUE TITLE
Devdocs on chrome fails to load css styles.

### ISSUE THREAD

**Issue by mugash** [Thibaut/devdocs#536]
Can someone please help...Devdocs failed to load css styles after an update.
On chrome Version 54.0.2840.100

![devdocs](https://cloud.githubusercontent.com/assets/12526580/20599819/6294ef9a-b261-11e6-8d9b-c7c505d871b8.png)
This is how it looks

**Comment by Thibaut** [comment]
Could you post a screenshot of the Network tab of the Dev Tools please (open the tools before loading the app).

**Comment by mugash** [comment]
I checked today and it is working ok now
