### ISSUE TITLE
Keyboard shortcut to focus the search box

### ISSUE THREAD

**Issue by maciel310** [Thibaut/devdocs#542]
A keyboard shortcut to focus the search box would be really handy. The most common keyboard shortcut I've seen for this is the forward slash character: /

**Comment by Thibaut** [comment]
Thanks for the feedback. Hitting any "letter" key (i.e. typing a new search) or backspace automatically re-focuses the search box, but you're right that `/` is usually a shortcut for search, so I added that as well.

**Comment by maciel310** [comment]
Thanks! I'd actually seen that in the documentation but it wasn't working for me (Chromebook Pixel 2 v54), so thought it might have been removed at some point. The / character will be great for my muscle memory though :)
