### ISSUE TITLE
Add https://www.terraform.io/docs/index.html docs

### ISSUE THREAD

**Issue by redbaron** [Thibaut/devdocs#543]
Having Ansible is very handy,but if we had Terraform docs it would be awesome

**Comment by edno** [comment]
You should use the [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation) for this request as per the [contribution guidelines](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations).
