### ISSUE TITLE
Protected emails instead of packages in Yarn documentation

### ISSUE THREAD

**Issue by calebmer** [Thibaut/devdocs#545]
Thanks for the amazing project!

Currently, in the Yarn documentation, it would appear that the phrase `[email protected]` appears wherever there is a package name and version number. So instead of `jest-cli@16.0.1` one would instead see `[email protected]`.

Example DevDocs rendering: http://devdocs.io/yarn/cli/upgrade
Yarn source rendering: https://yarnpkg.com/en/docs/cli/upgrade

It would appear as if Yarn’s webhost is inserting the `[email protected]` to protect against spam and then replacing the phrase with the package name and versions with JavaScript.

**Comment by Thibaut** [comment]
Thanks for the bug report!
