### ISSUE TITLE
jQuery docs are missing some /category/ pages

### ISSUE THREAD

**Issue by monk-time** [Thibaut/devdocs#548]
I was browsing jQuery docs and noticed that some entries link to pages that are not in devdocs ([example](http://devdocs.io/jquery/types#Event), this link is missing: *"properties are all documented, and accompanied by examples, on the [Event object](https://api.jquery.com/category/events/event-object/) page."*). This seems to be caused by the scraper [excluding all /category/ pages](https://github.com/Thibaut/devdocs/blob/193db39f9b2f79ca439231b90ffea32ef33f02ae/lib/docs/scrapers/jquery/jquery.rb#L11), and while I agree that most of them are only useless indexes, some also have bits or whole pages of useful documentation that can't be found via devdocs:

[Event Object](https://api.jquery.com/category/events/event-object/), [Attribute](https://api.jquery.com/category/selectors/attribute-selectors/), [Deferred Object](https://api.jquery.com/category/deferred-object/), [Manipulation](https://api.jquery.com/category/manipulation/), [Selectors](https://api.jquery.com/category/selectors/), [Global Ajax Event Handlers](https://api.jquery.com/category/ajax/global-ajax-event-handlers/), [jQuery Extensions](https://api.jquery.com/category/selectors/jquery-selector-extensions/).

**Comment by Thibaut** [comment]
Added. Thanks for the feedback.
