### ISSUE TITLE
Node.js docs links to MDN (for JavaScript types) should really be rewritten to point back to the corresponding DevDocs JS article

### ISSUE THREAD

**Issue by isiahmeadows** [Thibaut/devdocs#549]
This may or may not also apply to others (basically, links to one library's documentation being rewritten to the DevDocs equivalent), but it's very highly prevalent across all of Node's documentation, and has been for years. Any chance this could be fixed?

**Comment by Thibaut** [comment]
See #234. Unfortunately it's not an easy thing to do because docs are generated in isolation.
