### ISSUE TITLE
Rust Documentation Examples "Run"

### ISSUE THREAD

**Issue by Viomi** [Thibaut/devdocs#550]
In almost all the code examples, on https://doc.rust-lang.org/nightly/book/loops.html, there's a little "run" button on the right side.

In devdocs, this just shows up as text at the end of the codeblock that says "Run".

Assuming this would be fixed in https://github.com/Thibaut/devdocs/blob/master/lib/docs/scrapers/rust.rb

**Comment by Thibaut** [comment]
Thanks for the bug report.
