### ISSUE TITLE
Make Webpage Responsive for mobile-view

### ISSUE THREAD

**Issue by xstable** [Thibaut/devdocs#551]
Please make Webpage http://devdocs.io/ Responsive for mobile-view.

BTW: What means the section "Disabled". A short explaination why those docs are disabled would be fine at the page.

**Comment by Thibaut** [comment]
> Please make Webpage http://devdocs.io/ Responsive for mobile-view.

Could you provide an example of when devdocs.io is not responsive for you? (device, browser, etc.) DevDocs has a mobile-optimized version that should automatically kick in on mobile devices.

>  What means the section "Disabled". A short explaination why those docs are disabled would be fine at the page.

Step 1 of the introduction message gives a hint:

> To enable more docs, click Select documentation in the bottom left corner 

Then I would expect it's pretty obvious why not all docs are enabled all the time. It's up to you to choose your selection.
