### ISSUE TITLE
There is multiple 'amp' in lodash 4 escape example.

### ISSUE THREAD

**Issue by zjkhan713** [Thibaut/devdocs#552]
Actual: 
`_.escape('fred, barney, & pebbles');`
// => 'fred, barney, &ampamp; pebbles'
Expected:
`_.escape('fred, barney, & pebbles');`
// => 'fred, barney, &amp; pebbles'

Please find below the link to the docs:
http://devdocs.io/lodash~4/index#escape

**Comment by Thibaut** [comment]
Thanks for the bug report.
