### ISSUE TITLE
Question: Offline installation.

### ISSUE THREAD

**Issue by gviligvili** [Thibaut/devdocs#554]
Hey, I have a situation which where I work the computers are protected and are not connected to the internet.  
They are all windows.

Is there a way I can download all the needed docs in a computer which connected to the internet and then just transfer it "as is" to other computers?

Thanks!

**Comment by Thibaut** [comment]
Hey - You can run DevDocs locally (see instructions in the README), but the setup requires an internet connection. To do what you want, I think you'll need to create a Docker container or VM that you can transfer to your other computer and run without any setup. Unfortunately I don't know enough about Docker/VM/Windows to help with that.
