### ISSUE TITLE
Rails RDOC_MAIN & AbstractController URLs

### ISSUE THREAD

**Issue by aoozdemir** [Thibaut/devdocs#555]
AbstractController URLs are currently, http://devdocs.io/rails~4.2/abstractcontroller and http://devdocs.io/rails~5.0/abstractcontroller
These should be, http://devdocs.io/rails~4.2-abstractcontroller/ and http://devdocs.io/rails~5.0-abstractcontroller/

Also, RDOC_MAIN URLs are http://devdocs.io/rails~5.0/railties/rdoc_main_rdoc & http://devdocs.io/rails~4.2/railties/rdoc_main_rdoc
But I couldn't find the working URLs.

**Comment by Thibaut** [comment]
Thanks for the bug report. These URLs are being ignored by the scraper/generator because they have no content (or in the case `RDOC_MAIN`, the content is not useful / API related). I've fixed what was causing these URLs to incorrectly show up on the root page (e.g. http://devdocs.io/rails~5.0/).
