### ISSUE TITLE
Parsing error on the python::regex page

### ISSUE THREAD

**Issue by math2001** [Thibaut/devdocs#563]
Hello!

There's a parsing error on this page: <http://devdocs.io/python~3.5/library/re>

Search for `negative lookbehind assertion`. Just above, the code has been edited:

![image](https://cloud.githubusercontent.com/assets/15224242/21597767/324f9bca-d1a4-11e6-8e33-759ce95ce05c.png)

![image](https://cloud.githubusercontent.com/assets/15224242/21597772/4af4c79a-d1a4-11e6-9a16-0967543b7b38.png)

I'm using chrome, on windows. Same on firefox. 

Thanks for devdocs anyway!

Matt

**Comment by Thibaut** [comment]
Fixed. Thanks for the bug report.
