### ISSUE TITLE
Option to download/send to kindle

### ISSUE THREAD

**Issue by jrenton** [Thibaut/devdocs#568]
Being able to view docs offline on a Kindle is a great way to learn with less eye strain and you can take it anywhere you go. This should be fairly straight forward with Amazon's command line tool "KindleGen", which can convert an HTML document into a format for Kindle. It is available here: https://www.amazon.com/gp/feature.html?docId=1000765211

**Comment by Thibaut** [comment]
Hey - thanks for the suggestion.

I think this falls a bit outside the scope of this repo/project (web app), and I don't see myself having time to work on such a feature in the foreseeable future, sorry.

I don't think it'd be straightforward, but you're welcome to try and open a PR (or make it a separate repository, which I'd be happy to link to).
