### ISSUE TITLE
Create an API for devdocs

### ISSUE THREAD

**Issue by math2001** [Thibaut/devdocs#571]
Hello!

Devdocs is amazing for docs searching, just as Sublime Text is awesome for writing code. And, here's what I'd like to do: combine both of them, just like it's possible with atom.

Since Sublime Text now supports phantoms which allows it to [display basic html](http://www.sublimetext.com/docs/3/api_reference.html#sublime.Phantom) in the code, it's now very tempting to do a great plugin for ST using devdocs.

The problem is that ST just renders html, know's [very few CSS properties](http://www.sublimetext.com/docs/3/minihtml.html), so, JavaScript is pretty far from being supported. So, I thought there'd be an API like this maybe:

```
api.devdocs.io?language=python%q=str.format
```

that'd give us a `404`, or just the doc for this particular function.

But, it looks like it's not the case... So, would it be possible to build it? Or all the search algorithm are on the client's side?

Thanks for devdocs, and in advance 😉 

Matt

**Comment by Thibaut** [comment]
Hey - thanks!

See #133. An API would require a significant investment in time, maintenance, and hosting costs. I agree it would be useful, but unfortunately I don't have the time to tackle this, as DevDocs is just a side-project of mine.

Currently the search happens entirely client-side, which makes it fast, work offline, and cheap.
