### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by ajsb85** [Thibaut/devdocs#573]
These audits validate the aspects of a Progressive Web App.

[Lighthouse report_ http___devdocs.pdf](https://github.com/Thibaut/devdocs/files/725320/Lighthouse.report_.http___devdocs.pdf)

**Comment by Thibaut** [comment]
This "audit" is mostly incorrect/irrelevant. DevDocs has worked offline and been a "Progressive Web App" since even before the term was coined. Ask the tens of thousands of people that are using it daily :)
