### ISSUE TITLE
Adding Java docs

### ISSUE THREAD

**Issue by y-ates** [Thibaut/devdocs#575]
Hi,

I would like to remember of the issue #103 as Java is still not available.
I would love to see Java in DevDocs.

Thanks in advance.

**Comment by WallenHan** [comment]
eh,eh. now  I must use zeal and devdocs, because of zeal having java doc

**Comment by Ordiel** [comment]
I think **pron** accurately [referenced](https://github.com/Thibaut/devdocs/issues/103) the part of the license where it is stated that redistribution is allowed. And I quote 

**Pron:**

---

    "Except as expressly permitted in your license agreement"

"Redistribution and modification is *[expressly permitted in the license](http://openjdk.java.net/legal/gplv2+ce.html)*."

---

**Comment by minecrawler** [comment]
Please refer to the contribution guidelines for requesting new docs. You just waste your time writing into this issue.... -> https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations

**Comment by Thibaut** [comment]
https://devdocs.io/openjdk~8/
