### ISSUE TITLE
Some Ruby libs are not searchable

### ISSUE THREAD

**Issue by Shoroh** [Thibaut/devdocs#576]
For example — Gem::Command, which is a part of Ruby language.

I couldn't find Gem::Command#merge_options method. Ruby 2.3 and 2.4 are enabled for searching. I tried online and offline ways to search.

**Comment by Thibaut** [comment]
Thanks for the feedback.

The `Gem::*` docs represent ~20% of the Ruby doc (>2k entries). Since I expect most people don't need them, I decided not to include them. Reducing the size of docs helps make the search better.
