### ISSUE TITLE
Mozilla keyword search does not work as advertised

### ISSUE THREAD

**Issue by binki** [Thibaut/devdocs#577]
If I right-click the Search… box, choose “Add a Keyword for this Search…”, set the keyword to something like `dd`, and type `dd JSON.parse` into my address bar, my browser (Firefox or SeaMonkey) navigates to http://devdocs.io/?=JSON.parse which redirects to http://devdocs.io/ and shows me the welcome screen.

I expect the keyword search to perform a search and automatically show the top hit.

The instructions I’m following are in http://devdocs.io/help under “Search using the address bar”.

Is this perhaps because devdocs has at some point changed its URI format? Maybe the search parameters need to be updated for the new format, but redirects to keep from breaking old keyword search configurations would be nice or a redirect to a documentation page showing how to update your configuration would be fine.

**Comment by Thibaut** [comment]
Weird, I just tried this and it works for me. Firefox correctly opens http://devdocs.io/#q=JSON.parse when I type `dd JSON.parse`.

Could you try removing DevDocs in `about:preferences#search` and then adding it again?

Which version of Firefox are you using?

**Comment by binki** [comment]
It doesn’t show up in `about:preferences#search`. When I right-click on the search box and choose “Add a Keyword for this Search”, it opens a bookmark creation dialog. I set `dd` as the keyword in there.

Whenever I type `dd json.parse` and press enter, it appears to navigate to http://devdocs.io?=json.parse , not to http://devdocs.io/#q=json.parse . I’m adding search for the search box, it looks like when I choose “Add a Keyword for this Search” it is inspecting the form. Since the `<input/>` has no `name` attribute, the query string looks like `?=json.parse`. I don’t know how to get Firefox to use the opensearchdescription when adding a keyword for search via the Search `<input/>` via the method described at http://devdocs.io/help which states:

> You can also search from the location bar by following [these instructions](https://support.mozilla.org/en-US/kb/how-search-from-address-bar).

I’m using a community build of Seamonkey-2.48 and FirefoxDeveloperEdition-53.0a2.

**Comment by binki** [comment]
If you need an image to show how I’m adding the keyword search (this time in Firefox-51.0):

![image](https://cloud.githubusercontent.com/assets/82626/22635344/d5906dde-ec00-11e6-8f73-9b611f242a35.png)

**Comment by Thibaut** [comment]
Found the culprit. Thanks for the bug report and investigation!
