### ISSUE TITLE
Many HTTP status code missing

### ISSUE THREAD

**Issue by britishtea** [Thibaut/devdocs#578]
Documentation for many HTTP status codes is missing since 8a59a660cfa836b439071fb0ea8856bc4a0da82f which uses the HTTP documentation on MDN.

[This MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) provides a overview of all HTTP status codes, but does not have a link to a dedicated page for each status code. I think this may be the reason they are missing in Devdocs.

**Comment by Thibaut** [comment]
Thanks for the feedback. This is because not all HTTP codes have been documented on MDN yet, like you said. Hopefully they'll get documented soon. In the meantime you can manually look through the RFCs: http://devdocs.io/http-rfc/. I'll index those again in a future update.
