### ISSUE TITLE
Angular HTTP module docs seem outdated

### ISSUE THREAD

**Issue by gioragutt** [Thibaut/devdocs#581]
[Http Class Doc](http://devdocs.io/angular~2_typescript/api/http/index/http-class)
As an example, I don't think anything still uses HTTP_PROVIDERS publicly

**Comment by Thibaut** [comment]
This is an issue in Angular's documentation, not DevDocs. DevDocs only scrapes content (https://angular.io/docs/ts/latest/api/http/index/Http-class.html).
