### ISSUE TITLE
Feature Request: mysql documentation

### ISSUE THREAD

**Issue by malozaibi** [Thibaut/devdocs#583]
I find your app gigantic, however, I started to learn mysql and can't find a documentation for it.

I don't mean mysql function in php. I wan't the sql flavour that is used by mysql. Things like Foreign key structure , DATE_ADD(), MD5(), etc.

Thank you :)

**Comment by Kaijiro** [comment]
Hey,

First of all : https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations

Please, as it is asked don't post a new issue to ask a new documentation.

Then, you'll see in the Trello board that the MySQL license is incompatible with DevDocs because of their redistribution policy (@Thibaut even asked to Oracle's lawyers).

So, I'm sorry to announce you that the addition of the MySQL documentations is impossible.

**Comment by malozaibi** [comment]
First, I am extremely sorry for that. I am a newbie :) I will try to read first next time.

second, I feel sad because this is impossible.
If MySQL owners are stubborn, how about MariaDB documentation? https://mariadb.com/kb/en/mariadb/documentation/
I actually use MariaDB version of MySQL. 

I repeat. I am sorry. Please delete this feature request after you read my reply :) thank you

**Comment by jadius5** [comment]
Hey, @malozaibi 

First of all: [](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-featuresl)

As it states, search first, someone else might have already requested this same thing.

Also, if you actually acted on @Kaijiro 's comment, you would have checked out the [Trello Board](https://trello.com/b/6BmTulfx/devdocs-documentation), searched for your request, realized it's been voted up about ~287 times, noticed you're not the only one who want's this mariaDB devdoc, and finally saved yourself time and other people's efforts in responding to a second comment. 

This whole feature request you opened was unproductive and distracting.

Sorry for sounding harsh, but I hope a lesson was learned.

**Comment by Thibaut** [comment]
As others said, MySQL can't be added, and MariaDB is on the todo list (contributions welcome). 

Alternatively, most of the SQL language is documented in PostgreSQL's and SQLite's documentations, which are both available on DevDocs.

**Comment by malozaibi** [comment]
Hello, @jadius5 

Thank you for the statement, I have leaned my lesson and weren't harsh. You wanted to help me of course :)

For the trello link, I couldn't open I immediately because trello needs VPN in my country. I checked it later and saw the MariaDB votes. Sorry for the distraction and inconvenience :)

Thank you @Thibaut For the PostgreSQL advise :)
