### ISSUE TITLE
OpenGL docs

### ISSUE THREAD

**Issue by Aborres** [Thibaut/devdocs#586]
Hi I think I would be useful to support the OpenGL documentation inside DevDocs.

https://www.khronos.org/registry/OpenGL-Refpages/gl4/

Thank you!

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation
