### ISSUE TITLE
Search from URL thru specific docs is broken because of Firefox's CSP

### ISSUE THREAD

**Issue by mandx** [Thibaut/devdocs#588]
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src http://devdocs.io 'nonce-devdocs' http://cdn.devdocs.io https://cdn.devdocs.io https://www.google-analytics.com https://secure.gaug.es http://*.jquery.com https://*.jquery.com”). Source: ;(function installGlobalHook(window) {
 ....
```
The sidebar with index for the specific docs loads and search works with the sidebar, but the main content area fails to load:
```
The page failed to load.
It may be missing from the server (try reloading the app) or you could be offline.
If you keep seeing this, you're likely behind a proxy or firewall that blocks cross-domain requests.
Go back · Reload · Retry
```

Going back to the domain only `https://devdocs.io/` works as expected.

I'm using Firefox 52.0a2 (2017-01-24) (64-bit) (Developer Edition) on Linux.

Thanks!

**Comment by mandx** [comment]
Chrome Beta for Linux also complains:
```
> Application Cache Error event: Manifest fetch failed (6) https://devdocs.io/manifest.appcache
> devdocs.io/:1 Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZl…07Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-devdocs' http://cdn.devdocs.io https://cdn.devdocs.io https://www.google-analytics.com https://secure.gaug.es http://*.jquery.com https://*.jquery.com".
```
Apparently is trying to load this script (that came Base64 encoded):
```
(function() {
	// https://developers.google.com/analytics/devguides/collection/analyticsjs/
	var noopfn = function() {
		;
	};
	var noopnullfn = function() {
		return null;
	};
	//
	var Tracker = function() {
		;
	};
	var p = Tracker.prototype;
	p.get = noopfn;
	p.set = noopfn;
	p.send = noopfn;
	//
	var gaName = window.GoogleAnalyticsObject || 'ga';
	var
```

Looks partially downloaded...

**Comment by Thibaut** [comment]
None of these scripts (`Source: ;(function installGlobalHook(window)` and the one above) are from DevDocs. The CSP is doing its job of protecting the app from interference by 3rd-party scripts coming from potentially malicious software and proxies. 

Do you still get the same error? AWS S3 was down at the time you posted, which caused docs to not load in DevDocs.

The CSP errors are unrelated to the actual issue. They're just logging what was blocked, which is actually protecting the app, not breaking it. If you still get the same issue, please post screenshots of the Network tab in the dev tools (open the dev tools before you load the app, to get the full logs).

**Comment by mandx** [comment]
It works now. Confirmed with my laptop and my workstation. I'm closing this, thank you!
