### ISSUE TITLE
Give a choice to user /improvement

### ISSUE THREAD

**Issue by atiqsu** [Thibaut/devdocs#589]
This application saves his data in temporary folder so sometimes it automatically(/by ccleaner) get **deleted** because of users' absent mind. so **_give a choice to user_** to store this documentation files in others drive folder so it did not get automatically deleted.

**Comment by Thibaut** [comment]
This isn't possible, as DevDocs is a web app. Alternatively you could download and run the app locally: https://github.com/Thibaut/devdocs#quick-start
