### ISSUE TITLE
Bug: text-transform page opens another nested devdocs window

### ISSUE THREAD

**Issue by morenoh149** [Thibaut/devdocs#590]
navigating to http://devdocs.io/css/text-transform
jumps to the middle of the page and loads another instance of devdocs in a frame (I think)

**Comment by Kaijiro** [comment]
@Thibaut I checked quickly and it seems that the examples are rendered in iframes and somehow, this particular iframe seems to have its "src" attribute broken. Dunno why ...

**Comment by Thibaut** [comment]
Thanks for the bug report!
