### ISSUE TITLE
bug: cannot resize sidebar and items in menu are overflow

### ISSUE THREAD

**Issue by beiweiqiang** [Thibaut/devdocs#592]
How can I return to the old version devdocs.
There are some bug in my browser.
My environment is Win8.1 64bit, Chrome 56
![devdocs-bug](https://cloud.githubusercontent.com/assets/17352828/23554220/20777668-005f-11e7-9287-ad367f427bd7.png)
![devdocs-bug-2](https://cloud.githubusercontent.com/assets/17352828/23554306/7838203c-005f-11e7-9d50-8d1f1fcf8abb.png)

**Comment by Thibaut** [comment]
What happens when you try to resize the sidebar?

**Comment by beiweiqiang** [comment]
@Thibaut Thank you for responding.
I found the resizer default style is `display: none`, and I tried to delete the style, the sidebar can be resized finally.
![devdocs-bug-3](https://cloud.githubusercontent.com/assets/17352828/23579688/54c6d296-012d-11e7-99ae-4365ef5bb37a.png)

**Comment by Thibaut** [comment]
Right. It's because the sidebar was set to show/hide automatically. Both issues should be fixed in the next update. Thanks for the bug report.
