### ISSUE TITLE
OpenJDK compatibility

### ISSUE THREAD

**Issue by freayd** [Thibaut/devdocs#593]
Hey all,

I'm planning on adding the Java documentation using the OpenJDK 8. Before I dig into anything, I'd like to know if the [OpenJDK license](http://openjdk.java.net/legal/gplv2+ce.html) (GPL v2 with the Classpath Exception) is compatible with the DevDocs projects?

If so then I'll be submitting a pull request for it.

Thanks.

**Comment by Thibaut** [comment]
Hey!

Yes, the GPLv2 is compatible with DevDocs / MPLv2.

Which source are you planning to use? Ideally we'd use pre-generated docs from somewhere. I'm on macOS and would rather not have to build OpenJDK / the docs locally if we can avoid it.

**Comment by freayd** [comment]
That's great then.

Let me look a bit a the possibilities and I'll see if I can find some pre-generated documentation.

**Comment by freayd** [comment]
Would that be an option for you to start from any Linux distribution package like [Debian](https://packages.debian.org/sid/openjdk-8-doc) or [Ubuntu](http://packages.ubuntu.com/yakkety/openjdk-8-doc)? Will have to check their respective licensing thought. Are you already using any Linux distribution for other documentations?

**Comment by Thibaut** [comment]
Sorry, no. Every documentation is coming from a web/downloaded source, except the Ruby/Rails docs which are generated with a Ruby command-line tool.

Is there any way to turn these packages into HTML files without setting up an entire distro?

I also found http://linuxsoft.cern.ch/cern/slc63/i386/yum/updates/repoview/java-1.8.0-openjdk-javadoc.html and https://www.archlinux.org/packages/extra/x86_64/openjdk8-doc/.

FYI someone wrote a scraper for the SE documentation in https://github.com/Thibaut/devdocs/pull/560. We might be able to reuse parts of it for the OpenJDK scraper.

**Comment by japborst** [comment]
Great to see people working on this! @Thibaut I have looked into OpenJDK, but the fact that there was no publicly accessible version of the docs online and some time constraints, meant I did not write a scraper for OpenJDK.

I also found this one btw: http://packages.ubuntu.com/xenial/openjdk-8-doc

@freayd feel free to fork / use my branch in any way. Personally I have no experience with OpenJDK, so I have no idea how much similarities with the Oracle docs are.

**Comment by freayd** [comment]
As far as I understand, there is nothing else than sources provided by the OpenJDK project. So one option would be to download the sources and compile them which will generate the documentation.

Each Linux distribution provides packages, which are built by themselves from the sources. It is interesting to note that Linux distributions sometimes patch the original sources for various reasons, like adapting it to their platform or fixing bugs. Debian, Ubuntu, Arch Linux and the CERN all provide an OpenJDK documentation package containing a set of HTML files.

IMHO, I recommend starting from the Debian (the most reliable distribution, 23 years old now…) package. A package is a .deb file which is basically an archive. The Debian package is "built using the [IcedTea](https://en.wikipedia.org/wiki/IcedTea) build support and patches". My main concern still is the license, as the Debian, IcedTea and a few other building tools license is now coming up. @Thibaut can you please have a look at the [copyright file](https://gist.github.com/freayd/0d6333f9fd100cd0c416f46a1624f873) of the current Debian package and let me know if you think it is compatible with DevDocs? Thanks.

**Comment by Thibaut** [comment]
I've downloaded all four packages, and the documentation in each says:

> This document is the API specification for the Java™ Platform, Standard Edition.

and seems identical to http://docs.oracle.com/javase/8/docs/api/.

@freayd I'm not worried about the license of building tools like IcedTea. OpenJDK is licensed under GPLv2, so any derivative work has to also be licensed under GPLv2.

What I'm more worried about is whether those packages actually contain documentation built from the OpenJDK source code, and whether the GPL license applies or not. The packaging/UI of those docs indicate otherwise. Could you maybe ask for clarification on the OpenJDK mailing list?

**Comment by freayd** [comment]
I just spent a bit of time learning about the subject. I can't explain things better than these links (but I'll try to my best to summarize what I understood from them):
- [Wikipedia - Java Licensing](https://en.wikipedia.org/wiki/Java_(software_platform)#Licensing)
- [Wikipedia - OpenJDK / IcedTea inclusion in software distributions](https://en.wikipedia.org/wiki/OpenJDK#IcedTea_and_inclusion_in_software_distributions)
- [OpenJDK - FAQ](http://openjdk.java.net/faq/)
- [Ubuntu - Java](https://help.ubuntu.com/community/Java)
- [Debian - Java](https://wiki.debian.org/Java)

There are several Java implementations, such as OpenJDK, Oracle Java but also many others. All are supposed to be compatible, some fully, others not. But each version has indeed its own license and some share common code.

OpenJDK is a set of the opened classes under GPL. It is actually actively developed by Oracle but also many other contributors. The Oracle Java is built on top of the OpenJDK. Oracle provides some closed source additional classes/features to their Java SE and even more to their Java EE. The IcedTea project aims to implement an alternative GPL code to every bit of Oracle Java SE closed source features. Most of the Oracle Java SE is actually open (from OpenJDK), only bits of it are closed source which explains the great similarity between the Oracle Java SE documentations and the OpenJDK / IcedTea one.

Major Linux distributions ship so called OpenJDK packages which are actually built from IcedTea sources (based on OpenJDK). Debian & Ubuntu also provide packages for the older GCJ (GNU Compiler for Java), a no longer maintained alternative. There is also an IBM Java which isn't included in Debian nor Ubuntu, but IBM provides package for these distributions. As for the Oracle JDK SE, since 2011 Debian and Ubuntu no longer have the permission to distribute it, so instead Oracle provide binaries from its website.

**Comment by freayd** [comment]
If you still want to get a confirmation from the OpenJDK mailing list, we could try it but:
1. I'm confident to say that the Debian OpenJDK / IcedTea package is being built form fully opened sources. This is the [Debian source package](https://packages.debian.org/source/sid/openjdk-8) and the [source repository on Launchpad](https://code.launchpad.net/~openjdk/openjdk/openjdk8).
2. The OpenJDK FAQ contains: 
> Can I expect to get specific legal advice or answers to my legal questions on OpenJDK mailing lists? In general, no. The OpenJDK mailing lists serve for technical work around development of specific OpenJDK projects.

**Comment by japborst** [comment]
I just installed the openjdk documentation through `sudo apt install openjdk-8-doc`, which results in the same documentation as the Oracle docs in `/usr/share/doc/openjdk-8-doc/api/`. Also it shows the Oracle copyright at the bottom of the files:
> Copyright © 1993, 2017, Oracle and/or its affiliates. All rights reserved. Use is subject to license terms. Also see the documentation redistribution policy.

The [doc redistribution policy](http://www.oracle.com/technetwork/java/redist-137594.html) states:
> **Documentation**  The Java SE API Specification is not redistributable. One exception is granted, where permission is given to publish 10 or fewer unaltered screen shots of our documentation, whose intended purpose is to show examples of our work. Unaltered screen shots include web pages, our Java applets, our demo applets and applications, and listings of their source code.
> **API specifications** can be redistributed internally without special permission. They cannot be made available on the Internet.

So to answer your question, @Thibaut, the docs are _not_ generated from the OpenJDK source.

**Comment by Thibaut** [comment]
@freayd Thanks a lot for looking into this. 

I believe you're correct and the documentation is licensed under the terms/licenses described in the [copyright file](https://bazaar.launchpad.net/%7Eopenjdk/openjdk/openjdk8/view/head:/debian/copyright). I've looked at the source code of the OpenJDK package distributed on Debian and confirmed that the documentation is embedded in the source. This means the terms of GPLv2 license should apply to it, and any derivative work, including the API docs package, should also be licensed under GPLv2, regardless of Oracle's documentation redistribution policy (as long as the package was built from OpenJDK sources).

Additionally, if Oracle's documentation redistribution policy did apply to those packages, then Debian/Ubuntu/etc. would be violating it, as they are in fact redistributing the docs on their websites.

So I think we're good to redistribute the OpenJDK docs (downloaded from the Debian or Ubuntu repository) on DevDocs. I'll try to tackle this in the coming weeks, using [@japborst's PR](https://github.com/Thibaut/devdocs/pull/560) as a starting point.

**Comment by freayd** [comment]
Great news and thanks for helping.

I was going to start writing the necessary code, just waiting to be sure about the license compatibility. If you don't mind @Thibaut I can work on it in the next few days and send a new PR based on the previous one from japborst.

**Comment by Thibaut** [comment]
@freayd 👍

**Comment by Thibaut** [comment]
https://github.com/Thibaut/devdocs/pull/602 🎉

**Comment by gombosg** [comment]
Terribly sorry for necrobumping, but can I help with getting newer Java docs on board?
