### ISSUE TITLE
request: add server documentation for ubuntu 16.04 or other releases

### ISSUE THREAD

**Issue by 08ski11s** [Thibaut/devdocs#594]
request to add server documentation such as ubuntu 16.04 or other releases, it will be nice to have such documentation in devdocs ^_^

**Comment by Thibaut** [comment]
See:
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by 08ski11s** [comment]
i did not know, thanks for pointing out ^_^

**Comment by 08ski11s** [comment]
done
