### ISSUE TITLE
Django: ``versionchanged`` is not displayed fully

### ISSUE THREAD

**Issue by sk1p** [Thibaut/devdocs#595]
The Django documentation often contains small Changelog-style snippets scattered around the documentation. For example, see 

https://docs.djangoproject.com/en/1.10/ref/models/database-functions/#length

    Changed in Django 1.9:
    The ability to register the function as a transform was added.

It is not fully displayed in devdocs; the text of the change is displayed but the version is missing:

http://devdocs.io/django~1.10/ref/models/database-functions#django.db.models.functions.Length

Thanks!

**Comment by Thibaut** [comment]
This was an issue in the Django documentation, not DevDocs, which is fixed in the most recent version.
