### ISSUE TITLE
find an inconvenience in use

### ISSUE THREAD

**Issue by beiweiqiang** [Thibaut/devdocs#596]
After I checked `Automatically hide and show sidebar`, I type something in search bar and press Enter key.
Unfortunately the search bar is hidding the matching title.
![devdocs-bug-4](https://cloud.githubusercontent.com/assets/17352828/23983400/dcdd8236-0a4e-11e7-8a3c-18bb90fcb872.png)

**Comment by Thibaut** [comment]
Fixed. Thanks for the feedback.
