### ISSUE TITLE
search via url does not do initial render

### ISSUE THREAD

**Issue by dwelle** [Thibaut/devdocs#604]
When searching via query, e.g. `http://devdocs.io/#q=lodash+templ`, the devdocs finds the correct API, refreshes window when it redirects (dunno why), and loads the API in the left menu, but __does not render__ the body:

![image](https://cloud.githubusercontent.com/assets/5153846/24348042/a6f84996-12da-11e7-994e-6e8ef9ba8c1f.png)

I need to do additional refresh for it to work.

Stopped working since ~week ago (not sure).

Reproduced in chrome & FF stable.

**Comment by Thibaut** [comment]
Err, seems the fix doesn't fully work in production (was fixed locally). I can still replicate sometimes.

**Comment by dwelle** [comment]
Yup, still can repro 100% on current version if you've already shipped it.
