### ISSUE TITLE
Alphabetically sorted guides difficult to follow 

### ISSUE THREAD

**Issue by AyoubElk** [Thibaut/devdocs#606]
Hello,
While reading the expressjs guide I noticed that the subsections are sorted alphabetically (good for API references, not so much for guides and tutorials) which messes up the ordering available at the express website.

On devdocs:
![image](https://cloud.githubusercontent.com/assets/11050534/24480561/fa208cec-14dc-11e7-906e-1569eb80979b.png)

On the express website:
![image](https://cloud.githubusercontent.com/assets/11050534/24480575/13849296-14dd-11e7-83c0-170f503ef0bf.png)

**Comment by Thibaut** [comment]
Thanks for the feedback!
