### ISSUE TITLE
"email protected" filter mangles unpkg links in Vue.js docs

### ISSUE THREAD

**Issue by shamrin** [Thibaut/devdocs#607]
[Original:](https://vuejs.org/v2/guide/computed.html)

![screen shot 2017-04-03 at 13 29 18](https://cloud.githubusercontent.com/assets/510678/24605525/d7294830-1871-11e7-8104-8921cbf82a97.png)

[DevDocs:](http://devdocs.io/vue~2/guide/computed)

![screen shot 2017-04-03 at 13 29 42](https://cloud.githubusercontent.com/assets/510678/24605526/d72d813e-1871-11e7-85d0-0239a42c70ba.png)

Previously: #373, #491, #545. Why do we need "email protected" filter at all?

**Comment by j-f1** [comment]
@shamrin This is caused by the original site using Cloudflare. if you visit the site with JavaScript disabled, which is presumably what DevDocs does, you’ll see `[email protected]` in the code.

**Comment by Thibaut** [comment]
Thanks for the bug report. Like @j-f1 said, it's caused by Cloudflare.
