### ISSUE TITLE
Scrolling skips on click (in preferences mode) in the left panel.

### ISSUE THREAD

**Issue by adrianvoica** [Thibaut/devdocs#609]
On macOS, Chrome, when I click on something from the left panel (checkboxes), the panel's scrolling is messing up, jumping, such that on mouseup I am not positioned over the checkbox anymore.

**Comment by Arkni** [comment]
On Ubuntu 14.04, the same bug appears on `Chrome 57.0.2987.98` and `Firefox Developer Edition 54.0a2`.

**Comment by ymeine** [comment]
Same on `Windows 7`, `Firefox Nightly 52.0 (64-bit)`.

**Comment by antoine-briand** [comment]
Having the same problem on Chrome Version 57.0.2987.133 : 
![bug-devdocs](https://cloud.githubusercontent.com/assets/4669715/25060867/b3ae7ee0-2175-11e7-8142-0ab0d8979554.gif)

**Comment by Thibaut** [comment]
Thanks for the bug report. Fixed!

**Comment by Arkni** [comment]
Thanks!
