### ISSUE TITLE
Forced close on chrome android when instal big docs and blank page on uc browser android

### ISSUE THREAD

**Issue by pujohanto** [Thibaut/devdocs#610]
please fix it! Im using android, with chrome browser v54 and uc browser v10.0.58
problem with chrome when i'm instaling docs with big size, like DOM docs my browser is forced close, but small docs like html css js, dom event is without problem.
When im using uc browser to visit devdocs.io, its just blank page
nb: my android tablet is v4.4 kitkat, with ram 512, space on device is more than enough
Thanks

**Comment by Thibaut** [comment]
Unfortunately there's nothing I can do in DevDocs to fix this. Browsers should never crash. When they do, it's a browser bug. DevDocs tries to reduce the size of docs as much as possible, but some docs are just big and can't be compressed any further without removing useful content.
