### ISSUE TITLE
Support Design Pattern Documentation for PHP, Nodejs?

### ISSUE THREAD

**Issue by semachka** [Thibaut/devdocs#611]
Any chance we can implement some sort-of Design Pattern documentation for languages like PHP, Nodejs etc...?

**Comment by fvsch** [comment]
Could you elaborate which existing online documentations you would like to see supported in Devdocs? Devdocs only serves:

- existing HTML documentation
- that have been scraped by a custom-made import script

The [contributing docs](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations) state that documentation requests should be added on Trello and not on GitHub, by the way.
