### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by Maraket** [Thibaut/devdocs#612]
While trying to use DevDoc for the guides for VueJs I noticed it sorts them alphabetically, which is not helpful as they are ordered sequentially on the site. 
Allowing certain documents to be ordered as they appear on the site, rather than alphabetically or providing the option to sort them accordingly would improve usability in some instances.

**Comment by Thibaut** [comment]
Thanks for the feedback. I've added numbers to the entries, so they get listed in the same order as on the site.

**Comment by wufeihuang** [comment]
Hello, this problem happens not just to Vuejs. There is the same order problem for all other docs. @Thibaut

**Comment by irisjae** [comment]
For instance, official PostgreSQL docs are already ordered with a clear numbering, and this information is present in devdocs as well, yet the section numberings are ignored when sorting, providing only alphabetical ordering.
