### ISSUE TITLE
Issue with installing on windows

### ISSUE THREAD

**Issue by Epic3lite** [Thibaut/devdocs#614]
bundle seems to want a version of ruby that is both greater than 2.4.1 and less than 2.4 
```
>bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby ":
  In Gemfile:
    ruby  (~> 2.4.1.0)

    ruby  (~> 2.4.1.0) x64-mingw32

    nokogiri was resolved to 1.7.1, which depends on
      ruby  (< 2.4) x64-mingw32
```
I followed all the instructions on the main github page, and I even installed multiple versions of ruby (2.4.1 and 2.3.3) but still nothing.
I'm currently using Windows 8.1 64-bit

**Comment by Epic3lite** [comment]
Actually it's just an issue with nokogiri on windows, It works fine in my linux vm.

**Comment by j-ulrich** [comment]
You can run

    > bundle update nokogiri --minor

to update nokogiri to 1.8.0. Then it will work on Windows x64 again.
