### ISSUE TITLE
keypress, keyup and keydown miscategorized as focus events

### ISSUE THREAD

**Issue by Isk1n** [Thibaut/devdocs#615]
Subcategory Focus (1) of DOM Events (2) contains keyboard events (3). Subcategory Keyboard (4) is absent.

It happens most likely because .standard-table of each keyboard event page has substring focus (5). See https://github.com/Thibaut/devdocs/blob/a8bd4227c3377d63b7e018ecb95f2eaff9c7328d/lib/docs/filters/dom_events/entries.rb#L68

![screenshot-devdocs io](https://cloud.githubusercontent.com/assets/5972067/25576544/c1171808-2e68-11e7-9597-aec5edb90f9d.png)

Possible solutions:
1. change 'Focus' key of TYPE_BY_INFO from 'Focus' to 'FocusEvent' https://github.com/Thibaut/devdocs/blob/a8bd4227c3377d63b7e018ecb95f2eaff9c7328d/lib/docs/filters/dom_events/entries.rb#L11 
2. extra check a la FORM_SLUGS and LOAD_SLUGS https://github.com/Thibaut/devdocs/blob/a8bd4227c3377d63b7e018ecb95f2eaff9c7328d/lib/docs/filters/dom_events/entries.rb#L48

**Comment by Thibaut** [comment]
Thanks for the feedback!
