### ISSUE TITLE
Some documentation not installing on ms edge

### ISSUE THREAD

**Issue by cozmik** [Thibaut/devdocs#622]
I have tried installing JS, Node.js, backbone.js on edge and I keep getting error while others install fine..

And I keep getting this error on firefox 

> Offline mode is unavailable.
> 
> An error occured when trying to open the IndexedDB database:
> UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
> This could be because you're browsing in private mode or have disallowed offline storage on the domain.
>

**Comment by Thibaut** [comment]
This appears to be the same or similar issue as #584. Unfortunately I'm not able to replicate. Most likely this is a problem with Firefox (not sure what's going on with Edge). 

If you're able to pinpoint the root cause or provide steps to reproduce, please add more info in #584.
