### ISSUE TITLE
[Feature request] Add option to search for methods.

### ISSUE THREAD

**Issue by jottr** [Thibaut/devdocs#625]
Let's say I'm looking for javascripts `array.map()`, I would love to be able to search for the desired documentation until the method level, e.g.: `js:array.map` should jump to the methods documentation. 
For UX-reference, [Dash](https://kapeli.com/dash) comes with the described behavior.

**Comment by Kaijiro** [comment]
It does actually works.

Focus on the search field, type `js`, press `Tab` then type `array.map` and finish by pressing `Enter`.
Is it what you need ?

**Comment by jottr** [comment]
That's what I actually did. devdocs comes up empty for me. Have you actually tested the command above?

**Comment by Kaijiro** [comment]
Yup, I was doing the steps while writing this answer.

It's weird that it doesn't work for you ...

**Comment by jottr** [comment]
I think I've found the error: I use devdocs via the browsers address bar, where searching for methods doesn't work.
Using the search on the website directly, it does work as you described.

**Comment by Kaijiro** [comment]
How do you do your searches ? Via the 'q' parameter ?

**Comment by jottr** [comment]
Via chrome's address bar. So, yes via the 'q' parameter. 
Redirection happens so fast, that I am unable to see what parameters are actually passed...

**Comment by Kaijiro** [comment]
I managed to find a way around.
You can pass `?q=js%20array.map` as parameter. It's a bit strange, but it does fix the problem ...

**Comment by Thibaut** [comment]
You need to search `js array.map` instead of `js:array.map` (space between the doc name and the search query, instead of colon).
[http://devdocs.io/#q=js array.map](http://devdocs.io/#q=js%20array.map)
See also: http://devdocs.io/help#search

**Comment by Kaijiro** [comment]
I am dumb, `%20` is a space, why didn't I try like this xD
