### ISSUE TITLE
dark theme could not be disabled

### ISSUE THREAD

**Issue by ChristopherNeuwirth** [Thibaut/devdocs#627]
Hi there,

I use your project a lot. Since a long time I used the dark theme. Lately I tried to use the light theme again and noticed that my selection is not stored in the cookie which holds up my configuration. 

I also deleted the whole storage information and reconfigured it completely new on my machine to personalize my devdocs.io experience. 

Unfortunately this did not had any effect on my color-scheme problem. Every time I reload the page it shows up in dark mode again, no matter if the cookie holds up dark = true. 

Do you have any advice how to fix that?

Thanks.

**Comment by Thibaut** [comment]
Hey - which browser/OS are you using?

**Comment by ChristopherNeuwirth** [comment]
Hi there,
its a Safari 9 user agent on macOS El Capitan.

**Comment by Thibaut** [comment]
Do you use any browser extension and/or syncing service? It's possible that cookies are being synced and reset to enable dark mode.

Can you replicate in other browsers?

Could you post the output of http://devdocs.io/manifest.appcache in Safari (after clearing all storage for devdocs.io, then after reproducing the problem).

**Comment by ChristopherNeuwirth** [comment]
Hi there,
I do not but after deleting all website data for the 360th time and killing the safari process it somehow works again. 
Thanks for your support anyway.
Greetings.
