### ISSUE TITLE
the HTML miss input[type="radio]、input[type="file] and many more.

### ISSUE THREAD

**Issue by neoherus** [Thibaut/devdocs#628]

**Comment by Thibaut** [comment]
This is because MDN doesn't yet have dedicated pages for all input types (e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio doesn't exist). You're welcome to contribute MDN. 

Meanwhile, all input types are documented over here: http://devdocs.io/html/element/input
