### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by nattapongk** [Thibaut/devdocs#629]
I've got console error message while install CSS doc.

> XMLHttpRequest cannot load http://docs.devdocs.io/css/db.json?1492871074. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://devdocs.io' is therefore not allowed access.

browser: Google Chrome Version 58.0.3029.110 (64-bit)
os: Windows 8.1 64

**Comment by Thibaut** [comment]
What do you get when you open http://docs.devdocs.io/css/db.json?1492871074 in Chrome?

Could you post a screenshot of the network logs for that request (HTTP response headers &co).

This is likely caused by a proxy in your network or system, which is stripping or rewriting HTTP headers.

**Comment by nattapongk** [comment]
When I open [http://docs.devdocs.io/css/db.json?1492871074](http://docs.devdocs.io/css/db.json?1492871074) in Chrome, I've got data leak blocked screen from my company's firewall. like [this](http://pub.kb.fortinet.com/Platform/Publishing/images/aniln/FD36722/tn_FD36722-6.jpg) picture form fortinet.

But when I try [https://docs.devdocs.io/css/db.json?1492871074](https://docs.devdocs.io/css/db.json?1492871074) , I've get json data.

So, then I install HTTPS Everywhere extension and try install CSS doc again it work fine.
