### ISSUE TITLE
How I can erase one package

### ISSUE THREAD

**Issue by YnievesDotNet** [Thibaut/devdocs#635]
I download package dom_events, but on any page I load, found error 404.

How I can erasethis package and downloaded agains. Thanks.

Yoinier

**Comment by Thibaut** [comment]
Do you mean you've installed the "DOM events" documentation under http://devdocs.io/offline and now it doesn't work anymore? There is a link to uninstall the documentation on that page.

Which OS/browser are you using?
Could you post a screenshot of the network logs when trying to open a page that 404?
