### ISSUE TITLE
Settings and offline docs lost after browser restart

### ISSUE THREAD

**Issue by Em-AK** [Thibaut/devdocs#636]
Browser Iridium (chromium fork)
Same behaviour with adblockers desactivated.

When I visit devdocs after restarting my browser, all my settings (enabled and offline docs, theme) are back to default.

0. **default settings**
![selection_001](https://user-images.githubusercontent.com/1518393/27129072-5a6617c4-5101-11e7-9e94-1b6c97af9aeb.png)

1. **Enable Ansible doc and install it for offline access**
So far so good. Ansible doc is listed in the search list, the offline list, in local storage, in IndexDB, and even in the cookie.

Content of local storage
![selection_002](https://user-images.githubusercontent.com/1518393/27129093-6b5b526a-5101-11e7-8d29-7b07bf6f83bb.png)
Content of the cookie
![selection_003](https://user-images.githubusercontent.com/1518393/27129102-73dfd3ac-5101-11e7-8815-204f9514057b.png)

2. **Close tab, close browser**
3. **Open browser and visit https://devdocs.io**
Ansible doc is **NOT listed** in the search list, the offline list, in local storage and in the cookie.
But it is still **present in IndexDB** !

Content of local storage
![selection_004](https://user-images.githubusercontent.com/1518393/27129157-a2fc8c8e-5101-11e7-8dbc-962931c0ad15.png)
content of the cookie
![selection_005](https://user-images.githubusercontent.com/1518393/27129162-a718bda6-5101-11e7-8bc7-ce77ae8d2f51.png)

What in my browser settings could induce this strange behaviour ?

**Comment by Thibaut** [comment]
Something is resetting cookies. The data in localStorage is just a cache — it's not the source of truth for whether a doc is enabled or not (neither is IndexedDB). Cookies store that information, and based on your screenshots, they were reset after you restarted your browser (the `count` cookie increases every time you open the app, and you can see that it went from 5 to 2 after the restart).

Make sure your browser isn't set to delete cookies on quit (most browsers have a setting for doing that, e.g. in Chrome it's "Keep local data only until you quit your browser").
