### ISSUE TITLE
Have the escape key erase the search in steps if scoped to a language.

### ISSUE THREAD

**Issue by indigo0086** [Thibaut/devdocs#639]
When you select a language and press tab, then devdocs scopes all searches to that.  The problem is when you press escape, it erases the search term and the particular scoped language.  I would like to propose (and work on) a change to have the escape key first erase the search term, then if you press escape again, when there is no search term, erase the scope if it is present.  This way it allows the user to rapidly search for another term in the same language instead of deleting multiple times or having to re-scope.

**Comment by Thibaut** [comment]
Thanks for the feedback. Improved.

**Comment by indigo0086** [comment]
Awesome. thanks
