### ISSUE TITLE
Cannot request new documentation

### ISSUE THREAD

**Issue by jhabdas** [Thibaut/devdocs#641]
Looks like the Trello board is locked down now, rendering both the repo contribution guidelines and issue template a tad confusing. Is this a temporary thing, or did the woes of crowdsourcing finally become evident? Either way, how can I request WordPress documentation. Their website is making my fingers hurts.

**Comment by Thibaut** [comment]
The Trello board is not locked down (but you do need to sign up in order to comment/vote), and WordPress has already been suggested there (https://trello.com/c/mDIVCppx/85-wordpress).

**Comment by jhabdas** [comment]
Sign-up for what, exactly? Whenever I was logged in in the past I could create cards. Now I'm only able to comment and edit.

Also, thanks for pointing at the WordPress card. Not sure how it didn't come up when I searched before. But that was with Chrome. Yandex seems to be working just fine.

**Comment by jhabdas** [comment]
<img width="949" alt="screen shot 2017-06-26 at 11 24 55 am" src="https://user-images.githubusercontent.com/440298/27523772-1b0f12dc-5a62-11e7-9f8f-cd9cf1e61faf.png">

**Comment by jhabdas** [comment]
I'm going to assume Atlassian made a change, or the board is still broken and that's why your ideas have gone from the previous disorganized state to next to nothing.

**Comment by j-f1** [comment]
You have to comment on the requests card, and then @Thibaut will add the card.

**Comment by jhabdas** [comment]
Ah. Thanks for that.

**Comment by Thibaut** [comment]
No one but me has ever had permissions to create cards on the board. You're welcome to vote/comment, suggest new cards [here](https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here), or send in a PR.

**Comment by jhabdas** [comment]
Yep. Totally realized that now. The new interface Atlasssian threw on Trello got me confused. Funny how little things can change your entire mindset. Thanks @Thibaut.
