### ISSUE TITLE
HOW IT'S WORKS for update 

### ISSUE THREAD

**Issue by mauriau** [Thibaut/devdocs#645]
Hi everybody !

I would like to know how it's works for update.

So, devdocs load every time the site of the docs ?

Or, there is a cron which build the doc everyday ?

So, if I update my latest version, but dont create a new tag, at which moment, devdocs catch this new update and it's published ?

**Comment by Thibaut** [comment]
Docs are updated manually by myself, using the [command line tools](https://github.com/Thibaut/devdocs#available-commands) (scraper/generator scripts) in this repo. If you want to follow updates, you can subscribe to commits on `master`: https://github.com/Thibaut/devdocs/commits/master
