### ISSUE TITLE
Visual Studio Code also has plugins for devdocs

### ISSUE THREAD

**Issue by volo-zyko** [Thibaut/devdocs#648]
This can be mentioned on Wiki page. There are 2 plugins actually. https://marketplace.visualstudio.com/items?itemName=akfish.vscode-devdocs and https://marketplace.visualstudio.com/items?itemName=deibit.devdocs

**Comment by volo-zyko** [comment]
Well, after using both of these plugins I can state the following. :) It looks like the first one opens devdocs inside VSCode which looks like a part of the editor. The second one is not very usable - it just opens devdocs in default browser, so it cannot interact with the opened page.

**Comment by Thibaut** [comment]
Thanks. I've added both to the wiki page.
