### ISSUE TITLE
Offline mode not working with different Windows users

### ISSUE THREAD

**Issue by trhsrw** [Thibaut/devdocs#649]
The offline mode seems to ignore additional doc packages when a different Windows user logs in.

The setup:
- OS: Windows 10
- Browser: Chrome Portable(!) Version 59.0.3071.115

The problem:
When additional docs (e. g. AngularJS 1.6, jQuery) are installed for offline use in ChromePortable, different Windows users (or users on a different machine using the portable Chrome) see only the docs enabled by default (CSS, DOM, etc.) in offline mode. The same occurs if a non-portable version of Chrome is used. The localStorage and IndexedDB entries can be seen in the developer tools of Chrome, even if a different user logs in. Nonetheless, only the default docs are available offline.

The user who installed the docs can see and access all docs offline.

The images attached show the original user's view and the different user's view. Note, that both views were recorded in a filesystem location, where Chrome Portable was NOT originally installed (it was moved).

Original user:
![original_user](https://user-images.githubusercontent.com/26300206/28109546-b77dd592-66ef-11e7-81f2-38daeb65f9e5.png)

Different user:
![different_user](https://user-images.githubusercontent.com/26300206/28109543-b44e02de-66ef-11e7-80cf-c447b0149c58.png)

**Comment by Thibaut** [comment]
Hi

The selection of docs is stored in a cookie, not localStorage or IndexedDB. I'm guessing that in your case, cookies are not shared between the user profiles (or didn't get copied like you expected). 

Closing the issue, as this isn't a problem with DevDocs.
