### ISSUE TITLE
[FEATURE REQUEST] Mirror topics arrangement with the original docs source

### ISSUE THREAD

**Issue by toyongbanatero** [Thibaut/devdocs#650]
Can we have an option (or by default), the docs were sorted with how they were arranged with the original docs website of that language/framework? For example, I have been using the PHP and Laravel devdocs sections. My problem with it is that the articles were sorted alphabetically, and I have no way of knowing which ones do I need to read first. This is a problem with tutorial docs (for example in Laravel) because you need prior information found in previous sections of the docs to continue, and as I said, without knowing how this was arranged on Laravel's website, it can be a pain (I do not have internet connection most of the time so I use devdocs in this cases). The alphabetical sorting of things do not affect things very much when viewing an API documentation (in my case, PHP for example), and in fact helps finding things more easily (though the PHP docs also have a tutorial-like section but can be read in almost any order, but will be more help if arranged as in the PHP website too). Thanks!

**Comment by chuongnh3atgmaildotcom** [comment]
Agree, this feature will help using devdocs to learn rather than just for reference.

**Comment by shoaibshakeel381** [comment]
Any update on this? Is this a planned feature or not? Don't know Ruby otherwise I'd help out too. :(

**Comment by Thibaut** [comment]
Hey - this isn't something that can be addressed/improved in one swoop across all the docs available on DevDocs. Every doc is different, and the arrangement of entries in DevDocs's sidebar has to be manually fined-tuned for each one (most, especially PHP, don't make it easy to categorize entries). 

If you have suggestions for improving the arrangement of entries of a specific doc, please open a new issue for that particular doc (provide as many details and examples as possible), and I'll be happy to try to improve things where possible.

Closing this issue, though, as no single change is really going to fix it.
