### ISSUE TITLE
OpenSearch doesn't work on firefox

### ISSUE THREAD

**Issue by sbrl** [Thibaut/devdocs#651]
The opensearch file, while valid XML, doesn't appear to be liked by Firefox. In addition, I'm not sure on how to extract any more information from it. I've got an extension installed that lets me add opensearch files manually, and that _still_ didn't work! I'll be happy to help track this down and provide more information in request.

 - `uname -a`: `Linux Riikaan 4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
 - Firefox version: 54.0

**Comment by Thibaut** [comment]
What do you mean it doesn't work? Could you post screenshots highlighting the problem?

It works for me, as you can see here:

<img width="268" alt="screen shot 2017-07-18 at 08 04 35" src="https://user-images.githubusercontent.com/17579/28316199-d080ed50-6b8f-11e7-834a-c6b32977654f.png">

And when I add DevDocs as a search engine, I can search with it just fine.

**Comment by clarkbw** [comment]
I can't seem to reproduce this either.  Can you try with your extensions turned off?  What version of Firefox?

**Comment by sbrl** [comment]
That's really odd. I've just tried it again and it works! Never mind, then :P

**Comment by randolf** [comment]
I find that it doesn't work in Firefox for me either.  It works fine in Google Chrome.

**Comment by sbrl** [comment]
Hrm. Shall I reopen this, @randolf?

**Comment by Thibaut** [comment]
Please open a new issue with steps-to-reproduce if OpenSearch doesn't work. Nothing has changed in DevDocs recently related to this.
