### ISSUE TITLE
*Manually* show and hide sidebar with the *mouse*

### ISSUE THREAD

**Issue by agussell** [Thibaut/devdocs#657]
When the option of _automatically_ hide and show the sidebar is enabled, after a search is done and an option is selected, the sidebar disappears and it seems there is no way of showing it again with the mouse.

The main problem is that when you search from the address bar with [https://devdocs.io/#q=keyword](https://devdocs.io/#q=keyword), the first entry of the results is selected and the sidebar permanently closes, so it is impossible to change the documentation unless you use <kbd>Alt</kbd>+<kbd>&#8593;</kbd> or <kbd>Alt</kbd>+<kbd>&#8595;</kbd> but not with the mouse, which would be useful if you are not familiar with the keyboard shortcuts.

I am using Google Chrome 59.0.3071.115 in Ubuntu 17.04.

**Comment by Thibaut** [comment]
Good idea. I'll try to add this soon.

**Comment by Thibaut** [comment]
Done. The sidebar now pops back in & out when you mouse over the left edge of the viewport. Thanks for the feedback.
