### ISSUE TITLE
Way to import/export preferences to share between browsers

### ISSUE THREAD

**Issue by danbruegge** [Thibaut/devdocs#671]
Hi,

i use firefox and chromium for developement and currently i'll have to set the preferences for both. It would be quite helpful to export the settings and import them on the other browser.

Is there a plan to make such a feature available?

**Comment by j-f1** [comment]
I copy the `docs` cookie and put it in a Google Doc that looks like this:

```js
Cookies.set('docs', '<your cookie code here>')
```

Next, I type `javascript:` in the URL bar of the other browser, then paste in the code to update the cookie.

**Comment by danbruegge** [comment]
Thanks for the workaround. Worked fine.

But maybe a user friendly ui would also be worth?

**Comment by Thibaut** [comment]
@danbruegge coming later today :)

**Comment by danbruegge** [comment]
Sounds good. :)

**Comment by danbruegge** [comment]
Awesome and fast work. Thanks. 👍
