### ISSUE TITLE
How to add new Documentation

### ISSUE THREAD

**Issue by JorgeDDW** [Thibaut/devdocs#672]
Hi there!

So I want to add GraphQL documentation, how do I do it?
It's possible to add to devdocs.io to?

**Comment by ANtlord** [comment]
Hello!
Checkout https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs plases

**Comment by JorgeDDW** [comment]
oh! one last question this will add the doc to devdocs.io?

**Comment by j-f1** [comment]
Once you’ve made the changes specified on that page, you should open a pull request so the maintainer can publish your changes.

**Comment by Thibaut** [comment]
@JorgeDDW once you've got a scraper working locally for the new documentation, you're welcome to submit a pull request on this repo. More instructions here: https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#contributing-new-documentations

Once your PR is merged and I deploy DevDocs, the doc will appear on devdocs.io (this doesn't happen automatically).
