### ISSUE TITLE
 The page failed to load.

### ISSUE THREAD

**Issue by phantian** [Thibaut/devdocs#674]
Error message shows the following : 

The page failed to load.
It may be missing from the server (try reloading the app) or you could be offline.
If you keep seeing this, you're likely behind a proxy or firewall that blocks cross-domain requests. "

I tried to clear cache/storage and reload, with / without offline data, nothing happens.

Thanks.

**Comment by Thibaut** [comment]
Which page are you seeing this on? Could you please post a screenshot of the network logs in the dev tools when this happens? Is your internet connection behind a proxy or firewall?

**Comment by phantian** [comment]
I figured it out, actually it was my firewall. It's all good man . Thanks
