### ISSUE TITLE
Installing PHP docs fails

### ISSUE THREAD

**Issue by ZeeCoder** [Thibaut/devdocs#675]
I've just started using DevDocs today, and I could install everything I've selected except for PHP.

![devdocserror](https://user-images.githubusercontent.com/3679506/30536298-2fcbce94-9c5d-11e7-9c9d-6ef622edee77.png)

OS: Ubuntu Linux 16.04 LTS
Browser: Chrome Stable 60

**PS: Great work, absolutely loving this.**

**Comment by Thibaut** [comment]
Is your internet connection behind a proxy or firewall? This happens when something in between your browser and the `docs.devdocs.io` origin server blocks the CORS preflight request.

**Comment by ZeeCoder** [comment]
That's most likely it, I've just tried on my home computer and it works flawlessly.
I think there's some sort of firewall set up at the office, so your hunch is probably spot on too.

Thanks!
