### ISSUE TITLE
Prefilling the search field in querystring for a single documentation not working

### ISSUE THREAD

**Issue by opensas** [Thibaut/devdocs#676]
According to the documenation at http://devdocs.io/help#search

> The search field can be prefilled from the URL by visiting devdocs.io/#q=keyword. Characters after #q= will be used as search query.
> To search a single documentation, add its name and a space before the keyword: devdocs.io/#q=js date. 

Yesterday I tried it with the prefix cr (for Crystal) and it worked ok, but today is not working anymore

Testing with:

`https://devdocs.io/#q=cr array`

Sends me to 
`https://devdocs.io/javascript/global_objects/array`

instead of
`https://devdocs.io/crystal/api/0.23.0/array`

**Comment by Thibaut** [comment]
Have you enabled the Crystal documentation? This only works for docs that are enabled (I'll update the help page to clarify).

**Comment by opensas** [comment]
You are right, I guess ran bleachbit and it must have erased my dedocs conf, thanks! devdocs is a great tool!
