### ISSUE TITLE
Email protected

### ISSUE THREAD

**Issue by mazhead** [Thibaut/devdocs#677]
The git repository is changed wrongly to email protected:

Devdocs:
http://devdocs.io/ansible/intro_installation#latest-releases-via-pip

Original:
http://docs.ansible.com/ansible/latest/intro_installation.html#latest-releases-via-pip

**Comment by Thibaut** [comment]
Thanks for the bug report. This is caused by Cloudflare's email protection. I'll fix in a future update.
