### ISSUE TITLE
Start app in minimized mode

### ISSUE THREAD

**Issue by paulsrch** [Thibaut/devdocs#681]
I'm loving the app, and use it all the time. One suggestion would be to have a parameter (or command line switch) which makes the app open minimized in the tray. That way, I can put it into "start programs" and have it ready when I first log on.

**Comment by Thibaut** [comment]
This repo is only for the web app (devdocs.io). I'm guessing you're using [this desktop app/wrapper](https://github.com/egoist/devdocs-desktop), in which case you should report the issue there.
