### ISSUE TITLE
How do I remove a specific documentation 

### ISSUE THREAD

**Issue by abrhambas01** [Thibaut/devdocs#683]
How do I remove a specific documentation so that it won't display its list of functions.

**Comment by DerJacques** [comment]
You need to go into the preferences (simply click on the three dots next to the search bar). If you do that, the sidebar should change, and you are able to deselect the documentations that you do not want to include in your searches.

**Comment by Thibaut** [comment]
What @DerJacques said.

**Comment by abrhambas01** [comment]
@DerJacques Well, thank you my friend
