### ISSUE TITLE
License for icon

### ISSUE THREAD

**Issue by cmalard** [Thibaut/devdocs#685]
Hello there,

Can we use [devdocs icon](https://github.com/Thibaut/devdocs/tree/master/public/images) in related projects ?
Cf https://github.com/egoist/devdocs-desktop/issues/49

Thanks :-)

**Comment by Thibaut** [comment]
Hey - Those icons unfortunately aren't very good (I wish we'd get a new/better one), but yes @egoist is welcome to use it for https://github.com/egoist/devdocs-desktop :)
