### ISSUE TITLE
URL for searching

### ISSUE THREAD

**Issue by PierBover** [Thibaut/devdocs#687]
It would be awesome to be able to have a URL for searching such as:

`https://devdocs.io/?search=something`

This would be extremely helpful for people that use a launcher like Alfred, Quicksilver, or Launchbar, or even if someone wants to develop a browser extension.

Would you accept a PR with this feature?

**Comment by Thibaut** [comment]
Already works :)
`https://devdocs.io/#q=something`

See also http://devdocs.io/help#search.
