### ISSUE TITLE
please add spring framework document

### ISSUE THREAD

**Issue by devarchi33** [Thibaut/devdocs#689]
I am using devdocs very well.
Thank you very much for making this project.
I think if add [a spring framework document,](https://spring.io/docs/reference) to this project more users will like it. (like  @me)

**Comment by Kaijiro** [comment]
Hello

Please, follow the rules for requesting new document, DO NOT POST AN ISSUE, go to the [Trello Board](https://trello.com/b/6BmTulfx/devdocs-documentation). As you can see, Spring is already in the "To Do [Others]" part. 

As the Java scrapper has already be done, you can take a look at it and create a PR to integrate Spring Documentation.
