### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by jb08** [Thibaut/devdocs#698]
using _Docker for Mac_ with memory of 2.0 GB, receiving this stacktrace from `docker build -t thibaut/devdocs .`

<img width="421" alt="screen shot 2017-10-20 at 3 42 35 pm" src="https://user-images.githubusercontent.com/8146460/31841019-5c1404bc-b5ad-11e7-82ed-987a05d6845f.png">

**Comment by brewingcode** [comment]
....isn't the last line of your output the answer? You appear to be out of disk space. :-)

Or if by "memory of 2.0 GB" you mean "max image size of 2.0GB", it looks like the docker image weighs in at 3.2GB. So it will never fit in 2 GB.

**Comment by jb08** [comment]
yes, I bumped the _Docker For Mac_ memory to 4GB, and it built successfully. thanks!
issue closed.
