### ISSUE TITLE
Add v as Vue alias

### ISSUE THREAD

**Issue by ajtruex** [Thibaut/devdocs#701]
This is a request to add new search alias <code>v</code> for Vue.

**Comment by j-f1** [comment]
I’m pretty sure it works already — did you try it?

If it doesn’t work for you, do you have any other docs installed with `v` in their names?

**Comment by Thibaut** [comment]
Like @j-f1 said, this should already work, unless you've got another doc that starts with the letter "v" enabled. I'd rather not add single-letter aliases, as they're too opinionated / likely to conflict with other docs in the future. Thanks for the feedback though.
