### ISSUE TITLE
mkdocs support

### ISSUE THREAD

**Issue by mihaipopescu** [Thibaut/devdocs#702]
Is it possible to scrap documentation generated by [mkdocs](mkdocs.org) ?

The only way I can see it now is if first you [import](http://docs.readthedocs.io/en/latest/builds.html#mkdocs) mkdocs into readthedocs and then extend `Rdoc` base class but it's cumbersome and might not be possible in some cases.

**Comment by Thibaut** [comment]
There is no scraper/generator for mkdocs at the moment. Contributions welcome.
