### ISSUE TITLE
why not polymer?

### ISSUE THREAD

**Issue by spyhole** [Thibaut/devdocs#715]

**Comment by j-f1** [comment]
Polymer has been requested [here](). Unfortunately, the maintainer doesn’t have much time to work on new definitions, but there is [a guide](https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs) to help you get started with adding your own documentation.

**Comment by Thibaut** [comment]
Please read the [contributing guidelines](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations).
