### ISSUE TITLE
Ability to have a favorites or most viewed tab

### ISSUE THREAD

**Issue by RaDeleon** [Thibaut/devdocs#717]
Ability to have a favorites or maybe most used section which automatically adds the pages you check frequently or both of these options???

Idk maybe I will make myself sounds fun

**Comment by Thibaut** [comment]
Hey - thanks for the feedback.

While I agree such a feature could be somewhat useful, I don't think it's something that most users would use or derive much value from, so I don't think we should add it to DevDocs (every feature takes time to implement and then maintain).

Browsers also already have built-in features for bookmarking pages (and extensions can fill in the gap for things like "most viewed pages"), which makes adding such a feature to DevDocs a bit redundant.
