### ISSUE TITLE
Broken link to domframecontentloaded inside DOM Events

### ISSUE THREAD

**Issue by hacknug** [Thibaut/devdocs#719]
Broken link inside https://devdocs.io/dom_events/ takes you to https://devdocs.io/dom_events/domframecontentloaded 

Since all links in that section point to, this one should probably link to https://developer.mozilla.org/en-US/docs/Web/Events/domframecontentloaded

I can open a PR if you need me to. Also, thank you for such a helpful site!

**Comment by Thibaut** [comment]
Thanks for the bug report. This is somewhat intentional, in that this event is specific to Firefox Addons, so the scraper is set to skip it. However, the link should open MDN instead of inside DevDocs (where the page doesn't exist). Will fix next time I update the MDN docs.
