### ISSUE TITLE
Multiple languages supported

### ISSUE THREAD

**Issue by MarckFp** [Thibaut/devdocs#720]
I would like to see a multiple language support, a lot of documentations are already in their websites in different languages like english,spanish,french, italian,etc... This would be a very helpful feature.

It is a simple feature but It takes a lot of work, I love this project and I use it a lot!! keep working on this, you have maked a real good work.

**Comment by Thibaut** [comment]
Thanks for the feedback and the kind words!

Supporting multiple languages would be a lot of work. While I'm not against the idea, this isn't something I'd be willing to add to the main DevDocs repository, as I'm already maxed out in terms of maintenance burden. But anyone is welcome to fork the repo and create a French/Spanish/Italian/etc. version of DevDocs, which if done well I'd be happy to promote in the main app.
