### ISSUE TITLE
Color themes

### ISSUE THREAD

**Issue by Martin1887** [Thibaut/devdocs#73]
Having color themes (at least a dark theme) would be wonderful to improve  the user experience, since the current theme is too white.

Since DevDocs is a web app, it could be achieved allowing change among CSSs or allowing to load CSS files from local filesystem with a CSS template.

Thank you for this awesome app!

**Comment by theblacklion** [comment]
Any updates on this topic? :)

**Comment by eush77** [comment]
You can always activate “dark mode” on a browser level with an extension, e.g. [Hacker Vision](https://chrome.google.com/webstore/detail/hacker-vision/fommidcneendjonelhhhkmoekeicedej) for Chrome.

**Comment by dav-** [comment]
I've cloned the repo and now run DevDocs locally with my own dark color theme based on Monokai. I could share it if anyone is interested.

**Comment by theblacklion** [comment]
@dav- Would be nice if you could share that.

**Comment by dav-** [comment]
@theblacklion Here is my fork: https://github.com/dav-/devdocs
Just follow the instructions in the README to run it locally.

**Comment by theblacklion** [comment]
@dav- Thanks! Will have a look into it as soon as I can :). Screenshot is looking nice. I really like the base16-eighties dark theme. So this is very close...

**Comment by Thibaut** [comment]
Hey guys! I started implementing a dark theme a few weeks ago but didn't get to finishing it. One issue is that most of the doc icons don't look good on a dark background (some are almost invisible). But I'll try to finish that theme anyway in the coming weeks.

**Comment by theblacklion** [comment]
@Thibaut What would speak against pushing your work out and mark the theme as alpha. Then @dav- and others could support you in getting it done.

**Comment by epistemex** [comment]
@Thibaut that's great news +1. You're doing a great job with this project and it's very useful. Having a dark theme will be a tremendous helpful as toggling between a dark IDE and white pages feels like a camera flash for soar eyes :-)

I took a shot at the icon sprite-sheet. I updated (and optimized its size). Can be found here: https://github.com/epistemex/DevDocs_icons/blob/master/icons_dark_theme_opt.png

**Comment by Thibaut** [comment]
Dark theme is up: http://devdocs.io :)

Feel free to improve the colors and open a pull-request:
https://github.com/Thibaut/devdocs/blob/master/assets/stylesheets/global/variables-dark.scss

**Comment by theblacklion** [comment]
Nice work! First test revealed that you can definitely improve the colors of PHP code snippets (dark blue is not very readable on dark gray).

**Comment by Thibaut** [comment]
@theblacklion PHP is the only documentation that uses the same syntax highlighting as on the original documents. The other docs should have better colors.

**Comment by adius** [comment]
Finally! Very cool! =)

**Comment by binaryannie** [comment]
Yay! Thanks for the dark theme it's awesome!

**Comment by csalv5** [comment]
Finally! Nice colors, danke =)

**Comment by jcpst** [comment]
Thank you for the dark theme!!

**Comment by kevinvangelder** [comment]
:100: Thanks for the dark theme!

**Comment by Martin1887** [comment]
Thanks, it is great!

**Comment by theblacklion** [comment]
@Thibaut Yeah, the others are looking nice :). Do you mind fixing that, too?

**Comment by mMontu** [comment]
This is great!!
Just a small suggestion: it would be nice to have this feature mentioned on the "Tips", it could save some time for new users. 

(it took me a while to find a mention of ""Toogle light" preference" (on #259) by searching the issues, and a longer time to notice the small icon that sometimes appear on the left panel)
