### ISSUE TITLE
Install works, can't connect through localhost or [ip]

### ISSUE THREAD

**Issue by 1fabunicorn** [Thibaut/devdocs#730]
Hey there. I used the instructions on the readme, and did the `bundle exec rackup`, but when I try to access it, it "refuses to connect". It even gives me the 
`Thin web server (v1.7.2 codename Bachmanity)`
`Maximum connections set to 1024`
`Listening on localhost:9292, CTRL+C to stop`
after the `bundle exec rackup`

Thanks!

PS. It fails when ran as normal user and root

**Comment by j-f1** [comment]
How are you connecting to the development server?

**Comment by 1fabunicorn** [comment]
@j-f1 what do you mean? like how am I downloading the docs?

**Comment by Thibaut** [comment]
What OS are you using? Could you post screenshots? (what you see in the browser, etc.)

This sounds like a problem with your local environment, not an issue in DevDocs.

**Comment by 1fabunicorn** [comment]
![ishue](https://user-images.githubusercontent.com/19752126/33527500-045d445a-d820-11e7-97e3-5720039b3426.jpeg)

You could be right... when I ` wget localhost:9292`
it gives me  `::1 - - [03/Dec/2017:17:44:47 +0100] "GET / HTTP/1.1" 200 7591 20.8140`
on the window I ran `rakeup`

**Comment by j-f1** [comment]
Can you try visiting `localhost:9292` instead?

**Comment by 1fabunicorn** [comment]
it works...

**Comment by j-f1** [comment]
I think the server doesn’t listen on your IP address because that would be a security risk since anyone could access the server. Instead, it only listens on `localhost`, so you have to use `localhost:9292` or `127.0.0.1:9292`.

**Comment by 1fabunicorn** [comment]
yeah, but I don't have a xserver on there. Meaning I can't do that. I have confirmed that it most likely isn't a firewall problem, cause I use [huggins](https://github.com/huginn/huginn) the same way I am trying to use devdocs

**Comment by j-f1** [comment]
Try `rackup -o 0.0.0.0`, which will make the server accessible via the network.

**Comment by 1fabunicorn** [comment]
yay! It works! Thank you!!!
