### ISSUE TITLE
Add support for Awesome-lists

### ISSUE THREAD

**Issue by michalczaplinski** [Thibaut/devdocs#737]
It would be awesome we could add "awesome" lists as an new kind of documentation. 
Examples: 
• https://github.com/vinta/awesome-python
• https://github.com/avelino/awesome-go

Use case: 
I very frequently find myself searching through one of those "awesome" lists when I use a technology that I'm not intimately familiar with in order to find the right library/package for to accomplish a particular task.

I think it would make sense to group all the "awesome" lists under the top-level `Awesome` label like:

```
• Async
• Awesome
|-- awesome-python
|-- awesome-go
|-- awesome-something-else
• Backbone.js
```

Is this something that you would be interested in seeing added @Thibaut ?

**Comment by Thibaut** [comment]
Please read the [contributing guidelines](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations) regarding documentation requests. What you're suggesting wouldn't be straightforward to implement, but contributions are welcome.

**Comment by j-f1** [comment]
Also, IMO these would not be very helpful offline, since they’re just collections of links to online resources.
