### ISSUE TITLE
Offline dark theme

### ISSUE THREAD

**Issue by mdh34** [Thibaut/devdocs#745]
While offline, dark theme options aren't respected
Steps to reproduce:

- Go offline
- enable dark theme in preferences
- reload page

The page just defaults back to the white theme on a reload
tested on chrome 64 beta and using webkit2

It looks like a problem with the application cache - perhaps the settings or dark css aren't cached fully?

**Comment by Thibaut** [comment]
Duplicate of #745.

**Comment by mdh34** [comment]
#745 is this issue

**Comment by Thibaut** [comment]
Oops. I meant #613.

**Comment by mdh34** [comment]
Ah :)

**Comment by j-f1** [comment]
Duplicate of #613
