### ISSUE TITLE
Can't constrain search to C or C++ docset

### ISSUE THREAD

**Issue by Ambrevar** [Thibaut/devdocs#746]
Allow me to resurrect #151: Typing "C<tab>" expands to CSS, while "C++<tab>" moves the browser selection to the "x" button (the button to clear the selection to the right of the input).

Any solution / workaround?

**Comment by Snapy** [comment]
You just need to enable them and it will work (I just tried and it did).

**Comment by Ambrevar** [comment]
Silly me, I forgot I had just changed computer... OK, problem solved.
