### ISSUE TITLE
Rename OpenJdk to Java

### ISSUE THREAD

**Issue by CorruptComputer** [Thibaut/devdocs#747]
It is not very intuitive to have these named as such, and at first I thought this didn't have the JDK docs. Also it might be helpful, but something similar is [Zeal](https://github.com/zealdocs/zeal/). They seem to have docs available which aren't available from this site.

**Comment by Kaijiro** [comment]
Instead of renaming maybe we could have a `java` alias that points to OpenJdk Docs

**Comment by ceshihao** [comment]
It seems to be a3e8a4e

**Comment by Kaijiro** [comment]
You're right, I didn't bother checking anything before replying, thank you @ceshihao.

So @CorruptComputer, you can type `java` in the search field then hit `Tab` and then OpenJDK docs would be automatically selected. Is this behavior acceptable for you ?

**Comment by CorruptComputer** [comment]
Oh yeah that's fine! When I tried the site I was just scrolling through and couldn't find it at first.

**Comment by Kaijiro** [comment]
Glad we could help you !
If you do not have any additional problems related to this issue, don't forget to close it ;)

**Comment by CorruptComputer** [comment]
No further issues, maybe make an alias that would show up in the list as 'Java' and then just link to that? So people who are just browsing through can more easily see it.
