### ISSUE TITLE
Add Inspec to Devdocs

### ISSUE THREAD

**Issue by djessich** [Thibaut/devdocs#751]
May it be possible to add Inspec (by Chef) to DevDocs? If it would be added, it is not required anymore to switch between DevDocs and Inspec reference documentation during development. As Inspec is heavily used for Chef development, it would be incredible if it could be added.

**Comment by Thibaut** [comment]
Please read the [contributing guidelines](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations).
