### ISSUE TITLE
Formatting / scraping issue in Ansible documentation

### ISSUE THREAD

**Issue by du5tball** [Thibaut/devdocs#752]
I think the issue is obvious when comparing the official documentation and the one on devdocs side to side:

http://docs.ansible.com/ansible/latest/oc_module.html vs https://devdocs.io/ansible/oc_module

**Comment by j-f1** [comment]
There isn’t an obvious bug in the scraper, so I wonder if it’s some sort of transient issue that can be fixed with a re-scrape.
