### ISSUE TITLE
Is it OK to use this project's asset in a related project?

### ISSUE THREAD

**Issue by qwfy** [Thibaut/devdocs#762]
I created a [deskop app](https://github.com/qwfy/doc-browser) that uses assets produced by this project, specially:

- It ships with [icons](https://github.com/Thibaut/devdocs/tree/master/public/icons/docs) collected by this project

- It allows user to download doc sets from dl.devdocs.io

- It caches https://devdocs.io/application.css for offline use

I have [pointed out](https://github.com/qwfy/doc-browser#credits) that my project uses this project's asset. And the desktop app itself is open source, non-commercial and is under MPL-2.0.

Is it OK for me to do so?

**Comment by Thibaut** [comment]
Hey - sorry for the delay.

This is all OK, but please make sure to visibly credit DevDocs inside your app.

> It allows user to download doc sets from dl.devdocs.io

Keep in mind that I make no guarantee to support `dl.devdocs.io` forever.

> It caches https://devdocs.io/application.css for offline use

Same here. This URL could break in the future, or there could be changes to the CSS that affect your app.
