### ISSUE TITLE
Pressing escape key goes to homepage

### ISSUE THREAD

**Issue by nvlled** [Thibaut/devdocs#764]
Is there a way to disable this? It's kind of driving me mad every time I accidentally press the escape key to more than once to close the browser's search dialog I lose context and it goes to homepage.

Edit: Huh, I guess other's have different preferences https://github.com/Thibaut/devdocs/issues/86. Anyway, I found the offending line from that issue. I'll probably do a workaround it myself if I have the time.

**Comment by Thibaut** [comment]
This is intended behavior. I recommend you use a custom script to disable this. I don't think most users would want to disable it; it's pretty standard behavior for an app.
