### ISSUE TITLE
WebExtension API

### ISSUE THREAD

**Issue by RangerMauve** [Thibaut/devdocs#766]
I'm planning on working on a new WebExtension while travelling and I noticed that the [mdn docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) for the WebExtension API aren't there, and there's no way to get arbitrary stuff off of MDN.

It would be nice if this could be added as the WebExtension API is being standardized across browsers (including Mobile thanks to Firefox) and it can be useful to more people than older, individual extension APIs.

**Comment by Cimbali** [comment]
It seems the votes for that documentation are here: https://trello.com/c/ifUY1vLi/389-webextensions

**Comment by RangerMauve** [comment]
Are PRs for stuff like this welcome? Or is it entirely up to waiting on the maintainers to decide when they want it added?

**Comment by Cimbali** [comment]
PRs seem welcome, see #705. However issues requesting docs less so according to the contributing guidelines, those are requested in trello.

**Comment by RangerMauve** [comment]
Thank you for the details! Somehow missed the Trello link!
