### ISSUE TITLE
URL contains "+" sign. The page load fails.

### ISSUE THREAD

**Issue by jhelom** [Thibaut/devdocs#767]
Hi,

URL contains "+" sign. The page load fails.

Examples)

http://devdocs.io/cpp/iterator/move_iterator/operator+
http://devdocs.io/cpp/iterator/reverse_iterator/operator+
http://devdocs.io/cpp/iterator/back_insert_iterator/operator++

**Comment by Thibaut** [comment]
URLs are different (https://devdocs.io/cpp/iterator/move_iterator/operator_plus_) but this should work now.

**Comment by jhelom** [comment]
thanks!
